### ISSUE TITLE
Write a test for https://github.com/wheresrhys/fetch-mock/pull/102

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#103]
Something along the lines of:

- require fetch-mock
- run a test using it
- require isomorphic-fetch
- run a test using it
- run a test using something else to mock fetch

**Comment by shofel** [comment]
#102 (just making a link)

**Comment by wheresrhys** [comment]
Closing due to difficulty of writing the test, and the comment in the code probably provides a sufficient guard against regression

**Comment by wheresrhys** [comment]
Similar issue still occurs. Can try to create a reduced test case working backwards from https://github.com/Financial-Times/next-product-selector/blob/master/tests/routes.spec.js

**Comment by wheresrhys** [comment]
hmmm, can't reduce the bug in the above. @GlynnPhillips - if you comment out `require('isomorphic-fetch')` in the test above does the bug still happen for you? Which node version?
