### ISSUE TITLE
Calling real URL

### ISSUE THREAD

**Issue by montogeek** [wheresrhys/fetch-mock#104]
Hi!

I am trying to use this library in the following way:
src.js
```js
import fetch from 'isomorphic-fetch';
//...
return fetch(url, options).then(responseHandle).catch(errorHandle);
```
test.js

```js
import fetchMock from 'fetch-mock';
import chai, { expect } from 'chai';
import chaiAsPromised from 'chai-as-promised';

chai.use(chaiAsPromised);

describe('GET Requests', () => {
    it('Handle a GET request', () => {
      const url = '/get';
      const response = {
        'name': {
          'first': 'Blanchard',
          'last': 'Wolfe'
        }
      }

      fetchMock
        .mock(
            `${config.BASE_URL}${url}?${querystring.stringify(config.DEFAULT_REQUEST_PARAMS)}`, 
            'GET', 
            response
         );

      let result = client.get(url);

      return expect(result).to.be.eventually.deep.equal(response);
    })
  });
```

When running the test in the browser or Node it keeps calling the real URL, since `/get` does not exist in the server, it returns a 404, making the test fail.

When logging both urls, in the test and source code is exactly the same.
Also, when logging `fetch` in the browser it returns the `fetchMock` function source code, so, it's replacing the global `fetch` correctly

**Comment by wheresrhys** [comment]
you need `import  'isomorphic-fetch';`, which will set `fetch` as a global. You can use fetch-mock to mock non global instances of fetch if you really have to (it's near the bottom of the README), but it's optimised fro global use

**Comment by montogeek** [comment]
@wheresrhys I need to import it on the tests?

**Comment by montogeek** [comment]
I am still getting the `unmatched call` warning

**Comment by montogeek** [comment]
Thanks @wheresrhys, it worked :)
By the way, I am using `fetch-everywhere`, is the same solution:
```js
import 'fetch-everywhere';
```
