### ISSUE TITLE
v5

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#111]
- [x] deprecate `greed` option
- [x] implement new `catch` method
- [x] deprecate complex config
- [x] deprecate useNonGlobalFetch
- [x] Global config for sendAsJSON
- [ ] Accept a `Response` object as a response in `.mock()` waiting on https://github.com/bitinn/node-fetch/pull/132
- [x] Expose fetch-mock's `mockResponse()` internal as a utility
- [x] reset and restore return fetchMock instance
- [x] deprecate reMock
- [ ] write upgrade notes
- [x] deprecate accepting an array of routes
  - [x] bind fetchMock.mock to fetchMock so can be passed into [].map()
- [ ] regex call matching #83 ???
- [x] API change to mock(matcher, response, options)
  - [x] get, post, put, delete, head shorthands
  - [ ] Configure number of times a mock can be used
  - [ ] mockOnce, getOnce, postOnce etc

**Comment by montogeek** [comment]
The last change to mock! 👍

**Comment by wheresrhys** [comment]
mainly done. Gonna go for a release

**Comment by wheresrhys** [comment]
https://github.com/wheresrhys/fetch-mock/pull/110

**Comment by wheresrhys** [comment]
Ah no, blocked by bitinn/node-fetch#132

**Comment by montogeek** [comment]
Just vote it :)

**Comment by montogeek** [comment]
I just saw your commit about shorthands, what you think about PATCH?

**Comment by wheresrhys** [comment]
If you want to add a PR for it after v5 is released I'll consider it if other users :+1: it. get, post, put, delete and head are the 'Big 5' methods, and as long as fetch-mock provides an api to target other methods I'm reasonably comfortable with leaving the shorthand coverage at that. I might add OPTINS too.

What's your use case for PATCH? I've never had to use it

**Comment by montogeek** [comment]
Sure, I will add it :)
I've used PATH neither, just thinking about offer more options to the users
