### ISSUE TITLE
shorthand fuynctions throwing error when passed an object

### ISSUE THREAD

**Issue by ornj** [wheresrhys/fetch-mock#112]
Since the shorthand methods are passing an object to the options argument on `mock`, both sides of the check on [line 137](https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L137) are truthy causing the error to throw. 

I'm hypothesizing that the RegEx is matching the capital O in `[object Object]` and returning true.

**Comment by wheresrhys** [comment]
good spot. I'll add a filing test and release a fix as soon as I can. PRs welcome 🙊

**Comment by wheresrhys** [comment]
duplicate of #113
