### ISSUE TITLE
Check for numeric status

### ISSUE THREAD

**Issue by montogeek** [wheresrhys/fetch-mock#118]
I hit an issue, when mocking an API response, I discovered it has a `status` key with value `ok`: `status: 'ok'`, as docs said, if the Response object has a `status` key, fetch-mock will use it to construct the Response, since `ok` is not a valid HTTP Status Code it throws this error:
```
(index):65 RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].
```

What you think about checking if it is a number before using it in https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L298 ?

**Comment by wheresrhys** [comment]
you can get around this by responding with `{body: {status: 'ok'}}`. But you're right, a check for numeric status would be good too

**Comment by montogeek** [comment]
Thanks!
