### ISSUE TITLE
Match header on request

### ISSUE THREAD

**Issue by mauricioklein** [wheresrhys/fetch-mock#120]
Sorry, but I haven't figured out how to check if a mocked request was made with a specific header.

For example:
I'm mocking a login call and I wanna be sure that a specific URL is being called with the header AUTH.

I'm trying something like that:
`fetchMock.get("http://127.0.0.1/login", {status: 'OK'}, {headers: {AUTH: '123456'}}`

But the mock is matching even without the header.

Would appreciate some help in this case.

Thanks in advance and congrats for the great job done in this lib!

**Comment by wheresrhys** [comment]
You need to do something like

```
fetchMock.mock(function (url, opts) {
  return url === "http://127.0.0.1/login" && opts.headers.Auth === '123456';
}, 200)
```
or
```
fetchMock.get("http://127.0.0.1/login", {status: 'OK'})
//call your code then
expect(fetchMock.lastOpts.headers.AUTH).to.equal('123456')
```
I could extend the options object to accept some headers to check too. Or possibly add a utility method e.g. 

```
fetchMock
   .get(url, response)
   .with(name, value) // applies to the last mock added only
```
... which'd be a nice API, but not sure what I'd call the method

**Comment by mauricioklein** [comment]
Thanks for the clarification! :)

**Comment by wheresrhys** [comment]
Reopening to remind me to consider adding a nicer api for header matching

**Comment by lucasalmeida92** [comment]
I used this approach and didn't workout :/
```
fetchMock.get("http://127.0.0.1/login", {status: 'OK'})
//call your code then
expect(fetchMock.lastOpts.headers.AUTH).to.equal('123456')
```

Here my code:
```
it('should get config from api', () => {
      const configID = 'abcdefghij',
            sessionID = '123456',
            headers = {
              'x-config-id': paymentConfigID,
              'x-session-id': paymentSessionID
            };

      fetchMock
        .get(
          '/api/config',
          {
            status: 200,
            body,
          },
          { headers }
        );

      const store = mockStore({body});

      return store.dispatch(actions.getConfig(configID, sessionID))
        .then((response) => {
          expect(fetchMock.lastOptions.headers['x-config-id']).to.equal(configID);
          expect(fetchMock.lastOptions.headers['x-session-id']).to.equal(sessionID);
          expect(response).to.be.deep.equal(body);
        });
});
```

Here the error i get in console:
![image](https://user-images.githubusercontent.com/5767871/30396470-1c7b640a-98a0-11e7-8eba-9cda8496beb0.png)


Any idea how to solve this?
Tks in advance

**Comment by wheresrhys** [comment]
thanks for the code sample. I'll investigate tomorrow

**Comment by wheresrhys** [comment]
There are a couple of mistakes in your code
1. headers should be passed to fetch-mock as a property of the section option - the section option alone is used to configure the response. The third option is for a variety of things, mainly to do with decisions on when to match responses
2. `lastOptions` is a function, so must be called to get at the last options

```
it('should get config from api', () => {
      const configID = 'abcdefghij',
            sessionID = '123456',
            headers = {
              'x-config-id': configID,
              'x-session-id': sessionID
            };

      fetchMock
        .get(
          '/api/config',
          {
            status: 200,
            body,
            headers }
        );

      const store = mockStore({body});

      return store.dispatch(actions.getConfig(configID, sessionID))
        .then((response) => {
          expect(fetchMock.lastOptions().headers['x-config-id']).to.equal(configID);
          expect(fetchMock.lastOptions().headers['x-session-id']).to.equal(sessionID);
          expect(response).to.be.deep.equal(body);
        });
});
```

**Comment by lucasalmeida92** [comment]
I knew it was something stupid D;

Thank you @wheresrhys !
