### ISSUE TITLE
TypeError: fetchMock.mock is not a function

### ISSUE THREAD

**Issue by getmetorajesh** [wheresrhys/fetch-mock#125]
When using fetchMock with typescript its always throwing error as below, 

`TypeError: fetchMock.mock is not a function`

My imports are as below,

```
import 'isomorphic-fetch'
import * as fetchMock from 'fetch-mock';
import * as sinon from 'sinon'

...
  beforeEach(() => {
     fetchMock
    .mock('http://testurl', 200);

```

edit: I tried again by changing packages path to look for `client.js` instead of `fetch-mock.js` in my `systemjs.config.js`and it worked. Not sure what's going on in here.

**Comment by wheresrhys** [comment]
glad you figured it out

**Comment by yBandarenka** [comment]
http://2ality.com/2014/09/es6-modules-final.html
