### ISSUE TITLE
Returning Promise in older browsers

### ISSUE THREAD

**Issue by andreasgruenh** [wheresrhys/fetch-mock#132]
Hello together,

I'm using fetch-mock to create a fake-backend for development. That's why every request fails with a specific probability and gets resolved after x ms. In chrome this works fine, but in IE and Firefox, it doesn't. I searched through the fetch-mock source a bit and noticed, that this line:

`if (response instanceof Promise) {`

is always returning false in Firefox and in IE.

Update: I investigated some more and i found out that `Promise` in the fetchMocks source is not the same as `Promise` in my source... I guess some Babel or webpack vodoo is going on there :x

Update 2: I could fix this by removing the babel-runtime plugin from my webpack config. Still not sure what is really causing this...

Update 3: Okay I think I understand this now: `babel-plugin-transform-runtime` replaces every call to built in ES6 types (like Promise) with a reference to the babel-core polyfill, so it does NOT polyfill the globals. Since babel should not convert node_modules/ it cannot convert the Promise inside of fetchMock, so that this Promise and babel promise don't share the same identity.

**Comment by wheresrhys** [comment]
That's really annoying. Could you try adding `{polyfill: false}` (or it might be `{polyfills: flase}`) as an option to the babel runtime plugin and see if it fixes the problem? Though I wouldn't want fetch-mock to be opinionated about your babel setup, so will probably have to a dumber check for 'thenability' of the object

**Comment by wheresrhys** [comment]
Or come to think of it, this https://github.com/wheresrhys/fetch-mock/pull/131 (just released as 5.1.3) may have fixed the problem. Please give it a go and let me know if fixed

**Comment by andreasgruenh** [comment]
Many other libraries are using

```
if (typeof action.then !== 'function') {
    return next(action)
  }
```

This could be used here.
I try the newest version later today and submit a PR if this it does not fix it.

**Comment by andreasgruenh** [comment]
Submitted the Pull Request, some additions:

You should add babel-polyfill as a Peer Dependency in the commonJS version, since you need this for the library to work in older browsers.

**Comment by wheresrhys** [comment]
If you want to add a note to that effect in the troubleshooting guide
please do, but I don't like peer dependencies - they can cause annoying
install problems for people

**Comment by wheresrhys** [comment]
And there are many ways a user can decide to polyfill promises - the
troubleshooting guide seems like a good place to _suggest_ some, but I
don't think a testing utility should be opinionated about this
