### ISSUE TITLE
sendAsJson should set content-type header too

### ISSUE THREAD

**Issue by sktt** [wheresrhys/fetch-mock#147]
Just a suggestion, because me and probably others are only doing response.json() when the content-type is application/json. right now im setting it manually where i send mocked json. 

Edit: content-lenght could maybe also be implicitly set

what you think?

**Comment by wheresrhys** [comment]
Yep sounds like a good idea. I won't haev any tiem to work on fetch-mock for the next few weeks but a PR would be welcome

**Comment by wheresrhys** [comment]
On the other hand I'd want to leave room for the response to not set these... what if you want to test a response from a dodgy server that doesn't set content-length or content-type? Needs a bit of thought, but I think your suggestion could potentially be better default behaviour

**Comment by wheresrhys** [comment]
Have decided to close this. While I do see the benefits of setting some default headers, I think any API to override this behaviour risks being too confusing. Anyone using fetch-mock could easily write a helper to wrap around it to set default headers
