### ISSUE TITLE
Set main to es5/server

### ISSUE THREAD

**Issue by kirill-konshin** [wheresrhys/fetch-mock#150]
What's the point to have `main` = `src/server`? For older NodeJS installations users have to manually alter it to `fetch-mock/es5/server` and this breaks compatibility with `browser` property of `package.json`, Webpack cannot locate proper file, so the code can't be universal.

**Comment by wheresrhys** [comment]
Which node version? If it's 0.x then I'm afraid that defaulting to the uncompiled source code makes it easier to work with in newer node versions, and that's a bigger priority for me. If `src/server` won't run on  a later version of node then that's a bug which I'll fix. 

Could you explain the problem you're having with webpack? Webpack is very configurable, and you can point most file path strings at any file you want using the `resolve.alias` property in config.

**Comment by kirill-konshin** [comment]
I have same set of tests for:

- Browser
- Node 0.x
- Node 4+

Browser tests are compiled by webpack so yes, there I can use alias. But for Node 0.x I need to point to `es5/server`. So webpack is unable to pick up proper version w/o manual alias, which is bad.

Since you still deliver the pre-compiled version too, what's the point to deliver both? Why not just precompiled for all Node versions + proper `browser` property in `package.json`, this will allow config-free usages for all use cases.

**Comment by wheresrhys** [comment]
It's an easier development and debugging workflow working in the src code rather than compiled. As pretty much the only maintainer of this repo I'm going to stick to my priorities here. 

You should be able to use `es5/server` in all your tests, and then use a webpack alias in the browser to point it at `es5/client`, so there is a workaround available. If you want to add this to the bottom of the README I'd accept a PR.

**Comment by kirill-konshin** [comment]
I totally understand your priorities :)

I did the stuff exactly as you described and it's kinda awkward... 2 workarounds (`fetch-mock/es5/server` require instead of just `fetch-mock` and alias in Webpack config) is really an overkill for such an easy case.

Btw, what's there in the SRC that can't be ported to ES5 (manually) so that all Node versions will always use same SRC? I mean are you sure that benefits of having advanced stuff in SRC outweighs downsides (build procedure, tricky configuration for old Nodes, README sections, etc.)?

**Comment by wheresrhys** [comment]
It's mainly arrow functions. While it is would be possible to convert the code to be node 0.x compatible, unless there's something in CI to test in multiple versions of node, then it'll be vulnerable to regressions. 

I sympathise with your having to write hacky workarounds to get your tests running in node 0.12, but even nodejs doesn't officially support 0.12 any more, so I don't feel I should optimise for a deprecated environment. If there were no workarounds possible then I would be open to changing the codebase to support 0.12.
