### ISSUE TITLE
Ability to have instantiations of fetchMock for easier testing using Dependency Injection pattern

### ISSUE THREAD

**Issue by lukehesluke** [wheresrhys/fetch-mock#151]
As I understand, the current implementation is made explicitly for the use-case of mocking out a global polyfilled fetch (e.g. github/fetch or isomorphic-fetch). I'm sure this is the most common use case, but I would prefer to use a fetch-mock that isn't a global object, and that doesn't alter any global state. I think this option would have a few benefits:

1. Writing tests can be easier using Dependency Injection as the tests can be stubbed more easily and safely
2. Can run tests concurrently with no issue
3. Not vital to call .restore() after single use fetch mocks
4. Can use un-polyfilled fetch implementations like 'fetch-ponyfill' or 'node-fetch'

Here's a quick sketch of how I imagine this would look:
```
/* src/fetchyStuff.js */
// 'fetch' is injected into this function, defaulting to use "node-fetch" (or 'fetch-ponyfill', 'isomorphic-fetch', etc)
function isRequestSuccessful(fetch) {
  if (!fetch) { fetch = require('node-fetch'); }
  return fetch('http://somewhere.com/stuff')
    .then(function (response) { return response.status === 200; })
}


/* test/fetchyStuff.js */
var mockFetch = require('mock-fetch');
var expect = require('chai').expect;
var isRequestSuccessful = require('../src/fetchyStuff').isRequestSuccessful;

// These two mockFetchs won't step on each other's toes
// No need to call .restore() if only used once
var mockFetch1 = mockFetch.ponyfill({realFetch: require('node-fetch')})
  .get('*', {status: 200, body: 'success'});
var mockFetch2 = mockFetch.ponyfill({realFetch: require('node-fetch')})
  .get('*', {status: 500, body: 'error'});

describe('isRequestSuccessful()', function() {
  it('should return true for successful requests', function() {
    return isRequestSuccessful(mockFetch1).then(function(isSuccessful) {
      if (!isSuccessful) { throw new Error() }
    })
  })

  it('should return false for unsuccessful requests', function() {
    return isRequestSuccessful(mockFetch2).then(function(isSuccessful) {
      if (isSuccessful) { throw new Error() }
    })
  })
})
```

Not sure if this fits as a feature for this project, or perhaps an entire fork

Either way, I'm down to help out as necessary

Peace, x

Edit: "ponyfill" isn't a typo - reference to https://ponyfill.com/

**Comment by wheresrhys** [comment]
This is probably already covered (see the alternative installation guide in the README). Let me know if it doesn't cover any use cases you're thinking of

**Comment by lukehesluke** [comment]
Hi @wheresrhys. Would love to. As usual, naming is the main issue. Makes sense to have a clear distinction between polyfilled fetch mock (which should continue to be a singleton) and ponyfilled fetch mock (which should be instantiated). Not sure something like 'fetchMock.Ponyfill' is the clearest though

Regardless, will get started in the next few dizzles

**Comment by wheresrhys** [comment]
I would go for `fetchMock.getInstance()` as a static method. There'll be some tedious, and possibly tricky, work needed to persist the environment specific config (`src/client` and `src/server`) across instances too

**Comment by wheresrhys** [comment]
or `fetchMock.sandbox()`? I like the idea that this would return a function which can be injected as  `fetch`, but also has all the methods of `fetch-mock`, and these act to configure itself. 

```js
const myFetchReplacement = fetchMock
  .sandbox()
  .mock('http://place.com', 200)
  .catch(404) // returns a function
```


Not exactly sure what's the neatest way to code this.

**Comment by wheresrhys** [comment]
```
	sandbox () {
		const instance = new FetchMock();
		return Object.assign(instance.fetchMock, instance);
	}
```
?

**Comment by wheresrhys** [comment]
I think this should do it. Let me know what you think https://github.com/wheresrhys/fetch-mock/pull/152
