### ISSUE TITLE
Error: The API for method matching has changed

### ISSUE THREAD

**Issue by romeroyonatan** [wheresrhys/fetch-mock#153]
I had the error `Error: The API for method matching has changed` with this fragment of code:

```javascript
fetchMock.get('http://example.com', 'OK');
```

Thanks

**Comment by wheresrhys** [comment]
which version?

**Comment by wheresrhys** [comment]
Ah I see, yeah that will happen. Maybe I should remove that error now and assume users have had enough time to upgrade from the old API
