### ISSUE TITLE
Disabling response object magic

### ISSUE THREAD

**Issue by kirkov** [wheresrhys/fetch-mock#163]
Hi
Would it be possible to add a global config option to disable the following: 

> `object`: As long as the object does not contain any of the properties below it is converted into a json string and returned as the body of a 200 response. If any of the properties below are defined it is used to configure a `Response` object

I was "bitten" by this behavior by changing a variable name from `statusCode` to `status` and couldn't figure out why my mock were failing. 

Love the library btw!

**Comment by wheresrhys** [comment]
`fetchMock.setConfig({sendAsJson: false})` gives you that behaviour I think. It coudl do with being referenced in that bit of the docs though

**Comment by kirkov** [comment]
> Unless you're asking for the opposite... to always convert objects passed in to json?
Yes, that it what I want. I don't want fetch-mock to change the response based on the keys of the object I provide.

**Comment by wheresrhys** [comment]
I'll leave this open to see if anyone else :+1:'s it, but there is a way to avoid this problem using the existing api: `fetchMock.mock(url, {body: {your object in here}})`

I could make the check for 'should I treat this object as response config?' stricter, e.g. by checking that no properties not in a whitelist exist on it, but that would be a breaking change

**Comment by kirkov** [comment]
Yeah, calling `fetchMock.configure({ sendAsJson: false })` and the handling the `JSON.stringify` myself solves the problem. However I still think a config option like `disableConfigureProperties: true` or something like that would great to have and not be a breaking change.

**Comment by wheresrhys** [comment]
this will be improved in v6 by whitelisting properties that can be used in a responseConfig
