### ISSUE TITLE
is it possible to mock no response?

### ISSUE THREAD

**Issue by bufke** [wheresrhys/fetch-mock#168]
I want to force the request to not return anything - simulating a server being non existent. Perhaps I want to simulate google.com being down.

`fetchMock.mock('www.google.com', null)`

This syntax doesn't actually work. I can return an empty response pretty easy but that isn't the same as a lack of response. Is this possible to do? I'd love to unit test different states of error.

I could just not mock the url at all, but this won't work if the url typically does exist, like google.com.

**Comment by wheresrhys** [comment]
Would `fetchMock.mock('www.google.com', {throws: 'Server not found'})` work? http://www.wheresrhys.co.uk/fetch-mock/api

**Comment by JakeSummers** [comment]
This isn't working for me.  

When I do the following: 

```
try{
    fetch('http://thisSiteDoesntExist.com/foo')
        .then( res => console.log('It worked'))
        .catch( err => console.log('Promise error'));
}catch(e){
    console.log('Fetch threw!');
}
```

If I don't mock, then this will print: 

```
Promise error
```

If I use the code that @wheresrhys  pasted above (or more specifically `            fetchMock.mock(`glob:*`, {throws: 'Server not found'});`) this causes the fetch function to throw, not the promise.  This will print: 

```
Fetch threw!
```

---

I did some digging and this behavior seems to be enforced with a unit tests ([responses.test.js](https://github.com/wheresrhys/fetch-mock/blob/519f648eecbc011a6906983c560fc7681753370f/test/specs/responses.test.js#L234)):

```
			it('response that throws', async () => {
				fm.mock('http://it.at.there/', {
					throws: 'Oh no'
				});

				try {
					fm.fetchHandler('http://it.at.there/')
					expect(true).to.be.false
				} catch (err) {
					expect(err).to.equal('Oh no');
				}
			});
```

This seems odd to me.  Any input would be appreciated.

**Comment by JakeSummers** [comment]
Logged a new Issue to discuss this issue see #295.
