### ISSUE TITLE
How to: let unmatched requests passthrough and reach the original server apis?

### ISSUE THREAD

**Issue by andreawyss** [wheresrhys/fetch-mock#169]
I only want fetch-mock to create mock responses for only the registered matchers.
I a request doesn't match any matchers then I want it to go through as normal and hit the server.

Right now for these requests this warning is logged in the console:
**Unmatched GET to** https://...

**Comment by jackfranklin** [comment]
Can I ask why you're after this? I think it's more intuitive to error / warn at least when this happens because in tests you should be trying to avoid the network.

We could consider introducing a way to turn those warnings off.

**Comment by andreawyss** [comment]
Because I would like to you this library for development where selective features need to use mock API and other need to use the real server. 
When developing a new feature I will create mock APIs and get all the frontend code prototyped. When the frontend prototype is approved and the APIs signatures are finalized then backend will start being developed but the frontend continues to evolve using the mock APIs. Only when the backend is fully developed and unit tested then the 2 get integrated. 
But even at a later point if some of the server APIs become unavailable/inaccessible/broken it is easy to quickly switch back to use the mock ones so one can continue developing/fixing frontend bugs and not being blocked because of some backend issue. 
And theses same mock APIs will be used in frontend unit tests as well. But the main focus is to decouple frontend development from backend.

**Comment by wheresrhys** [comment]
`fetchMock.spy()` is designed for this. It will track calls to unmocked urls but will fall through to the underlying `fetch` implementation. It may only work when using fetch as a global though.

**Comment by andreawyss** [comment]
Excellent: ```fetchMock.spy()``` solved my problem!
Thank You, I will close this issue.

**Comment by wheresrhys** [comment]
by the way, I've been considering adding an option to spy with less verbose output. Don't have time to do it myself, but am open to a PR to implement it if you find the output a bit noisy
