### ISSUE TITLE
[SyntaxError: Unexpected end of input] when invoking response.json()

### ISSUE THREAD

**Issue by Zephir77167** [wheresrhys/fetch-mock#171]
Hi,

I'm trying to unit test the code handling the calls returning an error.

For that, I do:

```
import fetchMock from 'fetch-mock';

try {
    fetchMock.once('error', 400);
    const res = await fetch('error');

    const error = new Error(res.statusText);
    error.response = res;
    throw error;
} catch (err) {
    const error = await err.response.json();
    console.log(error.message)
}
```

And `await err.response.json()` throws [SyntaxError: Unexpected end of input]

This code works well if I remove `fetchMock.once('error', 400);` and replace the url with a valid one.

Any ideas why the mocked response doesn't match the response from the real fetch? Am I doing something wrong?

Thanks in advance!

PS: Here is the output of console.log(err.response):

```
Body {
      url: 'error',
      status: 400,
      statusText: 'Bad Request',
      headers: Headers { _headers: {} },
      ok: false,
      body: 
       Readable {
         _readableState: 
          ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [],
            length: 0,
            pipes: null,
            pipesCount: 0,
            flowing: null,
            ended: true,
            endEmitted: false,
            reading: false,
            sync: true,
            needReadable: false,
            emittedReadable: true,
            readableListening: false,
            resumeScheduled: false,
            defaultEncoding: 'utf8',
            ranOut: false,
            awaitDrain: 0,
            readingMore: false,
            decoder: null,
            encoding: null },
         readable: true,
         domain: null,
         _events: {},
         _eventsCount: 0,
         _maxListeners: undefined },
      bodyUsed: false,
      size: 0,
      timeout: 0,
      _raw: [],
      _abort: false }
```

**Comment by wheresrhys** [comment]
which url is fetch calling?

**Comment by wheresrhys** [comment]
is this in node or in the browser? if the latter, native fetch or polyfilled?

**Comment by wheresrhys** [comment]
I think it's because statusText is not the response body. `res.json()` or `res.text()` give you the result of streaming (and parsing) the response body, but statusText is not part of the body. It's something closer to a header (not sure if technically _is_ a header without checking the http specs... which I'll leave to you to do if you like).

So for your example `response.text()` returns and empty string, which is invalid JSON

**Comment by Zephir77167** [comment]
I run my tests in node. In my case, when my test cases are concerned with fetchs that should fail, they go through the code invoking `err.response.json()`, which is my "error handling" and works well with the native fetch. I can't see how I am suposed to use fetch-mock if I can't mock failing calls... Or maybe I am missing something?

PS: My code is the same as here: https://github.com/github/fetch#handling-http-error-statuses

**Comment by Zephir77167** [comment]
I'm sorry but I need the answer in order to unit test my app so I re-open the issue.

**Comment by wheresrhys** [comment]
Your mock responds with a basic 400, which has statusText but no body
content. You can't .json() a response if it has no body content.

Try {status:400, body: {message: 'blah blah' }}

**Comment by Zephir77167** [comment]
Indeed, that works now! Thank you very much
