### ISSUE TITLE
requirejs conflict (amd vs browserified)

### ISSUE THREAD

**Issue by gertcuykens** [wheresrhys/fetch-mock#172]
When I use `es5/client-browserified.js` I think it conflicts with globals from `requirejs` ?

`client-browserified.js` does more than creating a `fetchMock` global I think and overwrites `require` too?

Is there a way to make it a `amd` module I can use with `requirejs` ?

**Comment by wheresrhys** [comment]
Without more details of what the exact setup error is I can't help I'm afraid. It _shouldn't_ interfere with any requirejs globals as all variables in fetchMock are either local, speced globals (such as fetch, Request etc) or those used by browserify to build the bundle (and I've never had any problems with browserify being leaky).

**Comment by gertcuykens** [comment]
Hmm ok here in my case `require` get overwritten by another version that is in the client-browserified.js Maybe start from `client-browserified.js` and search for require inside and think of it as if that could mess up `requirejs`?

```js
function loadScript(src: string) {
  return new Promise(function (resolve, reject) {
    const script = document.createElement('script');
    script.async = true;
    script.src = src;
    script.onload = resolve;
    script.onerror = reject;
    document.head.appendChild(script);
  });
}

loadScript('node_modules/requirejs/require.js').then(e => {
   loadScript('node_modules/fetch-mock/es5/client-browserified.js').then(e => {
     fetchMock.post('*', {hello: 'world'})
   }).then(e => { require(['test'], function(test){ }) })
})
```

Anyway I could be wrong about this, I will just close it if you can't reproduce.

**Comment by wheresrhys** [comment]
My advice would be to do the simplest thing possible to load fetch-mock. A script loader is probably overkill for a test helper. Why not just include as a script tag before any of the rest of your test code?

**Comment by gertcuykens** [comment]
yes then the other way around occurs with ends up working as in the browserified require end up being overwritten by requirejs.

But the main point is that I believe a generated amd module would be better for client use instead of a browserified module.

But like you point out a browserified one could be made to work too if you order the module correctly.

**Comment by wheresrhys** [comment]
Just come across this https://github.com/substack/node-browserify/issues/790#issuecomment-46636501

> browserify defers to any existing require() definitions already present so that bundles can be broken up into multiple files. It probably won't work with a non-commonjs method signature for require().

If you have the time to experiment with another module bundler for fetch-mock (webpack or rollup, for instance) and can find one that coexists happily with requirejs, then I'll accept a pull request to switch to using one of those, but I'm going to close this issue for now as it's evidently not a problem that many fetch-mock users are coming up against, and requirejs is not particularly widely used these days.

**Comment by gertcuykens** [comment]
I am using typescript directly without any packaging system to generate the amd modules and source maps on the fly. Anyway lets just wait on ES6 modules to be in browsers, then we don't need all the packaging bs anymore anyway.

**Comment by tkalfigo** [comment]
Another possible solution can be https://github.com/rse/browserify-derequire which:

> applies [derequire](https://www.npmjs.com/package/derequire) in order to rename all require() calls to _dereq_() calls in the bundle output.

This solved for us the conflict between requirejs, which uses global `require()`, and browserify's `require()`.
