### ISSUE TITLE
Support for 1xx status codes

### ISSUE THREAD

**Issue by aliceriot** [wheresrhys/fetch-mock#174]
Hey y'all,

I'm working on upgrading from `fetch-mock@4.4.0` to `fetch-mock@5.9.4` and I'm running into a small difficulty. It seems like `fetch-mock` no longer supports mocking HTTP status codes below 200, based on this line in the code:

https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L164

I was wondering if this was intentionally removed - I didn't see anything relating to it specifically in the associated PR or issues. Our codebase currently has a few tests that check the handling of 100 and 199 status codes, so I'm wondering if this was an intentional change or a regression.

Thanks for reading!

**Comment by pimterry** [comment]
I think that's because fetch itself doesn't support status codes below 100. If you try to build a native fetch response in Chrome for example (`new Response("", { status: 100 })`) it refuses:

```
The status provided (100) is outside the range [200, 599].
```

Do you have a case where you're seeing real 100s coming back from a fetch request in the real world?

**Comment by aliceriot** [comment]
I don't think we do - I think it's just a case of an over-eager unit test 😆 

Thanks for clarifying - I think we can close this.
