### ISSUE TITLE
Can you maintain a ChangeLog for your package?

### ISSUE THREAD

**Issue by heath-guidewire** [wheresrhys/fetch-mock#175]
It will help people figure what kind of changes they will be getting when they are trying to decide whether to upgrade to a new minor version.  Thanks!

**Comment by wheresrhys** [comment]
I'll update the release process to one that publishes to npm based on github releases at some point (been meaning to do so for a while) and then the github releases page will provide a changelog. I'm not willing to go back and retrospectively update the existing releases though - would be a lot of work.

IMHO there's no strong reason to pin to a minor or specific version of a package only used to run tests. Using a `^` semver range for fetch-mock is my advice.

**Comment by wheresrhys** [comment]
As this project has shared ownership I don't think I can apply the approach above without sharing my npm credentials, which I'm not happy to do. I will however endeavour to add at least a meaningful title to every minor/major release, starting today https://github.com/wheresrhys/fetch-mock/releases/tag/v5.10.0
