### ISSUE TITLE
Feature Request - output not done calls

### ISSUE THREAD

**Issue by Ragnar-Hardarson** [wheresrhys/fetch-mock#176]
I'm setting up my mocks with the _times_ property in beforeEach and checking if they are done in afterEach.

```
beforeEach(() => {
    //Initial calls made when rendering component
  fetchMock.get('end:/some-resource', { body: { foo: 'bar' }, status: 200 }, { name: 'foo', times: 1 });
  fetchMock.get('end:/another-resource', { body: { bar: 'foo' }, status: 200 }, { name: 'bar', times: 1 });

  renderComponent();
});

afterEach(() => {
  expect(fetchMock.done('foo')).toBe(true);
  expect(fetchMock.done('bar')).toBe(true);
});
```

I'd like to test all the routes at once, which can be achieved with `expect(fetchMock.done()).toBe(true);`
but that won't tell me which route isn't done.

## Ideal
```
beforeEach(() => {
    //Initial calls made when rendering component
  fetchMock.get('end:/some-resource', { body: { foo: 'bar' }, status: 200 }, { name: 'foo', times: 1 });
  fetchMock.get('end:/another-resource', { body: { bar: 'foo' }, status: 200 }, { name: 'bar', times: 1 });

  renderComponent();
});

afterEach(() => {
    //This will catch all calls and output the faulty routes
  expect(fetchMock.notDone()).toBe([]);
});
```

**Comment by wheresrhys** [comment]
Yep a good use case to add. I'm not sure I like your suggested API. Perhaps done should just log out a list of failures (and successes?) by default, that way you'd get the info you need by just calling `fetchMock.done()`

**Comment by Ragnar-Hardarson** [comment]
Yeah, I like outputting the failures and success.
Preferably, `done()` shouldn't log out anything unless there is a problem.
Just to keep the test log uncluttered

**Comment by Ragnar-Hardarson** [comment]
Good job @wheresrhys :)
Looking forward to trying this out
