### ISSUE TITLE
Reset does not remove routes

### ISSUE THREAD

**Issue by wyuenho** [wheresrhys/fetch-mock#177]
https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L213

Would be nice if `reset()` takes a param to clear the routes instead of just reseting the times. `reset()` doesn't reset the added routes is too surprising.

The only way to do that now is to `restore()` and then `_mock()` after and before each test. The fact that users have to call an undocumented internal method to reset routes is also rather strange.

**Comment by wheresrhys** [comment]
I'm not clear what behaviour you're after here. What do you mean by 'clear the routes' if not clearing the call history (which `reset()` does) or clearing the history + route definitions (which `restore()` does)

**Comment by wyuenho** [comment]
There are circumstances where I would like to test different responses based on the exact same request -> same url, same headers, same everything. If I separate those out into separate tests, and only call `reset()` on teardown, when the next test is run, the router will find the first route and returns it. There is no way to get at the exact same route.

Completely removing the routes will solve this issue. To maintain backward compatibility, you can allow an extra param to for the user to decide whether they want to clear the routes when resetting.

**Comment by wheresrhys** [comment]
I still don't really follow. Why not just call restore()?

**Comment by wyuenho** [comment]
Because that requires calling another internal method to mock fetch again? As I said, `_mock` is not documented, and the name suggests it's not meant to be used by outside code. The teardown happens on a per test basis inside `afterEach`, I only call `restore()` in `afterAll`

**Comment by wheresrhys** [comment]
I think I need to see a reduced case (preferably a working repo I can clone
and install) in order to see what you mean. Maybe there's some deficiency
in fetchmock, or maybe you're not using it as intended. Hard to tell so far

**Comment by wyuenho** [comment]
```javascript
// some jest test
import 'isomorphic-fetch';
import fetchMock from 'fetch-mock';

afterEach(fetchMock.reset);

describe('get', () => {
  test('success', done => {
     fetchMock.mock('http://www.google.com', 'success');
     fetch('http://www.google.com').then(response => {
        response.text().then(body => {
          expect(body).toBe('success');
          done();
        });
     })
  });
  test('error', done => {
     fetchMock.mock('http://www.google.com', 'error');
     fetch('http://www.google.com').then(response => {
        response.text().then(body => {
          expect(body).toBe('error'); <- expectation fails
          done();
        });
     })
  });

});
```

This fails because of [this](https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L114-L116). The router just returns the route in insertion order, and the response is not a part of the route matching process. There's alway no way to clear it.

**Comment by wheresrhys** [comment]
why not use `afterEach(fetchMock.restore);` ? That's the intended usage. `.reset()` is for when you want to use the same routes as previously but just want to set the call history back to zero.

**Comment by wyuenho** [comment]
I'm running out of ways to say this, so let me repeat this one last time:

Restore() unmocks, there's no public API to "remocks", there's only an internal one called _mock(). Options:

1. Clear the routes in reset.
2. Rename _mock() to monkeypatch(), publicize it.
3. Use the response as a part of route matching input.

**Comment by wheresrhys** [comment]
Restore removes everything you've setup so far so you can then just use
.mock() again.

**Comment by wyuenho** [comment]
Okay that's fine. I'm merely suggesting some small changes, could be naming, or documentation, clearing the routes in reset, or opening up the opposite of the documentaries behavior of restore(), say replace(), that replaces fetch with a mock implementation. I would never in a million years expect .mock() to replace native implementation, and reset() not clearing the routes.

**Comment by Itschrismorgan** [comment]
I can see where wyuenho's perspective is coming from.

I just spent two hours trying to figure out why two unit test wouldn't work at the same time. One was testing a good response and the other was testing a server not found scenario.

While going thru the docs, I skipped over the 'restore' section because in my mind the method name conveyed the opposite of what I was looking for. It wasn't clear to me that 'reset()' was leaving anything still setup.

It wasn't until I hit this conversation that I finally realized what I was missing.

**Comment by daneov** [comment]
I can confirm @Itschrismorgan's experience. 
`Restore` is *_not_* the name I expect for the function to `reset` all the behaviour to how it was before I started mocking out endpoints.

My scenario: Wanted to test the response for different status codes => Same route == Previously mocked state started `mocking` me (pun intended)

**Comment by wheresrhys** [comment]
it's the same semantics as sinon, a popular testing library. The behaviour in fetch-mock is documented and many more people are using it successfully than are getting confused, so changing the api would cause a lot of disruption.

This issue is **closed!**. Please no more suggestions or requests to reopen
