### ISSUE TITLE
Unable to use with Webpack

### ISSUE THREAD

**Issue by sairion** [wheresrhys/fetch-mock#18]
Because Sinon does not really work well with Webpack, using Karma-webpack with this lib will produce error on load. In order to make karma-webpack work with Sinon, plugin with `karma-sinon` is always required. I think this lib can be provided as a Karma plugin.

edit: I did not notice there was browserify instruction. But requiring `fetch-mock/client` does not work either.

**Comment by wheresrhys** [comment]
yep, there are problems with the client side version of fetch mock which I need to fix. I'll look at webpack too next time I sit down to work on it.

**Comment by DefiantBidet** [comment]
I was able to get it working in webpack by adding the following to the `plugins` section of the webpack config:
```javascript
plugins: [
  // fetch-mock
  new webpack.NormalModuleReplacementPlugin( /^fetch-mock$/, path.resolve( __dirname, 'node_modules' , 'fetch-mock/client.js' ) ),
],
```
I have a bunch of other setup, so there's a chance that this in addition to something else in my config is what's working... but in adding the above I was able to generate a build and I've got fetch returning mocked data.

**Comment by sairion** [comment]
@DefiantBidet Great! I will give it a try, thanks.

**Comment by OpakAlex** [comment]
@DefiantBidet i have issue:
```
  Error: Cannot find module "sinon"
  attests.bundle.js:604 <- webpack:///~/fetch-mock/src/fetch-mock.js:3:0

Module not found: Error: Cannot resolve module 'imports' in node_modules/fetch-mock/src
 @ ./~/fetch-mock/src/fetch-mock.js 3:12-28
```

Can you help me ?)

**Comment by wheresrhys** [comment]
Hello all

I'm working on a v2 release which will

a) remove sinon as a dependency (the mock function constructed by fetch-mock, while not having all the utility methods of sinon, gives you access to the same raw data anyway, so sinon isn't required)
b) use a load of es6, so will assume you are on nodejs@4.x.x or are using babel to transpile as part of your test framework. 

Hopefully ready this weekend

**Comment by wheresrhys** [comment]
https://github.com/wheresrhys/fetch-mock/pull/20

**Comment by DefiantBidet** [comment]
@OpakAlex I can try. do you have something i can take a look at?   
did you take a peak at the [gist](https://gist.github.com/DefiantBidet/d49cf4eee8b663eac9fb) i linked above? if so did that help at all?   

I would suggest throwing a quick scaffold together of your project that reproduces the issue and i can take a peak at that

**Comment by sairion** [comment]
@wheresrhys Great!

**Comment by OpakAlex** [comment]
i make some magick, add some loads, and it works...spent a lot of time. but it only works if `fetch` global.

**Comment by DefiantBidet** [comment]
@OpakAlex `fetch` is supposed to be a global. from the readme of `fetch-mock`:
```
fetch-mock doesn't declare fetch or Promise as dependencies; as you're testing fetch it's assumed you're already taking care of these globals
```

**Comment by OpakAlex** [comment]
it will be very good if you make some polyfill.

**Comment by sairion** [comment]
@OpakAlex Use library like [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch)

**Comment by wheresrhys** [comment]
The thinking is that you wouldn't even want to or need to use this library
unless you're already working in an environment that, either natively or
via a polyfill, supports fetch. Adding fetch to your js environment is
outside of the scope of this module
