### ISSUE TITLE
Handling `lastOptions` when using a Request instance

### ISSUE THREAD

**Issue by jamesallardice** [wheresrhys/fetch-mock#180]
The `lastOptions` method is really useful when mocking a call to fetch that uses 2 arguments (URL and options object). But when mocking a call to fetch that uses a single `Request` instance as an argument `lastOptions` will return `undefined` (understandably, since no options object was used).

It appears that most of the code in fetch-mock expects calls to fetch to pass in 2 arguments. Would you be open to a change that allows `lastOptions` to return the `Request` instance in cases where one is used?

Currently the only way I've found to handle this is to use `lastCall(route)[0]`. Is there a better way to handle it without making a change along the lines of the one I suggested above?

**Comment by wheresrhys** [comment]
Doesn't `.lastUrl()` give you what you need? It returns the first parameter I think

**Comment by jamesallardice** [comment]
Yeah I think it will... not sure how I didn't think of that one, thanks! However I still think there's some room for improvement to the API here - the methods do different things depending on the call you're mocking. I think it would make sense to allow the various methods that return data from the last request to work properly when a `Request` instance was used (`lastUrl` could pull the URL out of the `Request` instance for example). What do you think?

**Comment by wheresrhys** [comment]
that'd be a breaking change. Given that `(url, options)` is the most common function signature for fetch I think it's fine as it is. Happy to accept a PR to improve the docs though
