### ISSUE TITLE
Issue with passing a function to `mock` rather than string or regex

### ISSUE THREAD

**Issue by nikolasburk** [wheresrhys/fetch-mock#184]
The documentation states that the `mock` function can be used by passing 3 params: `mock(matcher, response, options)`.

The first one, `matcher` can either be a string or regex that evaluate against the URL or otherwise a function that takes in the request url and options and returns true or false.

![image](https://cloud.githubusercontent.com/assets/4058327/25847222/7fc615ae-34b5-11e7-8eb5-2c5167db69c4.png)

However, when just trying to get it to work my code will throw an exception:

```js
test('test', async t => {
  fetchMock.mock(function(url, options){
    console.log(`Call fetch on ${url} with options: ${JSON.stringify(options)}`)
    return true
  })
  t.pass()    
}
```

The error I get says the following:

>  Rejected promise returned by test
>
>  Rejection reason:
>
>    [Error: Invalid parameters passed to fetch-mock]

**Comment by wheresrhys** [comment]
Thanks for reporting - I'll take a look

**Comment by wheresrhys** [comment]
ah, you're not passing a response as a second parameter. I should make that error message a bit more explicit
