### ISSUE TITLE
Access to POST data in mock

### ISSUE THREAD

**Issue by mitchswaldman** [wheresrhys/fetch-mock#188]
Hello! 

I was wondering if fetch-mock has access to the POST data of an API call? It'd be awesome if I could just return the supplied POST data with a few changes. 

Cheers!

**Comment by wheresrhys** [comment]
read the bit about functions in the response bit of the api docs http://www.wheresrhys.co.uk/fetch-mock/api -it gets passed the parameters fetch was called with so you can build any response you like
