### ISSUE TITLE
Latest version breaks builds

### ISSUE THREAD

**Issue by Nickman87** [wheresrhys/fetch-mock#189]
Since the last update we are getting the following error during our test build:

```
WARNING in ./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34
webpack: Compiled with warnings.
```

Rolling back to 5.10.0 solves the issue

**Comment by branweb1** [comment]
Maybe mistaken but I think this actually a `node-fetch` issue--or rather, an issue with a `node-fetch` dependency library called `encoding` (see discussion here: https://github.com/bitinn/node-fetch/issues/41).

One way to fix this (I think) is to install `node-noop` then do this in your wepback config:

```
new webpack.NormalModuleReplacementPlugin(/\/iconv-loader$/, 'node-noop')
```

If you're running your tests in a (headless) browser, you presumably don't need `node-fetch` at all. So theoretically you could just use the client version of `fetch-mock` and ditch `node-fetch` altogether. Haven't figured out how to do this yet unfortunately.

**Comment by Nickman87** [comment]
As that is the only change between 5.10.0 and 5.10.1 I'm guessing you're right.
We run both in headless and normal mode so I'll try the suggestions given in the thread you linked.
Thanks!
