### ISSUE TITLE
How to respond request with error

### ISSUE THREAD

**Issue by sheila1227** [wheresrhys/fetch-mock#190]
Thanks for this great library!

I have a success handler and  an error hander for fetching some url in my code.
```
fetch('./some/url', {
	method: 'get'
}).then(function(response) {
	// success handler
}).catch(function(err) {
	// error handler : (
});
```
I have successfully used fetch-mock to enter  the success handler like this:
```
fetchMock.get(/some\/url/, mockData);
```
But how can I make fetchMock to reply with error so that I can test my error handler?

Thanks in advance!

**Comment by wheresrhys** [comment]
`fetchMock.get(/some\/url/, {throws: yourError})`

**Comment by ehguo** [comment]
I'm unable to replicate this with a POST, is it the same syntax?

`fetchMock.post(/some\url/, { throws: { message: 'network error' } }`

**Comment by MrJadaml** [comment]
I had to explicitly instantiate a new `Error` object in order for it to work:

`await fetchMock.patch(url, { throws: new Error('Some No Good Error'), headers });`

**Comment by dydokamil** [comment]
```    
fetchMock.getOnce(URL, () => {
  throw new Error(errorMessage)
})
```

**Comment by hiradyazdan** [comment]
anyone used above solution with Chai 4.x? For some reason deep equal for chai 4.x fails the test with, but not with Chai 3.x: @dydokamil 

```shell
Message:
  expected [ Array(2) ] to deeply equal [ Array(2) ]

Difference:

Compared values have no visual difference.
```

This only happens if I set:

```js
fetchMock.mock(URL, () => {
  throw new Error(ERROR_MESSAGE)
})
```

or

```js
fetchMock.getOnce(url, { 
	throws: new Error('Some No Good Error'), 
	headers 
});
```

But if I don't throw with an Error object, only a string it passes, but then I get which makes sense:

```shell
Warning: a promise was rejected with a non-error
```
