### ISSUE TITLE
Using `require('node-fetch').Headers` causes issues

### ISSUE THREAD

**Issue by jackfranklin** [wheresrhys/fetch-mock#192]
When matching headers that have been created with `new Headers()`, fetch-mock checks if the object is an instance of `Headers`: https://github.com/wheresrhys/fetch-mock/blob/master/src/compile-route.js#L32

The problem is that this `Headers` is hard coded to be `node-fetch`'s impl: https://github.com/wheresrhys/fetch-mock/blob/master/src/compile-route.js#L4

However, we are using whatwg-fetch, so this check fails and therefore the route isn't matched. It seems to me that `compile-routes` should be given the `FetchMock.Headers`, which contains the implementation that the user is using, and can be overwritten by them.

Does that make sense, and if so would you be happy with a PR that did the above?

**Comment by jackfranklin** [comment]
It may be better to try to duck-type if something is a `Header` by looking for a suite of functions. Also currently we rely on `Headers.prototype.raw` which is _not_ standard and seems node-fetch specific.

**Comment by wheresrhys** [comment]
HI Jack,

There is a way to pass in custom implementations of all the fetch classes - `fetchMock.setImplementations()`. Hopefully this meets your requirements. And hopefully the recent changes to fix other bugs (https://github.com/wheresrhys/fetch-mock/releases/tag/v5.10.1), which moved further away from duck-typing, won't have affected too many users

**Comment by jackfranklin** [comment]
Hey Rhys,

From what I see though setting a custom Header implementation it still doesn't affect the check in that code I linked to earlier - I did try setting a custom Header impl and it didn't work. I'll see if I can reproduce in a small test case.

**Comment by jackfranklin** [comment]
It does look that 5.10.1 might fix my issue though - I'll try it at work soon!

**Comment by wheresrhys** [comment]
Hi Jack. There was also a recent bug todo with Headers which will be fixed in a minute
