### ISSUE TITLE
Does it support react-native?

### ISSUE THREAD

**Issue by zhouzhongyuan** [wheresrhys/fetch-mock#193]
**If no, will it support react-native, and when?**
**If yes, how?**

**Comment by wheresrhys** [comment]
Could you give more information about whether you've tried to use it nad had a look at the docs http://www.wheresrhys.co.uk/fetch-mock/installation. Also take a look at this old issue https://github.com/wheresrhys/fetch-mock/issues/57

**Comment by wheresrhys** [comment]
closed due to inactivity
