### ISSUE TITLE
Response redirected mock

### ISSUE THREAD

**Issue by MartinDawson** [wheresrhys/fetch-mock#194]
Their doesn't seem to be an option to mock the `redirected` property on the response. 

See https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected

I have the following code and need to set `redirected` to true to test it.

export const submit = formData => () =>
```
fetch('/account/externalLoginConfirmation', {
  method: 'post',
  body: formData,
  credentials: 'same-origin',
}).then((response) => {
  if (response.redirected) {
    location.href = response.url;
  }
});
```

**Comment by wheresrhys** [comment]
Good spot. I had no idea that property was part of the spec. Will implement it ASAP

**Comment by wheresrhys** [comment]
This is gonna be tricky (hopefully not impossible though) https://github.com/whatwg/fetch/issues/552

**Comment by wheresrhys** [comment]
A tentative solution to this is released as https://github.com/wheresrhys/fetch-mock/releases/tag/v5.12.0. Please give it a whirl

**Comment by plong0** [comment]
Thank you for the very useful `fetch-mock` module!

I too needed some testing of `redirected: true` response.  When using `fetchMock.get()` method I had to put the `__redirectUrl` in the `response` object vs `options` object (ie. second parameter vs third parameter).

The documentation seems confusing about where this option should be placed.

This works:
```
fetchMock.get('*', { '__redirectUrl': 'http://example2.com/redirected-path' });
```

This doesn't work:
```
fetchMock.get('*', {}, { '__redirectUrl': 'http://example2.com/redirected-path' });
```
