### ISSUE TITLE
flush does not wait for the requests

### ISSUE THREAD

**Issue by cesaraaron** [wheresrhys/fetch-mock#196]
```javascript
const foo = {
  async get() {
    this.data = await fetch('http://example').then(r => r.text())
  }
}
it('should flush', async () => {
  fetchMock.mock('http://example', 'working!')
  foo.get()
  await fetchMock.flush()
  console.log(foo.data) // undefined
})
```
This too:
```javascript
...
return fetchMock
    .flush()
    .then(() => {
      foo.get()
      return fetchMock.flush()
    })
    .then(() => {
      console.log(foo.data) // undefined
    })
```
However this works:
```javascript
  ...
  await new Promise(r => setTimeout(() => r(), 50))
  console.log(foo.data) // working!
```
Am I missing something?

env:

> "jest": "^20.0.3"
> "isomorphic-fetch": "^2.2.1"
>  "fetch-mock": "^5.11.0"

**Comment by wheresrhys** [comment]
My guess is that flush waits for the fetch to finish, but not for `res.text()`

What if you try
```
const foo = {
  async get() {
    this.fetch = await fetch('http://example')
    this.data = this.fetch.status
  }
}
```
if that works, then it's somewhere on the fine line between a feature and a bug, and will require some thought. If it doesn't work, then it's definitely a bug

**Comment by cesaraaron** [comment]
Sorry dude, I'd forgot about this (I've been busy)

![screenshot_2017-06-19_18-53-24](https://user-images.githubusercontent.com/20180899/27311831-f316e44e-5520-11e7-8096-2aebe0cd1549.png)

bug then?
