### ISSUE TITLE
Upgrade from 5.9.x to 5.10.x causes error with Webpack

### ISSUE THREAD

**Issue by kirill-konshin** [wheresrhys/fetch-mock#199]
I am using `fetch-mock` together with `fetch-polyfill` and Karma Webpack to run tests.

After upgrade from 5.9.x to 5.10.x I have experienced the following error:

```
WARNING in ./~/encoding/lib/iconv-loader.js
Critical dependencies:
9:12-34 the request of a dependency is an expression
 @ ./~/encoding/lib/iconv-loader.js 9:12-34
```

**Comment by wheresrhys** [comment]
what's iconv-loader?

Please can you provide a full example of this - a repo I can clone and install to replicate the issue

**Comment by kirill-konshin** [comment]
It's a package that is used by one of sub-packages inside `fetch-mock`. You can clone https://github.com/ringcentral/ringcentral-js set `fetch-mock` to 5.10.x and run `npm run karma-webpack`.

**Comment by wheresrhys** [comment]
Ah - I think I know what's going on. node-fetch's Headers implementation is being included on the client side. Thanks for the bug report. Will attempt to fix it today
