### ISSUE TITLE
greed: 'none'

### ISSUE THREAD

**Issue by doxiaodong** [wheresrhys/fetch-mock#202]
Please check the troubleshooting guide and read the API docs before raising an issue

http://www.wheresrhys.co.uk/fetch-mock/troubleshooting
http://www.wheresrhys.co.uk/fetch-mock/api

I use `fetch-mock` to mock unready apis, but I want to get other already apis through native fetch.
please move the greed option back.

**Comment by wheresrhys** [comment]
Sorry, that option is gone for good. You can probably achieve what you need by using either the `.spy()` or `.catch()` methods
