### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by ianmetcalf** [wheresrhys/fetch-mock#203]
It looks like #201 introduced the potential for an unhandled promise rejection.

https://github.com/wheresrhys/fetch-mock/blob/e87db70b253c24399521a5d6fcb78557220b4345/src/fetch-mock.js#L204

```js
FetchMock.prototype.respond = function (response, resolveHoldingPromise) {
	response
		.then(res => {
			resolveHoldingPromise()
			return res;
		})
		.catch(err => {
			resolveHoldingPromise()
			throw err;
		})
	return response;
}
```

Since the original response promise is now returned there is no need to re-throw the error. It is not possible to catch this re-thrown error resulting in the unhandled promise rejection warning in newer versions of node.

**Comment by wheresrhys** [comment]
good spot - thanks
