### ISSUE TITLE
how to make only one API been mocked in an app?

### ISSUE THREAD

**Issue by zzzgit** [wheresrhys/fetch-mock#207]
okay, I have read some of the documentation but there is still something I don't know 
I want to make only one API been mocked, but not any others
e.g:
```
fetchMock.post("www.example.com/", {foo: "bar"}).spy()
```
finally no API will been mocked, why?

**Comment by drobannx** [comment]
@zzzgit I just went through a similar issue myself. I believe what you need to do is just mock the one api like you did above. And then after just call fetchMock.spy();

```js
fetchMock.post("www.example.com/", {foo: "bar"});
fetchMock.spy();
```

What this does by calling spy() off of fetchMock is that it tells fetchMock if it doesn't find a registered mock route for the URL, to just use the regular fetch instead for that URL.

I hope this makes sense and that it helps you.

**Comment by zzzgit** [comment]
thanks, i tried that, but it didn't work for me

**Comment by wheresrhys** [comment]
you need `fetchMock.post(/www.example.com/, {foo: "bar"}).spy()`

The matcher string matches exact urls, and I would assume your urls contain `http`, so use a regex

**Comment by zzzgit** [comment]
yes regex works for me 
but why "*foo*bar*" doesn't work?

**Comment by wheresrhys** [comment]
You need to explicitly say you're using a glob expression: 
```
fetchMock.post('glob:*www.example.com*', {foo: "bar"}).spy()
```
It's all in the docs. Let me know if you read them and it wasn't clear

**Comment by zzzgit** [comment]
sorry I havn't totally read the documentation
another question, 
```
if(typeof argu == "string"){
     // as glob
}else if (argu.constructor.name=="RegExp"){
    // as regexp
}
```
why not design it like this?

**Comment by wheresrhys** [comment]
Because exact string matching is an important use case and urls can contain
*,{}. It'd also be a disruptive breaking change.
