### ISSUE TITLE
how to disable this mock programmatically?

### ISSUE THREAD

**Issue by zzzgit** [wheresrhys/fetch-mock#208]
in some case, i want enable this tool, but not in some other situations
so, how could i enable/disable it programmatically instead of commenting/uncommenting my source code?

**Comment by wheresrhys** [comment]
Not sure what you mean. Please post a code sample

**Comment by zzzgit** [comment]
```
sthHappen().then(result=>{
    fetchMock.pause()
})
sthelseHappen().then(result=>{
    fetchMock.activate()
})
```
I need this
but I am not sure whether there is a method which can activate this tool after been `restore`d

**Comment by wheresrhys** [comment]
That'd be a pretty unusual feature - never needed anything like that
myself, and not seen it in any other http mocking libraries. Is it exactly
the same request sent each time? What sort of behaviour are you trying to
test?

**Comment by zzzgit** [comment]
I use fetch-mock for programming instead of testing.
to avoid comment/uncomment the code over and over again, I need to bind a short-cut to enable/disable this tool at anytime.

**Comment by wheresrhys** [comment]
My advice is don't use fetch-mock in production code. I honestly can't imagine why you'd need to. And there's a lot of complexity in fetch-mock, probably a lot of stuff you don't need, so a greater surface area for bugs to creep in. 

I'd recommend wrapping fetch yourself in some of your own code that decides when to use the network, and when to resolve with some synthetic response

**Comment by zzzgit** [comment]
what i really mean is how to reactivate fetch-mock after `fetchMock.restore()`?
