### ISSUE TITLE
Support response.blob()

### ISSUE THREAD

**Issue by gap777** [wheresrhys/fetch-mock#209]
node-fetch v2 supports blob() for isomorphic JS. 

So that client code can be unit tested via mocks on the server, can this package be updated to use node-fetch v2?

**Comment by wheresrhys** [comment]
Nice! Not sure when I'll get to this, so PRs implementing it most welcome

**Comment by wheresrhys** [comment]
Just noting this here as it might be useful in further removing differences between server and client side implementations https://github.com/PaulKinlan/streaming-server-sw-demo/blob/005c6045cd7091ccc8265ea7ad67cb5e4cc381ba/public/scripts/platform/node.js#L65

**Comment by wheresrhys** [comment]
waiting on node-fetch@2 getting out of alpha/beta

**Comment by mandysimon88** [comment]
Given that Blob support has been merged to `node-fetch` (https://github.com/bitinn/node-fetch/pull/200), where is the priority on this now? ;-)

**Comment by wheresrhys** [comment]
Thanks for the heads up. 

The priority is as high as users of fetch-mock make it - PRs very welcome :-). If no PRs are forthcoming I'll get round to implementing eventually... but kinda busy with other stuff right now

**Comment by wheresrhys** [comment]
node-fetch 2 is still in alpha. Blocked until it's released properly

**Comment by wheresrhys** [comment]
fetch-mock 6 beta can now be used with node-fetch 2 (it uses whichever version of node-fetch is installed in your project)

Please give it a try with blob. You'll probably need something like
```js
fetchMock.mock(myUrl, {
   body: myBlob,
   sendAsJson: false
})
```
@gap777 @mandysimon88

**Comment by mandysimon88** [comment]
Yay!!!!!

**Comment by shiraze** [comment]
I know this is an old issue, and this appears to work for some, but I get the following error:
`TypeError: response.blob is not a function`

when I have my mock set as:
`
 const myBlob = new Blob();
  beforeEach(() => {
    fetchMock.mock("*", { body: myBlob, sendAsJson: false });
  });
`

**Comment by shiraze** [comment]
I fixed the above issue by adding node-fetch as a dev dependency:
`npm i -D node-fetch`

My application doesn't need node-fetch, but fetch-mock has a dependency on node-fetch v2. Hope this helps anyone else who faces this issue
