### ISSUE TITLE
mock only one url?

### ISSUE THREAD

**Issue by damaoxianjia** [wheresrhys/fetch-mock#213]
Now, I have two fetch request, I want to only mock one. 

this is code:

```js
fetchMock.mock('http://localhost:12000/mock.json', {
    errCode: 0,
    errMsg: "ok",
    data: {
      departmentId: 10435,
      ownerAccountName: null,
      ownerBaseId: null,
      bizTypeEnumList: null
    }
})

fetch('http://localhost:12000/mock.json',{
      method: 'get',
      credentials: 'include'
    })
    .then(res=>{
        return res.json()
    })
    .then(res=>{
      document.getElementById('pre2').innerHTML = JSON.stringify(res)
    })

fetch('http://localhost:8080/mock.json',{
    method: 'get',
    credentials: 'include'
})
  .then(res=>{
     return res.json()
  })
  .then(res=>{
      document.getElementById('pre1').innerHTML = JSON.stringify(res)
  })
```

But it seems that the `http://localhost:8080/mock.json` request was invalid.

How to use ?

**Comment by wheresrhys** [comment]
Can you give more details of the error you're getting - 'request was invalid' doesn't tell me much

**Comment by damaoxianjia** [comment]
@wheresrhys this is screenshots:

<img width="774" alt="2017-08-21 10 45 59" src="https://user-images.githubusercontent.com/5652348/29501829-feeadbd6-865d-11e7-8619-3cbba765046b.png">

**Comment by wheresrhys** [comment]
ah, you need to call `.spy()`  at the end of the fetch-mock chain. As soon as you call `.mock()` the fetch function gets taken over by fetch-mock, and you need to explicitly tell it to allow unmocked calls to hit the network

**Comment by wheresrhys** [comment]
I've updated the doc to make this behaviour clearer
