### ISSUE TITLE
Allow query parameters in arbitrary order

### ISSUE THREAD

**Issue by TimoSta** [wheresrhys/fetch-mock#215]
To mock one of our API enpoints, I am using the following piece of code:

      fetchMock.get(`${apiBase}/users/${userId}/files?type=${type}&sessionId=${sessionId}`, [{id: 0}])

This works fine for the following request:

    GET dummyApiBase/users/dummyUserId/files?type=dummyType&sessionId=dummySessionId

However, if the query parameters are switched, the URL does not match:

    GET dummyApiBase/users/dummyUserId/files?sessionId=dummySessionId&type=dummyType

For our backend, the order of the query parameters is irrelevant, as long as they are present. Is there an easy way to simulate this behavior with this library, without using a RegExp or custom matcher function? If not, is this be a feature that you would be willing to add to the library if I submitted a pull request?

**Comment by wheresrhys** [comment]
Other than writing a custom matcher, you could use `.get()` twice, with the qs in a different order for both. Sorry, I won't consider adding support for this in fetch-mock at present. Closing the issue, if others reopen asking for the feature I might reconsider.

**Comment by a-x-** [comment]
created here:
https://github.com/wheresrhys/fetch-mock/issues/300
