### ISSUE TITLE
Add api to find out if fetch is currently mocked

### ISSUE THREAD

**Issue by TheMallen** [wheresrhys/fetch-mock#216]
IMO it's good practice to have a project wide `beforeEach` that throws if you forgot to restore a module. With manual mocks using `jest.fn()` and friends, it's relatively easy to throw if any of your mock utilities were not restored. With `fetch-mock` I was unable to find any built in api to do so.

I was able to create a utility for this pretty easily using `jest.spyOn` in my project, but I feel like it makes sense to be part of the api of the module. 

## Example usage
```
// each-test.js
beforeEach(() => {
  if (fetch.isMocked()) {
    throw new Error('You did not reset the fake fetch. Make sure to call fetchMock.restore() after your tests have run.');
  }
})
```

**Comment by wheresrhys** [comment]
In v6 the mocked fetch will have a property `isMock: true`
