### ISSUE TITLE
How to know the content-length when fetch-mock does the stringify

### ISSUE THREAD

**Issue by Halt001** [wheresrhys/fetch-mock#218]
When I define a response object containing a body, fetch-mock will do the stringify but it doesn't add a content-length header. I could add the header myself but then I would have to know exactly how fetch-mock is going to do the serializing, otherwise the length may not be the same. Am I missing something here?

I know the serialising is no rocket science but it is the principle of serialising and deciding the length independently that bothers me.

Maybe it is an idea to add another boolean to the response indicating weather or not the content-length header should be included automatically.

Awesome library by the way. Thx.

**Comment by wheresrhys** [comment]
Agree with all your points. I don't have any free time to work on fetch-mock currently, but would accept a PR that adds a `includeContentLength` option. It'd be nice to make it a global config option too as my hunch is that if you care about content-length for one test, you probably care about it for many tests

**Comment by Halt001** [comment]
I'm also a bit pressed for time right now but I'll check if this is something I can do.

**Comment by tvhalteren** [comment]
You have a PR.

**Comment by Halt001** [comment]
You have a PR.

**Comment by wheresrhys** [comment]
addressed by #223 & #222
