### ISSUE TITLE
sandbox() method missing

### ISSUE THREAD

**Issue by Halt001** [wheresrhys/fetch-mock#219]
I'm trying to use fetch-mock using Typescript and have installed `@types/fetch-mock` but it seems the sandbox() method is missing.

Is this method missing in the types definitions only or doesn't it exist anymore at all?

**Comment by wheresrhys** [comment]
`@types/fetch-mock`... what's that? Not written by me. Sandbox is a fairly recent addition so perhaps whoever maintains it needs to update to work with the latest fetch-mock

**Comment by wheresrhys** [comment]
Please raise an issue on https://github.com/DefinitelyTyped for this

**Comment by Halt001** [comment]
Just did: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20421
