### ISSUE TITLE
Version 6

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#220]
The basic API is OK as is, but bolt-on config changes could do with reimplementing in a more carefully thought through way
Changes
- [x] .configure method gone
- [x] setImplementations metod gone
- [x] options available via the above two methods are now set directly on the `.config` object
- [x] global option to fall through to network
- [x] content-length set by default
- [x] no longer possible to pass Promise in to sandbox
- [x] refactor src
- [x] refactor tests
- ~[ ] carefully examine all the clever bits to determine if they should be globally configurable~
- [x] make the conditions for treating an object as a response body tighter
- [x] __redirectUrl -> redirectUrl
- [x] times -> repeat
- [x] allow global setting of node-fetch version
- [x] quiet option for `.spy()` https://github.com/wheresrhys/fetch-mock/issues/233
- [x] ... or a more forgiving fallback to network method
- [x] deprecate matchers begining `^`
- [x] rout override option (global and per mock), but be forgiving when no method clash
- [x] run  tests with node-fetch 1 and 2. use the version the app has installed
- [x] support 'forking' sandboxes
- ~[ ] take account of method restrictions in names of routes~
- ~[ ] maybe... just maybe... use some sort of map as the record of calls, which will allow for more complete grouping and querying~
- ~[ ] maybe rename reset to resetHistory, clearHistory etc~
- [x] seriously think if calls, called etc can be improved
- [x] behaviour of lastUrl/lastOpts when Request used to be bent closer in line with url, opts pairs
- [x] query string ordering
- [x] filter inspection methods by headers, methods and query strings (same as when setting a route)
- [x] if any properties not on a whitelist are in the response config, then treat the whole things as json
- [x] filter calls by exact url
- [x] isMock property on fetchHandler

**Comment by skidding** [comment]
> possibly a global config to turn on falling through to network by default

Is there any way to do this in v5?

I'm trying to only mock specific endpoints and let the rest fall through but can't find a way to do it with existing API. Thanks!

**Comment by wheresrhys** [comment]
@andy-ms From reading the [history](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/fetch-mock) it looks like you're the main contributor to @types/fetch-mock. You might want to keep an eye on this PR. The changes to the fetch-mock API are more or less complete (most of the remaining work is refactoring tests, internals and making a handful more things globally configurable... none of which are likely to affect the type definition)

**Comment by andy-ms** [comment]
I just moved the file -- types authors are @asvetliakov @tamird @merrywhether @chrissinclair

**Comment by NullVoxPopuli** [comment]
I just tried out overwriteRoutes, and it causes my tests to lock up / not finish. Using Jest.
Tried globally setting it to true, and locally in a test.

```js
    beforeEach(() => {
      fetchMock.restore();
      fetchMock.config.overwriteRoutes = false;
// ...
// in a test...
 fetchMock.config.overwriteRoutes = true;
// test never completes now.
```

if overwriteRoutes is never true, then my tests finish (but with an override error)

**Comment by wheresrhys** [comment]
@NullVoxPopuli are you able to point me at a repo + branch I can replicate this in?

**Comment by NullVoxPopuli** [comment]
not opensource, unfortunately :-(

**Comment by NullVoxPopuli** [comment]
not opensource, unfortunately

**Comment by wheresrhys** [comment]
Would you be able to create a dummy repo with a minimal test case to reproduce it?

Looking at your code, you are using the config in a slightly unintended way. `config` isn't really supposed to be modified for every test - it's there to alter the default behaviour _for all tests_ if you find the default behaviour unhelpful. The following would be more idiomatic:
```
before(() => {
    fetchMock.restore();
    fetchMock.config.overwriteRoutes = false;
});

it('is a test that should overwrite a route', () => {
    fetchMock.mock('http://blah.blah', 200, {overwriteRoutes: true});
});
```
