### ISSUE TITLE
Can't mock responsecodes

### ISSUE THREAD

**Issue by jhalborg** [wheresrhys/fetch-mock#221]
Hey :)

I'm having issues returning specific response codes for some reason. I can mock 200 responses with a payload just fine using i.e.

```
const expectedResponse = JSON.stringify({ token: newTokenValue });
fetchMock.post(`${baseUrl}/auth/renew`, expectedResponse);
```

but when I want to test for failures, I can't get the code to work. I've tried calling restore() or reset() out of desperation, but not luck. 

```
    fetchMock.restore();
    fetchMock.reset();
    const response = {
      status: 503,
      body: { data: '1234' },
    };

    const options = { method: 'POST', body: { test: 't' }, headers: {} };
    fetchMock.mock('*', response, options);
```
Even with the above, I get a 200 response for the request. Is there some between-tests flushing I can't figure out?

**Comment by jhalborg** [comment]
Again, out of desperation, I moved the test to the top of the test suite (using Jest) - and then I get the correct response. I've tried doing an 

```
afterEach(() => {
    fetchMock.restore();
    fetchMock.reset();
  });
```
but it doesn't help.

**Comment by wheresrhys** [comment]
Nothing springs to mind. Why are yo setting body and headers on the options object?

I think I'd need to see a more complete test case (i.e.a repo I can clone, install and reproduce the bug in)

**Comment by andrew-cc** [comment]
@wheresrhys Ensure your test fn is either taking (and calling) `done` or using `async`/`await` correctly, see [Jest: Testing Asynchronous Code](https://facebook.github.io/jest/docs/en/asynchronous.html). (I ran into a similar issue and this resolved it—issue with the test, not code).

**Comment by wheresrhys** [comment]
Thanks andrew
