### ISSUE TITLE
Expected behaviour of non-200 status code

### ISSUE THREAD

**Issue by grug** [wheresrhys/fetch-mock#226]
Hey there,

I was wondering what the expected behaviour was for an application that has a mock for a non-200 status code.

For example, if I had a mock set up like this:

```
const response = {
      body: { foo: 'bar' },
      status: 400
};

FetchMock.get(/foo/, response);
```

And then in my application I use fetch to do a get to something matching `/foo`:

```
fetch('localhost/foo')
  .then(response => console.log(response))
  .catch(error => console.log(error));
```

What should I be expecting in my application code? That the promise is rejected? Or is there something else I need to do? It's just hard to confirm whether or not there actually has been intended behaviour (I'm not sure what it is) as the network tab obviously doesn't pick up any of this because we're not actually making a request and it looks like in my code that the promise isn't being rejected.

**Comment by wheresrhys** [comment]
The fetch spec states that all responses result in a resolved promise which exposes the status code and an `ok` property if it's not an error code. If it's an error code it's up to the developer to throw. e.g.

```
fetch('http://place.com')
  .then(res => {
    if(!res.ok) { // or coudl check for e.g. res.status === 404 etc for finer grained control
       throw new Error('fetch response not ok');
    }
  })
```

**Comment by grug** [comment]
That answers my question perfectly :)

It's interesting that the fetch spec says that everything should respond with a resolved promise and exposes an `ok` property but the XHR spec doesn't have anything like that. I'm cool with it though - I guess the project that I'm working on is the first "major" thing I've done with fetch. 

You should check it out, by the way: https://github.com/ovotech/data-mocks

It's wrapping fetch-mock and providing an interface to easily inject mocks into your application. Would love to hear your feedback.

**Comment by grug** [comment]
Hey @wheresrhys, did you get a chance to check out my repo? Keen to hear your thoughts :)
