### ISSUE TITLE
Feature Suggestion: Need to override matcher or restore specific matcher

### ISSUE THREAD

**Issue by ianwcarlson** [wheresrhys/fetch-mock#231]
This is a feature request.  My use case is I need to define a default mock for an endpoint and be able to override it in specific situations.  The library doesn't appear to support this.  Currently, once I define a mock for a matcher it can't be undone without blowing away everything.  For complex views that require many mocks, it would be nice to define default responses and then override specific ones for specific tests.  I can pass flags around, but seems like this would be a nice feature enhancement.

If the library supported restoring a specific matcher or simply overriding an existing matcher if it's identical to one already declared previously, then I think my use case would be supported.

**Comment by wheresrhys** [comment]
mmm, yeah this seems like a nice idea. Any thoughts on what the API would look like? I have an idea, but would rather hear an untainted view first

**Comment by ianwcarlson** [comment]
I think the easiest way to support this is instead of automatically pushing onto the `this.routes` array, the code could check to see if the match already exists before pushing.  Since a route is defined by a matcher, each element could store a hash, or just JSON.stringify() the matcher object, and check for that to determine uniqueness.  If a duplicate is found, then replace it with the new mock.  I'm assuming that responses don't help define the mock's uniqueness because this approach wouldn't work in that case.

I think the other idea of restoring a specific mock works similarly, but is a little more clunky for my use use since the test code would have to restore a specific mock and then mock a different variant immediately afterwards.  But maybe there's a use case for someone else?  In the spirit of agile, maybe just doing the former first would be prudent.

If you agree, I could potentially give this a shot and submit a PR.  Not sure which branch to base off of though.

Thanks.

**Comment by wheresrhys** [comment]
That seems sensible. Please submit a PR (with tests) to the v6 branch

**Comment by wheresrhys** [comment]
something which shoudl meet this need will be in v6

**Comment by ianwcarlson** [comment]
👍
