### ISSUE TITLE
Fetch-mock is not mocking the global fetch in testcafe browser

### ISSUE THREAD

**Issue by luiscspinho** [wheresrhys/fetch-mock#232]
Hello,

I'm trying to use TestCafe for my tests and I need to mock some calls to different APIs, however **fetch-mock** is not catching the global **fetch**  method.
For example, I've this simple page:

```
<body>
    <div class="w3-container">
            <p>
               <input type="submit" value="GET JSON" id="getJSON" class="w3-btn w3-blue">
            </p>        
            <div id="result" class="w3-container">--</div>

    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.js"></script>
    <script>
        document.getElementById('getJSON').addEventListener('click', getJSON);

        function getJSON(){
            fetch('/followers', {method: 'GET'})
            .then((res) => { return res.json() })
            .then((data) => { 
                document.getElementById('result').innerHTML = JSON.stringify(data);
           })
           .catch(err => console.log('ERROR CATCH', err))
        }
    </script>   
</body>
</html>
```

And for this page I created this test:
```
import fetchMock from 'fetch-mock';
import 'isomorphic-fetch'

const mockGroceries = [
    { id: 1, name: 'Pineapples', quantity: 10 },
    { id: 2, name: 'Coconuts', quantity: 1000 },
    { id: 3, name: 'Pears', quantity: 5 }
  ];

//   function makeRequest() {
//     return fetch("/followers").then(function(response) {
//       return response.json();
//     });
//     };

fetchMock.get('*', {status: 200, body: mockGroceries});

fixture `Getting Started`
    .page `http://127.0.0.1:8080/app/`    

test('My first test', async t => {
    // makeRequest().then(function(data) {
    //     console.log('got data', data);
    //   });
        
    await t
        .click('.w3-btn')
        .debug()
});
```

When the test stops, I can clearly see that the browser don't have the object **mockGroceries** in the HTML as it should be. If I uncomment the **makeRequest** function inside the test scope I can clearly see that the **console.log('got data', data)** line prints the **mockGroceries** object which means that the **fetch-mock** is indeed mocking the fetch call but only inside the test context.

I don't know if this is a testcafe problem or not, but from what I read on your documentation, testcafe should be able to access the fetch global inside a browser?

Thanks!

**Comment by wheresrhys** [comment]
I suggest bringing this up with TestCafe. Though I reckon you might be hitting [this issue](https://github.com/wheresrhys/fetch-mock/issues/198), which is outside the scope of what fetch-mock can do

**Comment by luiscspinho** [comment]
I think you're right. I'm having that same problem, thanks for your help.
