### ISSUE TITLE
Add an option to spy with less verbose output

### ISSUE THREAD

**Issue by ryanbraganza** [wheresrhys/fetch-mock#233]
Feature Request:

Following [this comment](https://github.com/wheresrhys/fetch-mock/issues/169#issuecomment-284150347)

It would be nice to have an option for spy to let unmatched calls go through to the network without warnings.

Perhaps something like:
```javascript
fetchMock.spy({quiet: true});
```

**Comment by wheresrhys** [comment]
I'll add it to the v6 todo list. closing this issue. 

Thanks for the reminder
