### ISSUE TITLE
Response returned by the mock doesn't match Response instance specified in args

### ISSUE THREAD

**Issue by bondom** [wheresrhys/fetch-mock#236]
I try to mock requests sent with `isomorphic-fetch` library. 
Code to import `isomorphic-fetch` : 
`import 'isomorphic-fetch';`

Code to mock post request:
```
fetchMock.post(
      URL,
      new Response(null, {
        status: 598,
        statusText: 'Status test',
        headers: new Headers({ 'Content-Type': 'text/xml' })
      }),
      {
        'Content-Type': 'application/json'
      }
    );
```

As a result of sending mocked request I get object with following properties:
```
      url: '..URL..',
      status: 598,
      statusText: undefined,
      headers: Headers { _headers: {} },
      ok: false,
      ....
```

As you can see `statusText` and `headers` don't match specified in Response object, only `status` is the same.
In my tests I check if fetch was called for this url(this test passes):
```
expect(fetchMock.called(URL)).toBe(true);
```

Also I reset and restore fetchMock after each test:
```
  afterEach(() => {
    fetchMock.reset();
    fetchMock.restore();
  });
```
Versions:
`npm` - `5.2.0`
`fetch-mock` - `5.13.1`

Maybe I do something wrong, please help me solve this issue

**Comment by wheresrhys** [comment]
Would you mind sending me a more complete code sample. Ideally a repo I can clone, install and use to replicate the problem

**Comment by RookY2K** [comment]
This might not be the same issue experienced by @bondom, but it seems related. So I'll add it to this issue and leave it to you to decide if you want me to create a new issue.

**Expected Behavior:**
fetchMock should return the original, unchanged response instance provided to the mock method.

**Actual Behavior**
fetchMock treats the response instance as a response configuration and pushes it into a new Response's body as JSON.

**Using**
React-Create-App
Jest with JSDOM

Reproduction:
https://github.com/RookY2K/fetch-mock-response-repro

**Comment by wheresrhys** [comment]
great - thanks for the test case. I'll check it out tonight

**Comment by RookY2K** [comment]
I don't know if you  had a chance to check it out, but I added a test case where I overrode the config with the Response provided by JSDOM's fetch implementation. All tests passed when I did that. So this may be a situation where you either:

A) Ensure you set the config initially with the global Response (I thought you did, but I may have misread the code)

B) Update the documentation to be clearer that overriding the config's Response, Request, et al may be necessary in certain cases. Currently the doc's make it seem like this is only necessary if using a non-standard fetch. 

But the good news is that this does not seem to be a bug, just a misunderstanding of how to properly set things up.

**Comment by bondom** [comment]
@wheresrhys Sorry for delay, I will send you test repo in the near future, now I am very busy

**Comment by wheresrhys** [comment]
@RookY2K A PR to add this to the troubleshooting docs (and maybe a note in the installation docs too) would be much appreciated :smile:

**Comment by RookY2K** [comment]
Be glad to. Wanted to give you the opportunity to choose between an implementation change or updating documentation.

**Comment by bondom** [comment]
@wheresrhys I couldn't replicate this problem in new repo with 5.13.1. I updated version to 6.0.0 in my initial repo, and everything works fine! So my problem is solved :) As for me this issue can be closed,
@RookY2K what do you think?
