### ISSUE TITLE
Support all fetch init options as matcher options

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#239]
Currently `headers` and `method` are supported. It makes sense to add all the following:

- [ ] destination
- [x] referrer
- [x] referrerPolicy
- [ ] mode
- [x] credentials
- [ ] cache
- [ ] redirect
- [ ] integrity
- [ ] keepalive
- [ ] signal
  
Pull requests most welcome 😄

**Comment by ianwalter** [comment]
So was signal added in https://github.com/wheresrhys/fetch-mock/pull/381?
