### ISSUE TITLE
Feature Request: Add doneAndNothingElse() to the API

### ISSUE THREAD

**Issue by tylermurry** [wheresrhys/fetch-mock#242]
In other frameworks I've used, there are functions to [specifically verify nothing unexpected happened.](http://static.javadoc.io/org.mockito/mockito-core/2.13.0/org/mockito/Mockito.html#verifyNoMoreInteractions-java.lang.Object...-)

While .done() allows you to validate what you expected to happened, it does not confirm for you that nothing _unexpected_ happened. This can technically be done by filtering .calls() on unmatched items, but the syntax is not as succinct as it could be.

I would like to propose a new api-level function **.doneAndNothingElse()** to encapsulate both of these concepts in a syntax-friendly way.

I will create a PR for this if the idea is approved, but I just wanted to throw it out there first.

**Comment by wheresrhys** [comment]
great idea 😄 , and should be easy to implement. Not sure about the name of the method though. What do other libraries call this?

**Comment by wheresrhys** [comment]
maybe an additional chainable method, which would allow users to quickly check for no unmatched calls

```
.done()
.noSurprises()
```

**Comment by wheresrhys** [comment]
Just revisiting this. As fetch-mock 6's default behaviour is to error if any unexpected calls are made, I think this feature is already covered, unless there's some subtlety I'm missing.

Closing for now - reopen if necessary
