### ISSUE TITLE
response.arrayBuffer()

### ISSUE THREAD

**Issue by piranna** [wheresrhys/fetch-mock#248]
Trying to use `Response.arrayBuffer()` I get the error `TypeError: res.arrayBuffer is not a function`, while with `Response.text()` my code works. I've searched for references to `arrayBuffer` in the source code but didn't found them, also in the upcoming v6. Maybe it's related to https://github.com/wheresrhys/fetch-mock/issues/209 and should I upgrade?

**Comment by wheresrhys** [comment]
is this on server or client side? Could you post some example code please

**Comment by piranna** [comment]
I'm using it in some ReactNative tests on Node.js. What's the difference between client and server?

**Comment by wheresrhys** [comment]
Example code please

**Comment by wheresrhys** [comment]
Closing. Please open another issue adhering to the issue template if still needed
