### ISSUE TITLE
maybe use dist tags for beta

### ISSUE THREAD

**Issue by tomatau** [wheresrhys/fetch-mock#249]
Hey there! This isn't a real bug or anything, merely a suggestion.

As you're releasing a beta version, it might be worth utilising a dist-tag on your npm release of something like beta or next, so that consumers will install the stable version by default (aka latest) and can opt in to you beta with `npm i fetch-mock@next`

**Comment by wheresrhys** [comment]
i've not heard of this before. do you havea link to the docs on this?

Should be out of beta in the next release, so academic for now though

**Comment by tomatau** [comment]
Useful to know when providing open source modules.

```
npm publish --tag=beta
```
https://docs.npmjs.com/cli/dist-tag

Btw, a separate issue: I tried the new beta but the contract for `fetchMock.calls()` is only returning a 2 level array instead of 3 levels.

IE.
I would expect (given no unmatched calls)

```js
const topLevel = [matched, unmatched]
const matched:secondLevel = [call1, call2, call3]
const call1:thirdLevel = [endpoint, options]
```

actual
```js
const topLevel = [call1, call2, call3]
const call1 = [endpoint, options]
```

I can copy paste this into a new issue if it's not already being fixed.

**Comment by wheresrhys** [comment]
Hi, the contract for calls has changed. Apologies if I missed it from the
upgrade guide. calls() always returns an array of arrays now. Matched vs
unmatched is controlled by passing a Boolean in. The same contract applies
to all the inspection methods. So calls().unmatched -> calls(false) etc.

**Comment by tomatau** [comment]
So to check that my app made 2 expected calls and no unexpected calls, I have to call calls() twice, once with true and once with false?
