### ISSUE TITLE
undefined is not a function (evaluating  'this.routes.find(...)')

### ISSUE THREAD

**Issue by jordan-enev** [wheresrhys/fetch-mock#251]
Unit testing stack (I'm [using react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit#testing)):

- karma 2.0.0
- karma-phantomjs-launcher 1.0.4
- phantomjs-prebuilt - 2.1.16
- mocha & chai & sinon

Here is the mock:

```javascript
fetchMock.post('*', { url: 'https://example.com/' })
```

When I run the tests, they failed with the following error stack:

```
FAILED TESTS:
  (Actions) Api
    ✖ Fetches `API_URL`
      PhantomJS 2.1.1 (Linux 0.0.0)
    undefined is not a function (evaluating 'this.routes.find(function (route) {
    		return route.matcher(url, opts);
    	})')
    router@webpack:///~/fetch-mock/es5/lib/fetch-handler.js:128:0 <- tests/test-bundler.js:121000:30
    executeRouter@webpack:///~/fetch-mock/es5/lib/fetch-handler.js:47:0 <- tests/test-bundler.js:120919:28
    fetchHandler@webpack:///~/fetch-mock/es5/lib/fetch-handler.js:20:0 <- tests/test-bundler.js:120892:35
    [native code]
    webpack:///src/utils/api.js:107:0 <- tests/test-bundler.js:37061:17
    fetch@webpack:///src/utils/api.js:86:0 <- tests/test-bundler.js:37032:26
    post@webpack:///src/utils/api.js:117:0 <- tests/test-bundler.js:37073:21
    post@webpack:///src/redux/middlewares/enhancedThunk.js:22:0 <- tests/test-bundler.js:90178:40
    webpack:///src/redux/actions/api.js:31:0 <- tests/test-bundler.js:36597:20
    webpack:///~/redux-thunk/lib/index.js:11:0 <- tests/test-bundler.js:84607:24
    webpack:///tests/redux/actions/api.spec.js:42:0 <- tests/test-bundler.js:95058:26
```

**Comment by jordan-enev** [comment]
I found out that the problem is that `find` method is undefined, independently of the fact that I'm using `babel-preset-env`.

It looks like there is a [Babel runtime problem with an instance methods](https://github.com/babel/babel/issues/892).

The solution is to include `babel-polyfill` once in your testing bootstrap file, and set [Babel `useBuiltIns` option](https://github.com/babel/babel/tree/master/packages/babel-preset-env#usebuiltins).

**Comment by wheresrhys** [comment]
Yeah, I'll add it to the troubleshooting guide. Thanks for raising it.

**Comment by wheresrhys** [comment]
Could you try with 6.1.0-beta.1 please

**Comment by wheresrhys** [comment]
Can you try v6.1.0-beta.2 please. Finally managed to get a new release out

**Comment by jordan-enev** [comment]
I've tested it just right now and **everything's fine**! Thank you :)

**Comment by wheresrhys** [comment]
Great thanks. I’ll release a proper version shortly
