### ISSUE TITLE
Error about overriding when using `postOnce`, `getOnce`, etc

### ISSUE THREAD

**Issue by jackfranklin** [wheresrhys/fetch-mock#254]
Hey,

Firstly, the upgrade to v6 was super smooth, thank you!

One thing that took me by surprise was that despite using `getOnce` everywhere (as a rule we use the `Once` variants), I got a lot of errors about mocks overriding each one.

If the same two tests have a `getOnce('/foo')` call, where the call is hit each time, I wouldn't expect any errors. For example:

```js
test('test 1', () => {
  fetchMock.getOnce('/foo')
  someCodeThatCallsFoo()
})

test('test 2', () => {
  fetchMock.getOnce('/foo')
  someCodeThatCallsFoo()
})
```

This code would cause an error in `test 2` (assuming they run in that order) that it's overriding a mock. I would expect this not to happen because we're using the `Once` variants.

I'm happy to provide a PR to change this or debug further if this isn't the behaviour you were expecting :)

**Comment by wheresrhys** [comment]
I wouldn't call this a bug as the library's designed to be restored after each test (though it's interesting to see not everyone uses the library the same). Your tests aren't all that isolated because, say test 1 fails to call `fetch`, then all subsequent tests would error

In your testing framework is there such a concept as `afterEach()`?

**Comment by jackfranklin** [comment]
I see what you mean; in reality say that test 1 didn't call foo I'd know about it because the test would fail in some other way (because if the test needed to call foo and didn't, that would cause a subsequent assertion to fail).

I have added an `afterEach(fetchMock.restore)` which solves the problem, I guess I was just thrown by the error originally.
