### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by kristianroebuck** [wheresrhys/fetch-mock#26]
I'm in the process of updating the `fetch-mock` and our tests broke from the jump from `2.2.8` to `2.2.9`. Could you please consider introducing a changelog to ease the pain of upgrades. 

Does `fetch-mock` adhere to semver? I'm surprised things broke on a patch update.

**Comment by wheresrhys** [comment]
Ah yes sorry, The API didn't change, only the exact file to require. I'd accidentally broken the library in PhantomJS when moving to es6 a little while ago and the only satisfactory fix was to point at a pre-transpiled file. I interpreted this as being a bugfix, though that was possibly a bit tenuous, so sorry for any upgrade pain this caused.

I'm pleasantly surprised there are actually people out there making use of the module on a daily basis, and will henceforth be more careful with versioning changes. My intention is to comply with semver so incidents like this shouldn't happen again.

**Comment by wheresrhys** [comment]
And to answer your suggestion of a changelog, now I've fixed the 2 major things I wanted to a) making the simple use cases easier to work with and b) fixing in browsers, I can't see the module changing for a  good long while. I may at some point add support for `formData` but I'd be surprised if that can't be accomplished with a minor release. If I ever do another major release I'll make suer I write some upgrade notes for it though.

**Comment by kristianroebuck** [comment]
Thank you for the explanation and don't worry about it. 

I guess it's not just me and thee using fetch-mock as you have 1,173 downloads within the past month. :+1:

**Comment by shiraze** [comment]
Time to revisit this request? Major change from 7.5.1 to 7.7.0 without a changelog makes it harder to determine where I might need to make code changes in my code

**Comment by wheresrhys** [comment]
The releases section of this repo say what has changed in each release. https://github.com/wheresrhys/fetch-mock/releases. 

I'm not sure how any of the recent changes can have been breaking unless you were relying on some edge case. Open another issue if you identify the issue and think it needs addressing.
