### ISSUE TITLE
Cannot find module 'node-fetch' from 'server.js'

### ISSUE THREAD

**Issue by jepiqueau** [wheresrhys/fetch-mock#261]
package.json should be upgraded as node-fetch@2.0.0 has been released few days ago and it seems that node-fetch-alpha.9 does not exist anymore

**Comment by wheresrhys** [comment]
thanks for the heads up. Updated now

**Comment by biswa8998** [comment]
node-fetch is not getting installed while running npm install for fetch-mock. Is it supposed to be added in dependencies instead of devDependencies?
