### ISSUE TITLE
fetchMock.done does not take methods into account

### ISSUE THREAD

**Issue by dorian-marchal** [wheresrhys/fetch-mock#262]
When I set up a mock waiting for a POST request, I expect `fetchMock.done()` to return `false` if the route has been called with a different method.

For example:

```js
fetchMock.postOnce('http://example.com/foo/bar/update', { foo: 'bar' });

fetch('http://example.com/foo/bar/update')
  .then(() => {
    fetchMock.done(); // true, but I expect false.
  });
```

Note that I can't rely on `fetchMock` throwing a `No fallback response defined for GET...` because my fetch call is wrapped in a `try/catch` block.

Is this by design? If so, is there a workaround?

**Comment by dorian-marchal** [comment]
I worked around it using a custom matcher:
```js
const match = (requestMethod, requestUrl) => (url, { method }) =>
  requestMethod === method && requestUrl === url;
```
And rewriting my above mock:
```js
fetchMock.once(match('POST', 'http://example.com/foo/bar/update'), { foo: 'bar' });
```

The default matching behavior seems a little counter intuitive.
Coming from [`nock`](https://github.com/node-nock/nock), I expected `done` to return false in this case (like `nock.isDone()`).

**Comment by wheresrhys** [comment]
Thanks for raising this. Most of the inspection methods of the library accept a second `method` argument to scope to a given method. I can't think of a reason why `done()` shouldn't do the same, though there are perhaps some intricacies to consider that don't apply to the simpler inspection methods.

Another, probably more elegant, workaround would be to name your route, as follows

```js
fetchMock.postOnce('http://example.com/foo/bar/update', { foo: 'bar' }, {name: 'post update'});

fetch('http://example.com/foo/bar/update')
  .then(() => {
    fetchMock.done('post update'); // false.
  });
```

**Comment by wheresrhys** [comment]
fixed
