### ISSUE TITLE
Node 6 support

### ISSUE THREAD

**Issue by Malgalad** [wheresrhys/fetch-mock#266]
The problem:

- On Node 6.10 requiring fetch-mock results in a following error:
```
FetchMock.generateResponse = async function (response, url, opts) {
                                   ^^^^^^^^
SyntaxError: Unexpected token function
```

- Switching to `require('fetch-mock/es5/server')` results in:
```
Error: Cannot find module 'babel-runtime/core-js/promise'
```

because I don't use babel-runtime.

As far as I can see, it can be fixed by a) adding babel-runtime as an explicit dependency to fetch-mock, or b) removing transform-runtime because _transpiling_ into es5 does not mean _providing polyfills_.

How to reproduce:
* Install Node v6.x
* Create an empty repo (`mkdir test && cd test && npm init -y`)
* Install fetch-mock and node-fetch.
* Create a file that requires fetch-mock (`echo "require('fetch-mock/es5/server');" > test.js`)
* Run created file with node.

**Comment by wheresrhys** [comment]
Could you try v6.1.0-beta.1 and use `require('fetch-mock/es5/server')`. If it works I'll merge the change and release as a minor version update

**Comment by Malgalad** [comment]
Tried installing it, version in package.json is `v6.0.0-beta.7` which is really confusing, and there're no `dist` or `es5` folders in bundle.

![Contents of archive](https://user-images.githubusercontent.com/1475852/36794651-9535ce52-1ca9-11e8-97bf-c76e80ce4712.png)

**Comment by wheresrhys** [comment]
Oh crap - I've obviously messed something up in my CI config. I'm on holiday but will have a go at fixing when I'm back next week.

Thanks for testing it out

**Comment by wheresrhys** [comment]
Can you try v6.1.0-beta.2 please. Finally managed to get a new release out

**Comment by wheresrhys** [comment]
This is now fixed in the latest release. You will also need to install babel-polyfill (I decided not to add it as an explicit dependency as it increases the dependency footprint of fetch-mock from 3 to 10's, and isn't needed in modern environments)

**Comment by nebulousdog** [comment]
I too am getting this, but on a newer 6.x version of Node

```
node -v
v6.10.3
```

```
/home/[...]/node_modules/fetch-mock/src/lib/fetch-handler.js:57
FetchMock.generateResponse = async function (response, url, opts) {
                                   ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/[...]/node_modules/fetch-mock/src/lib/index.js:2:22)
error Command failed with exit code 1.
```

**Comment by wheresrhys** [comment]
which version of fetch-mock?

**Comment by nebulousdog** [comment]
```
fetch-mock@^6.4.2:
  version "6.4.2"
  resolved "https://registry.yarnpkg.com/fetch-mock/-/fetch-mock-6.4.2.tgz#cb0ff7dc3baf5d3bc8628f73fca73bf862fbaa43"
  dependencies:
    babel-polyfill "^6.26.0"
    glob-to-regexp "^0.4.0"
    path-to-regexp "^2.2.1"
```

**Comment by wheresrhys** [comment]
@nebulousdog Could you please provide a test repo I can clone & install to reproduce the problem

**Comment by wheresrhys** [comment]
Actually, just re-read you're comment. Are you requiring the right file? See the installation guide here: http://www.wheresrhys.co.uk/fetch-mock/installation

**Comment by nebulousdog** [comment]
@wheresrhys yeah, I'm just using yarn instead of node. There was more info to give from the yarn lock file :). This works fine in Node 9.x for example, and upgrading was my solution to fix the issue.
