### ISSUE TITLE
response.json() throws different Error than one thrown in browser

### ISSUE THREAD

**Issue by jwhitex** [wheresrhys/fetch-mock#270]
**To Reproduce:**

```
        fetchMock.mock("*", {
            body: "<html></html>",
            status: 200,
            statusText: "Ok",
            headers: {},
            __redirectUrl: "http://localhost/login",
        }, { method: "GET" })
        await fetch("http://localhost/", { method: "GET" })
            .then((resp) => resp.json().catch((err) => {
            if (err instanceof SyntaxError) {
                console.log("Matches fetch behavior")
            } else {
                console.log("Does not match fetch behavior")
            }
        })
```
**Current Behavior**

```
    Expected value to be an instance of:
      "SyntaxError"
    Received:
      [FetchError: invalid json response body at http://localhost:8080/login reason: Unexpected token < in JSON at position 0]
    Constructor:
      "FetchError"
```

**Expected Behavior:**

I cannot find an actual link between these two documents but from testing on chrome parsing invalid json always throws a SyntaxError. The mocks should behave the same way.
- [MDN: SyntaxError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/JSON_bad_parse) 
- [MDN: Body.json()](https://developer.mozilla.org/en-US/docs/Web/API/Body/json) 

What are your thoughts?

**Comment by wheresrhys** [comment]
I've looked into this and it's a deliberate variation from the fetch spec done in node-fetch https://github.com/bitinn/node-fetch/blob/master/ERROR-HANDLING.md, so closing this as a won't fix

**Comment by t3chguy** [comment]
New link for the above md file is https://github.com/node-fetch/node-fetch/blob/main/docs/ERROR-HANDLING.md#error-handling-with-node-fetch
