### ISSUE TITLE
Add string prefix to matcher arg to scope match to just the path portion of the URL

### ISSUE THREAD

**Issue by webbower** [wheresrhys/fetch-mock#271]
IMO it seems like people are more often just going to match against just the URL path and not the full URL from protocol to URL fragment and so having a prefix like `path:` for the string version of the `matcher` arg for `.mock()`, `.get()`, et al would be a nice convenience to scope the match to just the URL path. It could still be treated as a full match or use the glob `*` character to match a dynamic last segment.

Without this, you need to use a RegExp to match just the path which means you either need to write out a full constructor for it or escape all the forward slashes for the regex literal.

**Comment by wheresrhys** [comment]
You can use `end:`, which, granted, will also need to match any query string. The `express:` prefix also supports the full express path syntax, of which just using a path, with no params in it, is a subset.

So it is technically supported, though perhaps not obviously. I've been thinking for ages about putting together an examples and recipes section of the docs, but not had the time

**Comment by webbower** [comment]
Ok cool. Probably better to have an explicit one for this (probably) common use case. I'll try to tackle it in the next few weeks.

**Comment by webbower** [comment]
For the PR, it looks like all I need to do is:

* Add a new entry (probably keyed as `path`) to the `stringMatchers` object and import any necessary libraries for extracting the path (I'll try to find the most lightweight dependency possible since all that's needed is to break apart a URL and extract the path portion)
* Add whatever unit tests for browser and Node environments
* Update the docs

Does that sound about right?

**Comment by wheresrhys** [comment]
yep totally correct, other than that you shouldn't need any dependencies as both node and browsers have URL parsers built in: https://nodejs.org/api/url.html, https://developer.mozilla.org/en-US/docs/Web/API/URL (older browsers don't, but I'm working on tweaking the babel settings to polyfill any missing apis, so you can assume that it's available)

**Comment by webbower** [comment]
w00t! That makes life much easier.
