### ISSUE TITLE
[documentation] v5 - v6 upgrade guide doesn't discuss changes to the calls() return value

### ISSUE THREAD

**Issue by medington** [wheresrhys/fetch-mock#283]
In version 5, the `calls()` inspector used to return an object with:

[v5 calls() code](https://github.com/wheresrhys/fetch-mock/blob/b8270640d5711feffb01d1bf85bb7da95179c4de/src/fetch-mock.js#L288):

```
{
    matched: this._matchedCalls,
    unmatched: this._unmatchedCalls
};
```

in version 6 this has changed to only return an array of matched calls. This change is not called out in the [v5 - v6 Upgrade Guide](http://www.wheresrhys.co.uk/fetch-mock/v5-v6-upgrade).

I would be happy to submit a PR for updating the docs if you would like (assuming I'm not missing something obvious here).

**Comment by wheresrhys** [comment]
yep, good call. PR most welcome
