### ISSUE TITLE
RUM docs

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#284]
- Go through all the issues to find out what things users are stumbling on
- Create a 'recipes' page, and update the troubleshooting page
- Better styling for the API docs

**Comment by wheresrhys** [comment]
Better use this too https://github.com/jenniferlynparsons/awesome-writing

**Comment by nebulousdog** [comment]
examples would be amazing. I want to know how to fully utilize this! very useful so far.
