### ISSUE TITLE
.calls() Returns an object {matched: [], unmatched: []}

### ISSUE THREAD

**Issue by theKashey** [wheresrhys/fetch-mock#293]
__calls(filter, method)__
`Returns an object {matched: [], unmatched: []} containing arrays of all calls to fetch, grouped by whether fetch-mock matched them or not. If filter is specified then only calls to fetch matching that route are returned.`

In fact this is documentation for v5.
v6 returns just array of all calls :(

**Comment by wheresrhys** [comment]
fixed
