### ISSUE TITLE
Mocking no response - causes fetch to throw an exception instead of triggering the Promise's catch

### ISSUE THREAD

**Issue by JakeSummers** [wheresrhys/fetch-mock#295]
In issue #168, it is recommended to test a server not available using: `fetchMock.mock('www.google.com', {throws: 'Server not found'})`.  This functionality is causing my fetch call to throw an Error instead of resolving the Promise to an Error.  

----

When I do the following (no mocking):

```
try{
    fetch('http://thisSiteDoesntExist.com/foo')
        .then( res => console.log('It worked'))
        .catch( err => console.log('Promise error'));
}catch(e){
    console.log('Fetch threw!');
}
```

Then this will print: 

```
Promise error
```

If I mock, using `fetchMock.mock(`glob:*`, {throws: 'Server not found'});`) this causes the fetch function to throw, not the promise.  This will print: 

```
Fetch threw!
```

---

I did some digging and this behavior seems to be enforced with a unit tests ([responses.test.js](https://github.com/wheresrhys/fetch-mock/blob/519f648eecbc011a6906983c560fc7681753370f/test/specs/responses.test.js#L234)):

```
			it('response that throws', async () => {
				fm.mock('http://it.at.there/', {
					throws: 'Oh no'
				});

				try {
					fm.fetchHandler('http://it.at.there/')
					expect(true).to.be.false
				} catch (err) {
					expect(err).to.equal('Oh no');
				}
			});
```

This seems odd to me.  Any input would be appreciated.

**Comment by wheresrhys** [comment]
Hmmm, the more I investigate this, the more I think it's a mistake in my implementation.

I may consider a version 7 release to correct this and roll out one or two refinements to the codebase that, aside for _maybe_ some really edge cases, probably aren't breaking changes, but I'd rather not risk them in a patch/minor.

I have a busy few weeks so it won't be addressed quickly though

**Comment by JakeSummers** [comment]
Thanks for the reply and consideration!  Mostly raised the issue because I found this behaviour to be surprising.

**Comment by dwighthouse** [comment]
I thought I was going crazy. Yes, this is affecting my code as well. It's one of the few places I can't get code coverage in my tests currently.

**Comment by leogiertz** [comment]
We ran into this as well when upgrading from v5 to v6. Would be great with a v7 release.

@wheresrhys Thanks a lot for the effort you've put into fetch-mock! 🎈

**Comment by wheresrhys** [comment]
@leogiertz @dwighthouse @JakeSummers This should be fixed in the v7 branch. Please give it a try if possible

**Comment by leogiertz** [comment]
@wheresrhys The v7 branch works for us. Thanks! ⭐️

**Comment by wheresrhys** [comment]
Just released an alpha so you can have some stability v7.0.0-alpha.1
