### ISSUE TITLE
Router not matching the url if Request object is passed

### ISSUE THREAD

**Issue by LKay** [wheresrhys/fetch-mock#297]
Related to #258.

Seems that when `fetch` receives first argument as `Request` instance the router doesn't extract the url from it and router can't match the url:

This works:
```javascript
const response = await fetch(
      "/some-url",
      { foo: "bar" }
);
```
and this doesn't:
```javascript
const request = new Request(
    "/some-url",
    { foo: "bar" }
);
const response = await fetch(request);
```

Setting mock:
```
fetchMock.getOnce(
    "/some-url",
    { status  : 200 }
);
```

and call to it returns an error:
```
Unmatched GET to [object Object]
Error: No fallback response defined for GET to [object Object]
...<stack trace here>
```

**Comment by wheresrhys** [comment]
Which version are you on? This should be fixed now. 

Are you sure the `Request` constructor you're using is the same as the one used internally by `fetch-mock` - they can end up being different depending on what tooling you use. See the docs on config to fix this

**Comment by LKay** [comment]
I'm on a version `6.3.0` right now (seems to be latest). I'm using global fetch, which is polyfilled by `whatwg-fetch` (I have `isomorphic-fetch` imported) in node environment. The `Request` seems to be the same instance. According to section in the docs that should work without assigning `fetchMock.config` properties.

**Comment by LKay** [comment]
The problems seems to be with `matcher` property when custom matcher function is passed (`Function(url, opts)`). In that case url is passed as an object (`Request` instance instead of string).

**Comment by wheresrhys** [comment]
Ah cool. That’s very useful info. Will try to patch this weekend

**Comment by LKay** [comment]
Great! I also noticed similar behavior in other place. When `Request` is passed to `fetch` then the mock method `lastCall` object returns `Array<Array<Request, undefined>>` instead of `Array<Array<string, Request>>`. Looks like the tuple representing call does not extract url as well.

**Comment by wheresrhys** [comment]
Closing in favour of the proposal issue
