### ISSUE TITLE
Is it possible to throw on the text() method?

### ISSUE THREAD

**Issue by dwighthouse** [wheresrhys/fetch-mock#298]
I have been trying to find a way to mock a failure to the response.text() function. I can't find any way to cause text() to fail that doesn't also mean a complete network failure (and therefore, there would be no body in the first place). I read through the [fetch spec](https://fetch.spec.whatwg.org/) and wasn't able to find a clear way in which this could happen, unlike the response.json() function, which can throw on badly constructed JSON easily. Also, [MDN's article](https://developer.mozilla.org/en-US/docs/Web/API/Body/text) doesn't mention anything about it.

### Example

Assuming that `/my-api-endpoint/` actually works and gives a response, would the catch statement below ever be called?

```
const options = {
    method: 'GET',
    credentials: 'same-origin',
    headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
    }
};

fetch('/my-api-endpoint/', options)
    .then((response) => {
        return response.text();
    })
    .catch((e) => {
        console.log('text() threw');
        console.log(e);
    }).then((text) => {
        console.log(text);
    });
```

If it is possible, how would we mock such a situation?

### Attempts

I have tried to send in a Response with a null body, but even that returns an empty string from text().

```
const localFetch = require('node-fetch');
const response = new localFetch.Response(null, {
    status: 500,
    statusText: 'No Body',
});
fetchMock.get('*', response);

// Actual call to fetch
```

Sending in a null or undefined body via your constructor object also just returns an empty string from text():

```
fetchMock.get('*', {
    status: 200,
    body: null,
});
```

**Comment by wheresrhys** [comment]
`.text()`, `.json()`, etc. just use the native/node-fetch implementations (which are methods of `Response`). So if you can find a way to build a `Response` that contains a stream which errors when you try to convert it to text, then there's nothing in `fetch-mock` that will stop you doing so.

Possibly you're trying to test a scenario which can't actually occur in the real world (given how `Response`s are specced). I'd ask on some forum related to the `fetch` spec what - if any - are the scenarios where `text()` can throw

Closing as out of scope

**Comment by dwighthouse** [comment]
For anyone looking for the answer, it appears it is always impossible for text() to throw.

https://stackoverflow.com/a/49786130/195068
