### ISSUE TITLE
An easy way to access path parameters

### ISSUE THREAD

**Issue by vermilion1** [wheresrhys/fetch-mock#300]
To access url's path params we have to parse it with a regular expression or split it by `/`. Would be nice to have it working out of the box e.g.:
Express url: `/example/:foo/:bar`
Request: `fetch('/example/foovalue/barvalue')`
Fetch-mock object: `{ ... path: { foo: 'foovalue', bar: 'barvalue' }}
`

**Comment by vermilion1** [comment]
@wheresrhys if you want to make minor changes to the API - yeah, getters for params are 👍.
About other ideas - there is a proposal https://github.com/wheresrhys/fetch-mock/issues/301 created in the same day as this issue.
Basically an example at the end of the proposal is a part of the library built on top of yours.
I was even thinking about making it public one day.

**Comment by wheresrhys** [comment]
done

**Comment by danpantry** [comment]
Hey @wheresrhys, you marked this as done but I can't seem to find in the docs where this is handled. Could you point me in the right direction?

**Comment by wheresrhys** [comment]
In this section http://www.wheresrhys.co.uk/fetch-mock/#api-mockingmock_options

**Comment by a-x-** [comment]
But it is not about access. It's just matcher as requested here: https://github.com/wheresrhys/fetch-mock/issues/215

**Comment by a-x-** [comment]
Is any way to access actual url params and query object like express `req` allows?

**Comment by wheresrhys** [comment]
Hello @a-x- - Sorry can you give more details. Please open a new issue with exactly what information you want access to and where in the testing lifecycle (setting up mocks, inspecting their use...) you want it.

**Comment by a-x-** [comment]
This issue was about getting values of path params, not about matchers, as I understand

Example given in the description of issue:
We need to give objects like this: `{ foo: 'foovalue', bar: 'barvalue' }`

**Comment by a-x-** [comment]
hm, possibly, I was inattentive.
Looks, like `.ok(({ path }) => `deleted board with id ${path.id}`);` is all we need
