### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by vermilion1** [wheresrhys/fetch-mock#301]
Hi there,

First of all thanks for the awesome fetch-mock library! It is for sure the best mocking library available in open source at the moment.

There are features I miss in this library e.g.:
- Ability to easily access path/query/body params in the callback function. Currently path and query params have to be parsed manually from the url
- Ability to easily delay the response
- Ability to easily mock the response only when exact conditions are met e.g.
  - path param named “project” equals “1” 
  - query param named “expand” equals “issues” 
  - there are no other query params
- Ability to restore a single mock keeping others running

All those features I already implemented by writing the wrapper for fetch-mock (it is not an open-source solution, it is just a util which solves the problem of my project).

The question to you is whether you are open to feature requests or you just accept the PRs?
Another question is whether you are ready to change the interface of the fetch-mock library to make it more declarative?

To help you understanding what I want I’ll show you how my wrapper is used:

```javascript
import { get, put, del, restoreAll } from './fetch-mock';

get('/example/:foo/:bar')
    .matchPathParams({ foo: '123' })
    .ok();

// ---------------

put('/example/:foo')
    .matchPathParams({ foo: '123' })
    .matchBodyParams({ bar: 456 })
    .matchExactQueryParams({ kek: '789' })
    .internalServerError({ error: 'noo!' });

// ---------------

const delay = 1000;
const boards = [
    { id: '1', name: 'hey' },
    { id: '2', name: 'ho' },
    { id: '3', name: 'hello' }
];

const doesBoardExist = id => !!boards.find(board => board.id === id);

del('/api/board/:id')
    .matchParams(({ path }) => doesBoardExist(path.id))
    .ok(({ path }) => `deleted board with id ${path.id}`);

del('/api/board/:id')
    .matchParams(({ path }) => !doesBoardExist(path.id))
    .notFound(({ path }) => `board with id ${path.id} not found`);

// ---------------

get('/api/boards').ok(boards, delay);
```

Thanks,
Vitalii

**Comment by wheresrhys** [comment]
I'm gonna close this. While I like the idea, it'd be too much of an upheaval for both the codebase and users who are used to the existing API
