### ISSUE TITLE
leverage 'browser' key in package.json

### ISSUE THREAD

**Issue by Flet** [wheresrhys/fetch-mock#31]
Hello!

Thanks for putting together this handy package!

One thing I'd like to be able to do is run tests in node as well as in the browser without having separate import/require statements (`require('fetch-mock')` vs `require('fetch-mock/src/server')`).

Have you considered leveraging the `browser` key in `package.json`? 

Something like this should do it:
```js
"main": "src/server.js",
"browser": "es5/client.js"
```

This should allow `require('fetch-mock')` to work for both browser and server (well, at least node v4 :smile:)

Have you explored this at all?

**Comment by wheresrhys** [comment]
Good idea. I'll try this out soon.
