### ISSUE TITLE
support for readable streams

### ISSUE THREAD

**Issue by qjflores** [wheresrhys/fetch-mock#314]
test.js
```
const fetchMock = require('fetch-mock')
const copyFile = require('./file.js')
const path = require('path')
const fs = require('fs')
const readableStream = fs.createReadStream(path.join(__dirname, 'testfile.txt'))
const fetch = fetchMock.sandbox().mock('/attachments',
    {
      status: 200,
      body: readableStream,
      headers: {'Content-Type': 'application/json'}
    })
```

file.js
```
const fs = require('fs')
const ws = fs.createWriteStream(null)
async copyFile (url) {
  let response = await fetch(url)
  const stream = response.body..pipe(ws)
}
```

When I try to run the test I get the error
```
TypeError: response.body.pipe is not a function
```
typeof show response.body being a string

**Comment by wheresrhys** [comment]
Thanks for the detailed issue. I'm not gonna have time to look at this for a while most likely, so pull requests welcome

**Comment by wheresrhys** [comment]
I've added a test for this now, which passes in v7 https://github.com/wheresrhys/fetch-mock/pull/367/files

Are you still having this problem? Which environment are the tests running in?

**Comment by wheresrhys** [comment]
gonna close for now - please reopen if it's still an issue

**Comment by rolandjitsu** [comment]
@wheresrhys can this be extended to `ReadableStream`?

**Comment by mayakoneval** [comment]
++ ^
