### ISSUE TITLE
Suggestion: stringify instances of URL before attempting a match

### ISSUE THREAD

**Issue by evoyy** [wheresrhys/fetch-mock#315]
Firstly, thanks for creating and maintaining this project.

In my app, I build an URL and pass it to fetch():

````javascript
let url = new URL(/*...*/);
fetch(url).then(/*...*/); 
````

This is how they do it in the MDN docs:
https://developer.mozilla.org/en-US/docs/Web/API/URL

But in my tests, this failed to match:

````javascript
fetchMock.get('http://example.com?foo=bar')

Error: No fallback response defined for GET to http://example.com?foo=bar
````

This puzzled me for quite a while before I realized I need to explicitly stringify the URL for compatibility with fetch-mock:

````javascript
fetch(url.toString()).then(/*...*/);
````

I think that passing an URL to fetch will be a common paradigm, so this may help other people.

**Comment by wheresrhys** [comment]
This is actually what I'm proposing in #311  - I've been hoping for some steer from people using the library before making the breaking change.

Gonna close this issue and consider it a :+1: for #311
