### ISSUE TITLE
Removing the requirement to specify config.Request

### ISSUE THREAD

**Issue by adam-nielsen** [wheresrhys/fetch-mock#326]
This is a suggestion that may make the code a little easier to work with.  Feel free to disregard if it's not the direction in which you want to go.

I had some trouble trying to get fetch-mock working in my environment (ReactJS tests run via Node) because the `Request` objects being passed to `fetch()` weren't being recognised as such by fetch-mock.  I saw that I could supply a `Request` class to fetch-mock's `config.Request` parameter, but it took me a while to work out what this was (because I was using `node-fetch` before I realised that the tests were running with `whatwg-fetch` instead.  Since these two had different implementations of the `Request` object, fetch-mock was seeing a `whatwg-fetch.Request` object, which wasn't an instance of `node-fetch.Request`, so it was treated as a string and then failing because there was no `substr` method.)

It does work now I have correctly set `config.Request`, but I wonder whether this could be simplified.  Using `compile-route.js` for example, the requirement to know the object type could be eliminated by looking inside the object instead:
```
function normalizeRequest (url, options, Request) {
//	if (Request.prototype.isPrototypeOf(url)) {
	if (url.url && url.headers) {
```
By doing this, it doesn't matter which provider of the `Request` object we have, as they all need to provide the fields from the spec.  So by looking at the fields we need, we no longer care what the object's instance type actually is.

I have tried this change and it allows the code to run correctly, regardless of what you pass as `config.Request`.

I am not sure whether this could be extended to the other items in `config`, but if it can, it might make the library easier to use as you would no longer have to tell it which fetch implementation you're using.

**Comment by adam-nielsen** [comment]
A descriptive error message would definitely be helpful.  Especially one that uses `typeof` or similar to show what type of object was passed vs the one that was expected, to make it abundantly clear if you're using two completely different `Request` objects as I was!

**Comment by wheresrhys** [comment]
Error messages improved here https://github.com/wheresrhys/fetch-mock/pull/340
