### ISSUE TITLE
Flush a specific quantity of Promise

### ISSUE THREAD

**Issue by lourenci** [wheresrhys/fetch-mock#335]
It'll be useful if I could flush a certain quantity of Promise. Is this on roadmap of the lib?

There is some scenarios that I have a `Promisse.all` statement.

I came from AngularJS, the httpBackend allows this by passing the number of flushs to be resolved in `flush` parameter.

Thanks.

**Comment by wheresrhys** [comment]
`.flush()` is generally only intended to be used when your API does not return the fetch call (i.e. it's called in a fire and forget way). It's not designed for controlling fetch resolution order. `fetch-mock`, in theory at least, allows any level of control over response order by using function/promise responses. e.g.

``` js
fetchMock
  .mock(url1, new Promise(res => setTimeout(() => res(200), 50) // resolve with ok in 50ms
  .mock(url2, () => someOtherPromise.then(() => 500)) // resolve with 500 after some other promise has resolved
```

See the response section of the docs http://www.wheresrhys.co.uk/fetch-mock/api
