### ISSUE TITLE
Is `fetch-mock` compatible with `axios`

### ISSUE THREAD

**Issue by redguardtoo** [wheresrhys/fetch-mock#341]
Thank you for developing this nice package.

My only concern is we might migrate from `fetch` to `axios` (https://github.com/axios/axios) in the future. Is `fetch-mock` still usable when we use `axios`.

**Comment by wheresrhys** [comment]
Unfortunately not. Axios uses XHR under the hood in the browser, and the native http module in node, so doesn't interact with fetch at all.

**Comment by redguardtoo** [comment]
Thanks for the heads up.
