### ISSUE TITLE
Adopt sinon's method names

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#351]
https://sinonjs.org/releases/v6.1.5/stubs/

- `stub.reset()`: Resets both behaviour and history of the stub.
- `stub.resetBehavior();`
- `stub.resetHistory();`

Will probably keep `restore()` as an alias for `reset()` as it's probably quite widely reused and  woudl be  a pain for everyone to update.

**Comment by wheresrhys** [comment]
done

**Comment by nebulousdog** [comment]
if a deprecation message were added, it'd give us all time to choose the new universal method. :+1:
