### ISSUE TITLE
Support URL objects in matchers

### ISSUE THREAD

**Issue by carpeliam** [wheresrhys/fetch-mock#355]
Currently, matchers (as documented) are required to either be a string, a regex, or a function. When a `URL` object is passed to `fetch` and a string matcher is used with fetchMock, then fetchMock uses a `matchUrl` function of object equality; this fails, even though the URL object and the string can be equal to each other via `==`. If fetchMock is given a `URL` matcher, then the `matchUrl` function is not defined, which causes fetchMock to throw a `TypeError: matchUrl is not a function` error.

It would be helpful if either fetchMock were to directly support `URL` objects as a matcher, or to check for loose equivalence (`==`) for strings.

Examples:

```js
// when supplying URLs to fetchMock:
const fetchMockUrl = new URL(`https://google.com/search`);
fetchMockUrl.searchParams.append('q', 'fetch mock');

// test
fetchMock.get(fetchMockUrl, { status: 200, body: { fetchMock: 'Awesome' } });

// code
fetch(fetchMockUrl); // this will result in `TypeError: matchUrl is not a function` because fetchMock matchers do not support URL objects
```

```js
// when matching URLs as strings:
const fetchMockUrl = new URL(`https://google.com/search`);
fetchMockUrl.searchParams.append('q', 'fetch mock');

// test
fetchMock.get('https://google.com/search?q=fetch%20mock', { status: 200, body: { fetchMock: 'Awesome' } });

// code
fetch(fetchMockUrl); // this will result in `Unmatched GET to https://google.com/search?q=fetch%20mock` because the URL and the string are not exactly the same
```

**Comment by wheresrhys** [comment]
Thanks for reporting this. You'll be glad to hear it's fixed in v7. Please try the alpha release. The proper v7 release should be out reasonably soon - just a handful of things left to tweak and document

**Comment by redaxmedia** [comment]
Can someone confirm that `indexOf` error occurs using node-fetch 7.3.9: 

```
TypeError: matcher.indexOf is not a function
```
