### ISSUE TITLE
Response status 204

### ISSUE THREAD

**Issue by KateKate** [wheresrhys/fetch-mock#36]
Thank you for your lib! I tried to mock 204 status, but got the error:
```
Uncaught (in promise) TypeError: Failed to construct 'Response': Response with null body status cannot have body
    at TypeError (native)
    at mockResponse ...
```
with that line `return _Promise.resolve(new Response(body, opts));`
I suppose it couldn't mock 204 status as far as it hasn't response body.
I have the following routes:
```
fetchMock.mock({
    routes: [{
      name: 'route3',
      method: 'DELETE',
      matcher: 'path/to/my/api',
      response: 204,
    }]
});
```
Should I change the response config? Thanks in advance!

**Comment by wheresrhys** [comment]
good question. Probably needs a unit test adding for just this case

**Comment by wheresrhys** [comment]
Looks like this is a bug in Chrome https://code.google.com/p/chromium/issues/detail?id=524500&q=label%3ACr-Blink-FetchAPI%2CCr-Blink-XHR%2CCr-Blink-WebSockets%2CCr-Blink-StreamsAPI%20status%3Aunconfirmed%2Cuntriaged%20opened-before%3A2015%2F10%2F1&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified%20Opened

**Comment by hansottowirtz** [comment]
I have the same problem in Safari: `TypeError: Response cannot have a body with the given status.`
Body is `"null"`, response status is `204`.
