### ISSUE TITLE
Update from v6 => v7 breaks chaining

### ISSUE THREAD

**Issue by robseriousgit** [wheresrhys/fetch-mock#369]
Hi Rhys, from across the river!  _waves_

Currently using `v6.5.2` and trying to update to `v7.0.2`

Have some code that is giving an error: 

```
 fetch-mock: Adding route with same name or matcher as existing route. See `overwriteRoutes` option.

      348 |           status: 200
      349 |         })
    > 350 |         .get(`/xyz/abc?id=486727`, {
          |          ^
      351 |           body: [thingStub],
      352 |           status: 200
      353 |         })
```
The code that's setting this up looks like:

```
fetchMock
        .get(`/xyz/abc?id=486726&id=486727`, {
          body: multiThingStub,
          status: 200
        })
        .get(`/xyz/abc?id=486727`, {
          body: [thingStub],
          status: 200
        })
```
I don't want to use the `overwriteRoutes` as they're different, and should return different results.

Is this a new 'feature' or perhaps a byproduct of the note in the upgrade to v7 guide 'Able to match requests based on the path of the url'?

Cheers

Rob C

**Comment by wheresrhys** [comment]
Definitely a regression - thanks for reporting. I'll see if I can reproduce and fix this afternoon

**Comment by wheresrhys** [comment]
fixed in 7.0.3

(PS hello :wave: - didn't recognise you with all that hair)

**Comment by robseriousgit** [comment]
Cheers Rhys!  I'll try that out now.  A+++ for turnaround :)

**Comment by robseriousgit** [comment]
@wheresrhys Mind pushing to npm?  Thanks mate

**Comment by wheresrhys** [comment]
had a build problem - should be released in the next few minutes
