### ISSUE TITLE
node-fetch in peerDependencies but we don't use it

### ISSUE THREAD

**Issue by edmorley** [wheresrhys/fetch-mock#377]
Hi!

After updating to fetch-mock from v6 to v7, we now get a missing peer dependency warning when installing:

```
warning " > fetch-mock@7.0.6" has unmet peer dependency "node-fetch@*".
```

However we only use fetch-mock to mock native browser usage, so have no need to install the node-fetch package other than to silence the warning.

Would it be possible to:
* consider removing the peer dep, to prevent the warning for the browser mocking use-case
* or if that's not desired, then add a mention about it in the upgrading guide? (technically adding a peer dep is a breaking change, since it can make certain package managers exit non-zero when they didn't before)

Many thanks :-)

**Comment by wheresrhys** [comment]
Please add a note to the upgrade guide if you feel it's important. I don't have time to work on this project for a few weeks

**Comment by edmorley** [comment]
Would you be open to removing the peer dep instead (I'm happy to open a PR for it)?
