### ISSUE TITLE
In Chrome realFetch throws Illegal invocation error.

### ISSUE THREAD

**Issue by mvandiest** [wheresrhys/fetch-mock#38]
I am actually unable to get anything to work as Chrome throws Illegal Invocation error. At the following line: https://github.com/wheresrhys/fetch-mock/blob/f0e113203ce362e1bc3e83f08fb8fbbfe2ddcab0/src/fetch-mock.js#L329

I'm assuming it's a binding context issue similar to this: https://github.com/typicode/fetchival/issues/1

Or quite possibly I'm not using the library correctly.

I'm just using a basic example and I get the error: 

```
import fetchMock from 'fetch-mock'
fetchMock.mock('http://www.example.com', 200);
```

**Comment by mvandiest** [comment]
I think it might be as simple as adding the following to https://github.com/wheresrhys/fetch-mock/blob/f0e113203ce362e1bc3e83f08fb8fbbfe2ddcab0/src/fetch-mock.js#L123:

`this.realFetch = theGlobal.fetch.bind(theGlobal);`

**Comment by wheresrhys** [comment]
which version of fetch-mock are you using?

**Comment by wheresrhys** [comment]
Fixed - thanks for highlighting the problem

**Comment by mvandiest** [comment]
Awesome! Thanks for addressing so quickly.
