### ISSUE TITLE
inconsistent url when calling fetch mock with proxy setting

### ISSUE THREAD

**Issue by jterryhao** [wheresrhys/fetch-mock#388]
Hi there, I was using fetch-mock 7.2.2, typescript 3.1.3 and I have the following code
```
fetchMock.config = Object.assign(fetchMock.config, {
        Request: Request,
        Response: Response,
        fetch: fetch //fetch in typescript library
    });

fetchMock.get("/default", data.list_data);

fetchMock.get("/default/provinces", data.get_data);
fetchMock.get("/default/NBA", 404);

fetchMock.delete("https://mydictionary/default/provinces", 200);
fetchMock.delete("https://mydictionary/default/NBA", 404);

...// some other code here

it("", () => {
    await foo(); // foo calls fetch
});

```
I have a proxy set in package.json:
`proxy: "https://mydictionary"`
The issue I'm having right now is the following:

- When doing a GET, it sends the request to "/default/..."
- When doing a DELETE, it sends the request to "https://mydictionary/default/..."

Is this the expected behavior? I can provide more detail if needed.

**Comment by wheresrhys** [comment]
fetch-mock doesn't send any request - it's your application that does that. It sounds to me that it's probably an issue in your code somewhere, but if you can provide a repo I can clone that reproduces the issue I'm happy to take a look

**Comment by jterryhao** [comment]
I think I figured this out. It was a dumb mistake I made. In foo(), I was fetching from "https://mydictionary/default/..." instead of just "/default/...", causing the issue above. Please close this issue, thank you very much.
