### ISSUE TITLE
your donation link is disabled on JustGiving

### ISSUE THREAD

**Issue by jgravois** [wheresrhys/fetch-mock#389]
has the campaign ended?
https://www.justgiving.com/fundraising/rhys-evans-walk

![screenshot 2018-10-31 10 19 18](https://user-images.githubusercontent.com/3011734/47806225-718e0b00-dcf6-11e8-9a52-1952ab4f8891.png)

**Comment by wheresrhys** [comment]
Does that mean you want to donate :pray: . It expired a few days ago. I may update with a direct link to the charity

**Comment by jgravois** [comment]
> Does that mean you want to donate?
> I may update with a direct link to the charity

done and done.

![screenshot 2018-11-02 11 47 54](https://user-images.githubusercontent.com/3011734/47934700-45f55700-de95-11e8-96eb-2b935e3530ea.png)
