### ISSUE TITLE
Is there a way to specify`fetchmock.config.errorOnFallback`? I would like the tests to fail if an unexpected http request is made.

### ISSUE THREAD

**Issue by josh08h** [wheresrhys/fetch-mock#399]
I would like my tests to fail if an unmatched HTTP request is made. It doesn't look like there is a way to specify this as a config option. Please advise.

**Comment by wheresrhys** [comment]
The default behaviour is to error on unmatched calls. More details here under `fallbackToNetwork` http://www.wheresrhys.co.uk/fetch-mock/#usageconfiguration. Can be set globally or as an option in any call to `.mock()`

**Comment by josh08h** [comment]
Great thanks.
