### ISSUE TITLE
Returns rejected promise promise when `config.greed = bad`

### ISSUE THREAD

**Issue by danny-andrews** [wheresrhys/fetch-mock#40]
This library rejects the promise when you set promise `config.greed = bad` ([ref](https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L29)), but the fetch specification states:
```
The Promise returned from fetch() won't reject on HTTP error status even if the response is a HTTP 404 or 500. Instead, it will resolve normally, and it will only reject on network failure, or if anything prevented the request from completing.
```
https://github.com/github/fetch#caveats
We should just resolve as normal here.

**Comment by wheresrhys** [comment]
To be honest, I'm not sure how useful being able to configure bad responses is. `greed: 'good'` is a feature I use from time to time, and it's also useful to be able to let unmatched requests pass through to native fetch. `greed: 'bad'` is only there for completeness really. I don't see it as running contrary to the fetch spec though: fetch 'will only reject on network failure, or if anything prevented the request from completing.' So `greed: bad` kinda equates to the worst case scenario fora fetch request.

I could add the ability to configure the behaviour more precisely e.g `greed: {status code}`, and will leave this issue open to see if anyone else wants the feature. Personally I think if the developer cares that much about status codes returned by the fetch calls in their test, then they should probably be mocking those calls individually or with some predefined routes.

**Comment by danny-andrews** [comment]
I decided against using fetch, I was having too much friction trying to mock it out in tests. You make a good point about the network failure, though.
