### ISSUE TITLE
node-fetch is a peer dependency

### ISSUE THREAD

**Issue by perrin4869** [wheresrhys/fetch-mock#433]
Trying to use `fetch-mock` in my unit tests, if I don't install `node-fetch` manually, I get an error

```
Cannot find module 'node-fetch' from 'server.js'

      at Resolver.resolveModule (node_modules/jest-runtime/node_modules/jest-resolve/build/index.js:230:17)
      at Object.<anonymous> (node_modules/fetch-mock/src/server.js:1:42)
```
 `node-fetch` is required here: https://github.com/wheresrhys/fetch-mock/blob/28744cde12fe8813716355319d8aa7cac2a5b9b2/src/server.js#L1
I noticed that `node-fetch` was dropped as a peerDependency in https://github.com/wheresrhys/fetch-mock/issues/377, but I do not understand why it was considered as unused.
Should it not be added back? I'll be happy to put in a quick PR

**Comment by fatso83** [comment]
I also find this strange. The module is required for this to work. Having it in `dependencies` brings no clear downsides that I can see:
- people who build for the browsers will not have the dependency bundled in anyhow
- people don't need to care about the peer dependency at all (to remove the annoying peer dependency warning you'd have to install it anyway)
- people who build for the servers would have needed to install it for things to work anyway

I think the right solution would be to just `npm i node-fetch` and be done with it. This is literally the first thing that hit me when [testing out the examples](http://www.wheresrhys.co.uk/fetch-mock/).

**Comment by wheresrhys** [comment]
The reason is [documented very clearly](http://www.wheresrhys.co.uk/fetch-mock/#usagerequirements) in the requirements section of the docs.

**Comment by cstoddart** [comment]
The reason is technically in the docs, but it is filled with jargon and not very clear
