### ISSUE TITLE
Typescript types please

### ISSUE THREAD

**Issue by nojvek** [wheresrhys/fetch-mock#434]
This is a great lib but hard to figure out the api. I would love to use a version I can type check against. 

It would be great to have typescript declaration types built into the repo via "types" in package.json.

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by wheresrhys** [comment]
Someone defined types for an earlier verson of the library over in https://www.npmjs.com/package/@types/fetch-mock. You are welcome to use/update them

fetch-mock, however, is not a typescript project, so this issue is out of scope here.

**Comment by nojvek** [comment]
It doesn’t need to be a typescript project. You could just have a simple types.d.ts file here and a simple update to package.json

This ensures the types are compatible with the version that is installed. 


So people don’t need to download two packages for the same thing.

**Comment by wheresrhys** [comment]
If you want to submit a PR to do that then I'll have a look and decide if it's too much of a maintenance overhead.

**Comment by wheresrhys** [comment]
@nojvek This is now done in v8.0.0-alpha.9. Would appreciate it if you could try it out
