### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#436]
I don't have the time to maintain this library any more.

I would welcome any responses to this issue with offers of help.

I'm particularly interested in hearing from people who already maintain established open source projects (with apologies to those who'd like to find a way to begin working on OSS; I don't have time to vet potential maintainers, and being an already established maintainer is a good shortcut to establishing that you're reliable, non-malicious etc)

**Comment by grug** [comment]
We're already scheduled for a catch-up, but figured I'd put it here :) I'd like to put my hand up to help out as a maintainer. I'm pretty familiar with the codebase and the usage of this library. I maintain a couple of OSS projects: https://www.npmjs.com/package/data-mocks and https://www.npmjs.com/package/optimizely-service mainly. I've also worked full-time for Moodle https://github.com/moodle/moodle so I have a fair amount of open source experience.
