### ISSUE TITLE
Support for fetch with Request object as parameter

### ISSUE THREAD

**Issue by DrUNE** [wheresrhys/fetch-mock#44]
Allow using mock to intercept [fetch](https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch/fetch) call with [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object as input. Currently only [USVString](https://developer.mozilla.org/en-US/docs/Web/API/USVString) type is supported.

**Comment by wheresrhys** [comment]
Will be fixed when https://github.com/wheresrhys/fetch-mock/pull/43 is merged

**Comment by wheresrhys** [comment]
done and released as 3.0.4

**Comment by jshado1** [comment]
@wheresrhys this appears to have regressed: I cannot find any code in [fetch-mock.js](../blob/master/src/fetch-mock.js) (in either the current v6 beta or the latest stable, v5.13.1) that checks whether the argument passed to `fetch` is a `Request` instance.

Also, when a Request instance is passed, `calls` is essentially empty:
```js
{ matched: [], unmatched: [ [ {}, undefined ] ] }
```

Please see the 3rd and 4th commits in https://github.com/jshado1/fetch-mock-test

**Comment by jshado1** [comment]
@wheresrhys I can try to put together a PR this weekend to restore this lost functionality. I don't see any contribution guidelines though.
