### ISSUE TITLE
Feature request: Add option to match request body

### ISSUE THREAD

**Issue by gr2m** [wheresrhys/fetch-mock#442]
Today, I can quite easily match the request body & request headers. Example

```js
fetchMock.postOnce(
  // match URL
  "https://api.github.com/app/installations/123/access_tokens",
  // response body
  {
    token: "secret123",
    expires_at: "1970-01-01T01:00:00.000Z",
    repositories: [{ id: 1 }, { id: 2 }, { id: 3 }]
  },
  {
    // match request headers
    headers: {
      accept: "application/vnd.github.v3+json",
      authorization: `bearer ${BEARER}`,
      "user-agent": "test",
      "content-type": "application/json; charset=utf-8"
    }
  }
);
```

It would be nice to be able to match the request body similar to request headers

```js
fetchMock.postOnce(
  // match URL
  "https://api.github.com/app/installations/123/access_tokens",
  // response body
  {
    token: "secret123",
    expires_at: "1970-01-01T01:00:00.000Z",
    repositories: [{ id: 1 }, { id: 2 }, { id: 3 }]
  },
  {
    // match request headers
    headers: {
      accept: "application/vnd.github.v3+json",
      authorization: `bearer ${BEARER}`,
      "user-agent": "test",
      "content-type": "application/json; charset=utf-8"
    },
    // match request body
    body: {
      permissions: {
        contents: "read"
      }
    }
  }
);
```

The current workaround is to use a matcher function

```js
fetchMock.postOnce(
  // match URL
  "https://api.github.com/app/installations/123/access_tokens",
  // response body
  {
    token: "secret123",
    expires_at: "1970-01-01T01:00:00.000Z",
    repositories: [{ id: 1 }, { id: 2 }, { id: 3 }]
  },
  {
    // match request headers
    headers: {
      accept: "application/vnd.github.v3+json",
      authorization: `bearer ${BEARER}`,
      "user-agent": "test",
      "content-type": "application/json; charset=utf-8"
    },
    // match request body using matcher function
    matcher(_, request) {
      expect(JSON.parse(String(request.body))).toStrictEqual({
        permissions: {
          contents: "read"
        }
      });
      return true;
    }
  }
);
```

With the matcher function  I need to provide my own assertion and it’s a little more code.

Apologies if this was requested before. I searched the docs and issues and couldn’t find anything about request body matching

**Comment by wheresrhys** [comment]
@leggsimon was requesting this feature a few days ago too, and IIRC may have volunteered to implement it. Am I right?

**Comment by gr2m** [comment]
> Also might be tricky matching (Request) vs (url, options) calls

I’m not sure what you mean with `Request`? Can I pass in a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object into matcher functions today?

**Comment by leggsimon** [comment]
@wheresrhys Yeah so I raised this with you before and you said the same, that request bodies can be made up of a lot of things which is potentially a can of worms and maintenance nightmare (my words).

The thing I suggested the other day was that I wondered how if we at least only supported matching JSON bodies, would that cover _most_ of the use cases. There will, of course, be people using fetch-mock with Form data and blobs etc… but I wonder if this could support at least matching against a JSON body if the `Content-type: "application/json"` header existed.

I’m not sure what the API would look like personally, like where would that matcher option go?

Using @gr2m’s examples above I wonder whether it should look something like 

```js
fetchMock.postOnce(
	// first argument becomes a matcher object
	{
		url: 'https://api.github.com/app/installations/123/access_tokens',
		// match the headers
		headers: {
			accept: 'application/vnd.github.v3+json',
			authorization: `bearer ${BEARER}`,
			'user-agent': 'test',
			'content-type': 'application/json; charset=utf-8',
		},
		// match request body
		body: {
			permissions: {
				contents: 'read',
			},
		},
	},
	// second argument is still the response body

	{
		token: 'secret123',
		expires_at: '1970-01-01T01:00:00.000Z',
		repositories: [{ id: 1 }, { id: 2 }, { id: 3 }],
	},
);
```

**Comment by jackocnr** [comment]
I would also love to see this. And only supporting matching JSON request bodies would fulfil my requirements as well 👍
