### ISSUE TITLE
Is there a way to mock without responding?

### ISSUE THREAD

**Issue by subyraman** [wheresrhys/fetch-mock#452]
Cheers for the library! My question is, given the following:

- the UI initially displays a loading indicator.
- when the UI loads, it requests a fetch.
- after the fetch occurs, the UI renders out content based on fetched data.

I'd like to test the "loading" state, which means that in the test, the fetch should not be resolved. Looking through the documentation I am unsure if `fetchMock` has the ability to _not_ respond to requests. Is this possible?

**Comment by subyraman** [comment]
On digging it seems like the answer might be something like 

`fetchMock.get('data', new Promise(() => {}));`

Maybe an addition to the docs would be helpful here?

**Comment by wheresrhys** [comment]
The docs do say:

> Accepts any of the following values or a Promise for any of them (useful when testing race conditions etc.)

What would you add?

**Comment by wheresrhys** [comment]
I've added this as an extra use case to the docs
