### ISSUE TITLE
Is there a way to inspect body/query params and respond with dynamic data?

### ISSUE THREAD

**Issue by gcdurastanti** [wheresrhys/fetch-mock#454]
Looking through the documentation I can't seem to find anything that would solve this issue so I figured I'd come here for some clarification. My use case is simple.

Given: 

`fetch('/artifact/:id', { params: { id: 1 } })`

 where `1` represents an Identifier but can change based on the interaction point, is there a way to setup a fetch mock that would be able to see that query param and respond with different data based on what that is set to. 

i.e.

```
const responseMap = {
  0: 'foo',
  1: 'bar',
  2: 'baz',
};

fetchMock.get('express:/artifact/:id', (url, options) => {
  return responseMap[options.params.id]; 
});

yields: 'bar'
```

**Comment by wheresrhys** [comment]
No there isn't. I would accept a PR to implement it, though I'm not sure what the API should look like. Overloading the `options` object with a `params` property feels ok I guess

You could implement something for yourself by using https://github.com/pillarjs/path-to-regexp and applying it to `url`
