### ISSUE TITLE
Create a more jest-friendly wrapper

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#458]
Jest is dominating the js testing world, and fetch-mock is not idiomatic in its assertion API.

Will publish another package that:

- requires fetch-mock
- has some helpers for easier jest set-up
- implements the jest mock function interface (with some fetch-specific extensions)

**Comment by wheresrhys** [comment]
mockFn.mock.calls
mockFn.mock.results
mockFn.mock.instances
mockFn.mockClear()
mockFn.mockReset()
mockFn.mockRestore()
.toHaveBeenCalled()
.toHaveBeenCalledTimes(number)
.toHaveBeenCalledWith(arg1, arg2, ...)
.toHaveBeenLastCalledWith(arg1, arg2, ...)
.toHaveBeenNthCalledWith(nthCall, arg1, arg2, ....)
.toHaveReturned()
.toHaveReturnedTimes(number)
.toHaveReturnedWith(value)
.toHaveLastReturnedWith(value)
.toHaveNthReturnedWith(nthCall, value)

**Comment by milesj** [comment]
While I have ran into the pain of `fetchMock.spy()` having a different API than Jest spies, I wonder if `const spy = jest.spyOn(global, 'fetch')` would suffice here?

**Comment by wheresrhys** [comment]
That's a good idea. Do you not experience problems with the fact that both fetch-mock and jest mocks use the `.mock` property for different purposes?

**Comment by milesj** [comment]
@wheresrhys Never used it for anything more than checking what has been called (which `spyOn` above seems to cover): https://github.com/milesj/interweave/blob/4428876ef02d568b83c7ea6443e577e99b56f556/packages/emoji/tests/useEmojiData.test.tsx#L110

Others may have more complex use cases.

**Comment by bstchow** [comment]
@wheresrhys Trying to figure out the best way to make jest and fetch-mock play nice with one another. Would love to help out with https://github.com/wheresrhys/fetch-mock-jest if that's the relevant repo

**Comment by wheresrhys** [comment]
@bstchow just seen your offer of help - thanks.

I came across it because I was coming to this issue to close it because I have just released fetch-mock-jest. Your help beta testing it would be much appreciated https://github.com/wheresrhys/fetch-mock-jest
