### ISSUE TITLE
fetch-mock@8.0.0-alpha.14 is currently published as latest

### ISSUE THREAD

**Issue by gr2m** [wheresrhys/fetch-mock#472]
```
$ npm info fetch-mock version
8.0.0-alpha.14
```

I just want to let you know about it, it does not look like it was intended? Did you mean to publish it using an `@alpha` dist-tag?

**Comment by wheresrhys** [comment]
This is surprising, but `npm info` isn't documented in the cli https://docs.npmjs.com/cli-documentation/, so I'm not really sure what that command even aims to provide.

But this is a bit alarming. I'm not sure when npm introduced a prerelease dist tag as an additional requirement on top of, y'know, having a version which, by the semver standard, is already _defined as being a prerelease_!!!

I am quite annoyed at npm for introducing this behaviour, but grateful to you for reporting 😄 . I will release a no-change version from master to make sure nobody else gets accidentally opted in to the alpha.

**Comment by wheresrhys** [comment]
Now resolves to 7.7.3 (although the npmjs.com page for it is yet to update)

**Comment by gr2m** [comment]
I can confirm that it's fixed now 👍 

by default, npm publishes to the `@latest` dist-tag, no matter what you put into the version. 

When you publish alpha versions, you can do so with 

```
npm publish --tag alpha
```

People installing with `npm install fetch-mock` won't get the version, they have to explicitly do `npm install fetch-mock@alpha`, which is great for alpha testers. 

You can also add a `"publishConfig" property to your package.json while you are working on the alpha version, then you won't forget it by chance

```
{
  "publishConfig": {
    "tag": "alpha"
  }
}
```

None of this was recently introduced, it's been there for as long as I remember :)

**Comment by taion** [comment]
btw, you can just use `npm dist-tag add` to overwrite a tag, instead of publishing a new version
