### ISSUE TITLE
Version 8 pulls in an old version of babel-runtime, resulting in core-js old version

### ISSUE THREAD

**Issue by waynebrantley** [wheresrhys/fetch-mock#476]
Here is the dependency tree.  As you can see your main project uses current version of core-js, but the runtime uses old one.

├─┬ fetch-mock@8.0.0
│ ├─┬ babel-runtime@6.26.0
│ │ └── core-js@2.6.10
│ └── core-js@3.4.5

Could upgrade the babel-runtime...or do you have to take dependencies on these - just let users of package polyfill as needed?

**Comment by wheresrhys** [comment]
Does this cause anything to break for you?

I agree it's a bit messy, and wish I'd noticed this wen releasing v7, but if nothing's actually broken, think I'll leave it be for now

**Comment by waynebrantley** [comment]
Unsure if it is an issue - causes warnings on npm install and thought you would want to know.  As far as I know, it is not an issue, just thought you would want to cleanup.....maybe next version?

Best to remove the dependency completely - why do you specifically need/use it?

**Comment by wheresrhys** [comment]
There to support one of the many weird and wonderful setups people have. If you search the issues you'll find lots of mentions of babel & core-js

I'm kicking myself for not tidying up before the v8 release (which was very recent), but I can live with it for now.
