### ISSUE TITLE
set-cookie header

### ISSUE THREAD

**Issue by Martin7mind** [wheresrhys/fetch-mock#478]
fetchMock.get("https://mydomain.com", { status: 200, headers: { 'Set-Cookie': 'hello=hello; Max-Age=3600; Path=/;' }})

if i fetch https://mydomain.com, document.cookies does not contain "hello". Am i doing something or wrong how can i mock this?

**Comment by wheresrhys** [comment]
Oh, this is a nice new requirement. set-cookie is part of the browse/http spec (https://tools.ietf.org/html/rfc6265#section-4.1), not the fetch spec. As fetch-mock prevents request getting out of js and into the browser, set-cookie will have no effect.

This is a good feature request, and could be met by doing a feature detect for `document.cookie` and then writing to it.

To unblock you while you wait for the feature to land, you can implement this yourself:
```
fetchMock.get("https://mydomain.com", () => {
  const cookieString = 'hello=hello; Max-Age=3600; Path=/;';
  document.cookie = cookieString;
  return { status: 200, headers: { 'Set-Cookie': cookieString }};
})
```

**Comment by wheresrhys** [comment]
I'm not 100% sure it's worth implementing; the end user would still need to take care of unsetting the cookie after the test has completed, and I absolutely won't be implementing anything in fetch-mock to assist with that (unsetting side effects would be quite some scope creep for the library). Given that asymmetry, I think the best solution is just to find the right place in the documentation to put an example that both sets and unsets a cookie.
