### ISSUE TITLE
TypeScript warning in types index

### ISSUE THREAD

**Issue by thenickcox** [wheresrhys/fetch-mock#480]
Using TypeScript 3.6.4, Babel 7.6, and webpack 4.3.3, and Jest 24.9.0, and importing fetchMock as follows:

```typescript
import fetchMock from 'fetch-mock';
```

I get the following TypeScript warning:

```typescript
Module '"[path_to_project_root]/node_modules/fetch-mock/types/index"' can only be default-imported using the 'esModuleInterop' flag
```

Adding the `esModuleInterop` flag to my `tsconfig.json` doesn't make the error go away, but I feel like that's actually a TypeScript issue.

However, I noticed that the last line of the types index file is

```typescript
export = fetchMock;
```

I don't know enough about the TS compiler and export syntax to know, but I believe making that `export default fetchMock` would fix the error. Though I don't know what other issues that would cause.

I also tried `import * as fetchMock from 'fetch-mock'`, which resolves the warning, but then in my tests, I get 

```
TypeError: fetchMock.mock is not a function
```

What am I doing wrong? I also read the "Importing the Correct Version" section of the docs, as well as usage with Jest, and am still confused.

**Comment by thenickcox** [comment]
I also just tried

```
import * as fm from 'fetch-mock';
const { mock, reset } = fm;
...

// in test
mock('url', ...);
```

And that satisfied TypeScript, because `mock` is part of the `FetchMockStatic` interface, but when I run the tests, I get `TypeError: mock is not a function`.

**Comment by wheresrhys** [comment]
I don't really know typescript either. Sorry it's causing you problems, but will have to wait for a better typescripter than I to debug.

@grug Do you have anything better to add?

**Comment by grug** [comment]
Hey @thenickcox can you share your `tsconfig`? I'll try recreate it locally and then we can take it from there :)

**Comment by thenickcox** [comment]
Hi, @grug. Thanks a lot for hopping on this. I'll also help out any way I can. Our organization relies heavily on this library. (Thanks a lot for writing it, @wheresrhys!)

Here's my tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "./dist",
    "preserveWatchOutput": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["./src/**/*"],
  "exclude": ["./src/**/*.test.ts", "./node_modules/**/*"]
}
```

Note that that `esModuleInterop` flag is set to `true`, which the compiler suggests will fix the issue, but it doesn't.

**Comment by grug** [comment]
Hey @thenickcox - I'll give this a go first thing in the morning and report back to you with my findings :)

**Comment by scottwalter-nice** [comment]
@thenickcox  Did you ever figure this out?  I am also struggling to get fetch-mock imported

**Comment by wheresrhys** [comment]
Did anybody ever get anywhere with this? Closing the issue unless there is more activity
