### ISSUE TITLE
Explore writing a node http mocking module with a similar api

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#487]
[nock](https://github.com/nock/nock) is the 'market leader' for http mocking in nodejs, and is also the original motivation behind developing this library as I found it's api quite unwieldy.

I get a lot of feedback that the fetch-mock api is intuitive, so it's worth exploring if a sister library - node-http-mock? - could be developed with a similar api, but which deals with lower level http requests, and can therefore be used as a http mock for any application

Could wrap nock??

**Comment by redaxmedia** [comment]
Sure, nock looks more advanced and fetch-mock properly can learn a couple of things. Being the so called market leader doesn't mean that nock is better. I give it a shot recently but this crap doesn't work with Jest and React as it returns "Network request failed" all over the place.
