### ISSUE TITLE
Implement optional partial body matching

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#489]
Currently requests must match an entire JSON body

It seems valuable to allow an option `partialBodyMatching: Bool [default: false]` to match with similar semantics to [jest's objectContaining](https://jestjs.io/docs/en/expect#expectobjectcontainingobject) 

Could use https://www.npmjs.com/package/is-subset

**Comment by wheresrhys** [comment]
@leggsimon you'd love to take this on wouldn't you?

**Comment by leggsimon** [comment]
Yeah, could do. I’m not sure about the API though. Are you thinking that that `partialBodyMatching` option should be a property on the `matcher` object? For example:

```js
fetchMock.mock("http://example.com/", 200, {
  partialBodyMatching: true,
  body: {
    key1: "value1"
  }
});
```

Personally I think that interface seems a little clunky but I’m not sure if there’s a nicer option that wouldn’t be a breaking change.

Also, I would say it’s not immediately obvious, the above example would match the following bodies

```JSON
{ "key1": "value1" }
```

```JSON
{ "key1": "value1", "key2": "value2" }
```

But should it match: 

```JSON
{
	"foo": {
		"bar": {
			"key1": "value1",
			"key2": "value2"
		}
	}
}
```

**Comment by wheresrhys** [comment]
yes to the API. But also it could be set as a global option so if a user is after partial matching then they can just set it once.

On the not immediately obviousness, it's how jest's object matching works to basically follow th object tree and for a match to occur the body would have to have the same value for the same property at the same depth. I can't remember what the array behaviour is

**Comment by wheresrhys** [comment]
Decided I'd just do this. Quite easy in the end
