### ISSUE TITLE
fetch-mock: No fallback response defined for POST

### ISSUE THREAD

**Issue by Emanuell-Dan** [wheresrhys/fetch-mock#497]
All my **GET** requests are going through but **POST** ones fail. This happens when I update `fetch-mock` from `7.3.0` to `7.3.1` or **later**.

**console.warn** `Unmatched POST to url`

**Error** `fetch-mock: No fallback response defined for POST to url`

**http.js**

```js
const API_ERROR_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED"
};

const handleJsonResponse = async response => {
  const text = (await response.text()) || "{}";
  const json = JSON.parse(text);
  if (response.ok) {
    return Promise.resolve(json);
  }

  switch (json.errorCode) {
    case API_ERROR_CODE.UNAUTHORIZED:
      window.location.replace(json.url);
      break;
    default:
      return Promise.reject({ status: response.status, ...json });
  }
};

export const get = (url) => {
  const options = {
    method: 'GET',
    credentials: 'same-origin'
  };

  return fetch(url, options).then(handleJsonResponse);
};

export const post = (url, body) => {
  const headers = {
    "content-type": "application/json",
    "pragma": "no-cache",
    "cache-control": "no-cache"
  };

  return fetch(url, {
    credentials: "same-origin",
    method: "POST",
    cache: "no-cache",
    body: JSON.stringify(body),
    headers
  }).then(handleJsonResponse);
};
```

**http.spec.js**

```js
import fetchMock from "fetch-mock";
import { get, post } from "./http";

describe("Http", () => {
  const url = `${CONTEXT_PATH}/`;

  afterEach(() => {
    fetchMock.reset().restore();
    jest.resetAllMocks();
  });

  describe("get", () => {
    it("makes a GET request", async () => {
      fetchMock.mock({
        name: "route",
        matcher: url,
        method: "GET",
        credentials: "same-origin",
        response: {
          status: 200,
          body: []
        }
      });

      const response = await get(url);

      expect(response).toEqual([]);
    });
  });

  describe("post", () => {
    it("handles unauthorized error", async () => {
      window.location.replace = jest.fn();

      const requestBody = { request: "request" };
      const expectedError = {
        errorCode: "UNAUTHORIZED",
        url: "/invalid/"
      };

      fetchMock.mock({
        name: "route",
        matcher: url,
        method: "POST",
        credentials: "same-origin",
        cache: "no-cache",
        body: JSON.stringify(requestBody),
        headers: {
          "content-type": "application/json"
        },
        response: {
          status: 401,
          body: expectedError
        }
      });

      await post(url, requestBody);

      expect(window.location.replace).toBeCalledWith(expectedError.url);
    });
  });
});
```

I have got `node-fetch` imported globally - version `2.6.0`.
`jest` version is `24.9.0`.

I am not sure what am I doing wrong and/or how to fix this. I have googled this extensively but I did not manage to find anything useful.

**Comment by Emanuell-Dan** [comment]
I've dug into the module itself and something weird happens in the `fetch-handler`. `route.matcher(url)` returns false even though the url is identical - it fails even if I compare it to itself - e.g. `route.matcher(route.url)`. I've tried looking into the `matcher` method but I could not find anything to hook into..

In version `7.3.0` there's no **cjs** and in later versions it's the `fetch-handler` in **cjs** that's being used. I've tried referencing the **es5 handler** but this didn't work either..

**Comment by wheresrhys** [comment]
By 'later', do you mean you've tried the latest version, v8.3.1?

One thing that jumps out at me from your report is that the error message is 'fetch-mock: No fallback response defined for POST to **url**'

The fact that it says 'url' rather than an actual url suggests that you may be passing in the string `'url'` instead of the variable `url` at some point. but in your example I can't see where that might be.

**Comment by Emanuell-Dan** [comment]
Thanks for your message @wheresrhys!

To answer your first question, yes, whether I update from `7.3.0` to `7.3.1` or straight to the latest `8.3.1` I end up getting the same error described above.

In regards to the **url**:

```const url = `${CONTEXT_PATH}/`;``` - **CONTEXT_PATH** is **/shop/car-insurance/** and the error I am getting is `fetch-mock: No fallback response defined for POST to /shop/car-insurance/
`

**Comment by sslotsky** [comment]
I think I'm having a similar problem in 8.3.1. Not sure if it's related. I've implemented some retry logic and I'm asserting that the fetch mock was called `MAX_RETRIES + 1` times. The test passes, but I still get a bunch of `Unmatched GET` warnings.

To help debug this, I've printed out the calls that I expect to be matched:

```ts
      pages.forEach(p => {
        console.log(
          `${p.name} calls: `,
          fetchMock.calls(`${p.address}/__console/${p.version}/menu`)
        );
      });
```

Here's the output for the first entry in that array:

```
    catalog calls:  [
      [
        'https://catalog.stage.manifold.co/__console/v1/menu',
        undefined,
        request: undefined,
        identifier: undefined,
        isUnmatched: true
      ],
      [
        'https://catalog.stage.manifold.co/__console/v1/menu',
        undefined,
        request: undefined,
        identifier: undefined,
        isUnmatched: true
      ],
      [
        'https://catalog.stage.manifold.co/__console/v1/menu',
        undefined,
        request: undefined,
        identifier: undefined,
        isUnmatched: true
      ],
      [
        'https://catalog.stage.manifold.co/__console/v1/menu',
        undefined,
        request: undefined,
        identifier: undefined,
        isUnmatched: true
      ]
    ]
```

The fact that they were printed should mean that they are _matched_, but notice that each entry says `isUnmatched: true`.

**Comment by Emanuell-Dan** [comment]
@wheresrhys I have found out where the issue was.

In my code (and the snippet above) I am **stringifying** the body `JSON.stringify(body)`. Your `generate-matcher.js` is **parsing** it `JSON.parse(body)` and then compares the two - the point which was causing the failure. I am now just sending it as the raw object.

**Comment by WangLarry** [comment]
fetchMock.config.fallbackToNetwork = true

**Comment by wheresrhys** [comment]
Glad you found the cause
