### ISSUE TITLE
On mocks with delayed responses, done() returns true before the request has finished

### ISSUE THREAD

**Issue by bard** [wheresrhys/fetch-mock#498]
Given this:

```js
fetchMock.mock({
  method: 'GET',
  matcher: 'http://localhost/foo',
  delay: 2000,
  response: {
    status: 200
  }
})

fetch('http://localhost/foo')
```

Then `fetchMock.done('http://localhost/foo')` will start returning `true` while the request is still in flight. 

My expectation was that it would return `true` when the request was, well, done.

Repro:

```js
global.fetch = require('node-fetch')
const fetchMock = require('fetch-mock')

fetchMock.mock({
  method: 'GET',
  matcher: 'http://localhost/foo',
  delay: 2000,
  response: {
    status: 200
  }
})

const report = (startTime) => {
  console.log(
    `at ${Date.now() - startTime}ms: `,
    fetchMock.done('http://localhost/foo'))
}

const test = () => {
  const startTime = Date.now()
  report(startTime)
  setInterval(() => report(startTime), 500)

  fetch('http://localhost/foo')
    .then(() => console.log('got response'))
}

test()
```

Output:

```
$ node -v
v12.14.0
persistence:/tmp/test$ node test.js
Warning: http://localhost/foo not called
at 0ms:  false
at 505ms:  true
at 1010ms:  true
at 1516ms:  true
got response
at 2018ms:  true
at 2521ms:  true
^C
```

Above, `done()` only returns `false` before the request is sent. As soon as the request is sent, `done()` starts returning `true`, regardless of completion.

This may be a problem of assumption more than anything, namely my incorrect assumption that "done" = "request done". If that's the case, is there any other way to know when mocked requests are finished?

**Comment by wheresrhys** [comment]
`done()` is for inspecting if fetch has been _called_ the expected number of times, so this is the intended behaviour. I'll see if I can make the docs clearer though.

If you need something in your tests to wait for responses to complete then you need the `flush` method
