### ISSUE TITLE
fetchMock Import failed & can't run test suite with ts-jest

### ISSUE THREAD

**Issue by viT-1** [wheresrhys/fetch-mock#501]
fetch-mock 8.3.1
jest: 24.9.0
ts-jest: 24.3.0

Using `npm run test` with jest config:
```
testMatch: ['**/*.*(spec|test).*(ts|js)'],
transform: {
	'.*?\\.(ts|js)$': 'ts-jest',
},
```
nothing about fetch in jest setup scripts

My test file for code with default modern browser fetch:
```
import fetchMock from 'fetch-mock';
fetchMock.mock({
	url: 'begin:/activity/findpoints',
	response: Promise.resolve([
		{ label: 'foo' },
		{ label: 'bar' },
		{ label: 'baz' },
	]),
});
```

Test suite failed to run with error:

```
Jest encountered an unexpected token
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    testProject\node_modules\fetch-mock\esm\client.mjs:3552
    export default client;
    ^^^^^^

    SyntaxError: Unexpected token export

    > 1 | import fetchMock from 'fetch-mock';
        | ^

      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (services/PointSvc/PointSvc.u.spec.ts:1:1)
```

Trying but isn't working too:
```
import * as fm from 'fetch-mock';
const { mock: mockFetch, restore: restoreFetch } = fm;
mockFetch({
	url: 'begin:/activity/findpoints',
	response: Promise.resolve([
		{ label: 'foo' },
		{ label: 'bar' },
		{ label: 'baz' },
	]),
});
```

**Comment by viT-1** [comment]
https://github.com/facebook/jest/issues/2550

**Comment by viT-1** [comment]
https://github.com/kulshekhar/ts-jest/issues/881

**Comment by viT-1** [comment]
https://github.com/facebook/jest/issues/4842

**Comment by wheresrhys** [comment]
Try using `npm install fetch-mock-jest@1.1.0-beta.3`. It's a wrapper around fetch-mock (exporting the same API and more), and in this beta release I attempt to fix the jest compatibility problem when running in a browser. I'm going to close this issue, but let me know if there are any issues by commenting on https://github.com/wheresrhys/fetch-mock-jest/pull/5

**Comment by viT-1** [comment]
@wheresrhys 
with beta.3 on running tests I have another error:
```
Test suite failed to run

    TypeError: src\services\PointSvc\PointSvc.u.spec.ts: Emit skipped

      at getOutput (../node_modules/ts-jest/dist/compiler.js:162:23)
      at Object.compile (../node_modules/ts-jest/dist/compiler.js:187:29)
      at TsJestTransformer.process (../node_modules/ts-jest/dist/ts-jest-transformer.js:101:41)
      at ScriptTransformer.transformSource (../node_modules/@jest/transform/build/ScriptTransformer.js:453:35)
      at ScriptTransformer._transformAndBuildScript (../node_modules/@jest/transform/build/ScriptTransformer.js:523:40)
      at ScriptTransformer.transform (../node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
```

**Comment by viT-1** [comment]
Sorry, "Emmit skipped" error is same for [jest-fetch-mock setup](https://github.com/jefflau/jest-fetch-mock/issues/110#issuecomment-578619105)

**Comment by viT-1** [comment]
@wheresrhys I don't understand how to configure fetchMock from 'fetch-mock-jest' with minimal code for typescript tests: https://github.com/wheresrhys/fetch-mock-jest/issues/6
Please help me.

**Comment by viT-1** [comment]
@wheresrhys I run tests by `npm run test`

**Comment by wheresrhys** [comment]
Could you please share a repo that recreates the issue. It'll really help isolate if this is a fetch-mock, fetch-mock-jest, jest or ts issue

**Comment by viT-1** [comment]
@wheresrhys 
Yes, with jest-fetch-mock test is ok, but with fetch-mock is not.
[This commit](https://github.com/viT-1/systemjs-ts-es6-vue/commit/4a1eb3b47a6c0fea5479864ce6f1236cf9317d87) with trying to migrate to your package.

**Comment by wheresrhys** [comment]
Please try v9 of this library and reopen the issue if it's still broken
