### ISSUE TITLE
`npm install fetch-mock` installs beta version

### ISSUE THREAD

**Issue by gr2m** [wheresrhys/fetch-mock#506]
The `@latest` version published to npm points to `9.0.0-beta.2`. Was this intended?

```
$ npm info fetch-mock version
9.0.0-beta.2
```

You can make `latest` point back to `8.3.2` by doing

```
$ npm dist-tag add fetch-mock@8.3.2 latest
```

**Comment by wheresrhys** [comment]
oh, that's a mistake, but not catastrophic - the only breaking change is an extremely edge case. I'm about to release v9 for real now
