### ISSUE TITLE
fetchMock.fallbackToNetwork: Need option to fallback to localhost but not other www network traffic

### ISSUE THREAD

**Issue by patrickliechty** [wheresrhys/fetch-mock#508]
We need the option to fallbackToNetwork when localhost is hit, but not when www network traffic is hit. 
 We don't want unit tests to hit the www, but we don't mind localhost.  That way our unit tests will be reliable.  if a www network call is made and fails, the unit test will be flaky.  Localhost network calls are reliable and we need a way to get local assets.  We either need an option to allow localhost network calls when fallbackToNetwork is set to false or when fallbackToNetwork is set to false, it will allow localhost network calls.  Here is some code inside a unit test:

fetchMock.fallbackToNetwork = false;
//Will hit localhost to fetch sample_data.json.  This is desirable and should work
let sampleData;
fetch('sample_data.json').then(x => x.json()).then(sd => { sampleData = sd; });

//This call should not hit the www network and an error should be thrown
let liveData;
fetch('http://mysite.com/user').then(x => x.json()).then(ld => { liveData = ld; });

**Comment by wheresrhys** [comment]
@patrickliechty I just stumbled across this short-lived issue

I guess you found a workaround, but might be interested to know that you can now choose which traffic falls through to the network by passing a matcher in to `.spy()`. For your use case you would  use `fetchMock.spy(/localhost/)`. Other interesting use cases are also possible e.g. read from the network, but don't write is possible with `fetchMock.spy({method: 'get'})`

**Comment by patrickliechty** [comment]
Thank you for the information.  I will use the fetchMock.spy(/localhost/)
