### ISSUE TITLE
when using partial body matching, fetchMock.getOption is not there

### ISSUE THREAD

**Issue by keremciu** [wheresrhys/fetch-mock#510]
I'm so excited about your changes in the library recently. partial body matching is a great one 🎊 

I updated library to 9.10 to use that feature but my tests are broken now.

```TypeError: Cannot read property 'getOption' of undefined``` error is this one.

How it's occurred? 

Basically I'm writing some tests like this one:

```
expect(
        fetchMock.called(/v1\/comments/, {
          method: "POST",
          body: {
            comment: {
              body: comment.body,
            }
          }
        })
      ).toBeTruthy();
```

If I remove body, it works because the problem is finding fetchMock instance: https://github.com/wheresrhys/fetch-mock/blob/master/src/lib/generate-matcher.js#L225

I've no idea how can I affect this generateMatcher code and put default fetchMock instance there as second argument:
https://github.com/wheresrhys/fetch-mock/blob/master/src/lib/inspecting.js#L10

What do you recommend for this case?

fetchMock.filterCalls is in same situation while it's related to same generateMatcher function

**Comment by wheresrhys** [comment]
Fixed in v9.1.1
