### ISSUE TITLE
using query params inside matcher is not part of identifier

### ISSUE THREAD

**Issue by keremciu** [wheresrhys/fetch-mock#516]
As you can see here: https://github.com/wheresrhys/fetch-mock/blob/25559337842a67fd6c6a02bbb0dbaad671332791/src/lib/set-up-and-tear-down.js#L19 library looks clashes with route.identifier.

I have a warning for the code below because of it:
```js
fetchMock.get(
  {
    url: "v1/users",
    query: {
      permission: "Comment"
    }
  },
  200
);
fetchMock.get(
  {
    url: "v1/users",
    query: {
      permission: "Test"
    }
  },
  200
);
```

It says:
`fetch-mock: Adding route with same name or matcher as existing route. See `overwriteRoutes` option.`

I don't wanna write query params inside my URL like this: 

```
"v1/users?permission=Test"
```

unfortunately in one case, I have a lot of query params, if I write in URL it looks messy :/

Do you think we can change matcher function a bit for this case?

**Comment by keremciu** [comment]
okay I managed with route.name

```
fetchMock.get(
  {
    name: "getComments",
    url: "v1/users",
    query: {
      permission: "Comment"
    }
  },
  200
);
fetchMock.get(
  {
    name: "getTests",
    url: "v1/users",
    query: {
      permission: "Test"
    }
  },
  200
);
```

but still wanted to leave it open maybe this name is not that explicit to find.

**Comment by wheresrhys** [comment]
Thanks for the feedback. I've added the following to the docs

![image](https://user-images.githubusercontent.com/447559/77238625-e4d53d00-6bc9-11ea-9de2-4bb6666a3e24.png)
