### ISSUE TITLE
feat: node-fetch's natural exports should be re-exported by mock

### ISSUE THREAD

**Issue by chet-manley** [wheresrhys/fetch-mock#528]
The `node-fetch` package exports helpers like `Headers` and `Response` by default, allowing Node projects to use them in their code, usually like so:
```javascript
const { default: fetch, Headers } = require('node-fetch')
const headers = new Headers(...)
fetch('...', {headers})
```
If your code relies on these utilities, mocking `node-fetch` causes errors, such as: `TypeError: Headers is not a constructor`. It would be nice if `fetch-mock` (and `fetch-mock-jest` by association) re-exported these useful utilities, so as not to break production code. 

[Repl.it demonstrating issue](https://repl.it/repls/DarkvioletImmaterialIteration)

**Comment by chet-manley** [comment]
My current work-around:
```javascript
// __mocks__/node-fetch.js
'use strict'

const nodeFetch = require('node-fetch')
const fetchMock = require('fetch-mock-jest')
const fetch = fetchMock.sandbox()

module.exports = exports = fetch
module.exports.default = exports
module.exports.Headers = nodeFetch.Headers
module.exports.Request = nodeFetch.Request
module.exports.Response = nodeFetch.Response

```

**Comment by wheresrhys** [comment]
I think this is a good idea. Thanks for raising it.

There is however some nuance:fetch-mock is configurable to use _any_ implementation of fetch, and node-fetch is not the only one available (although it is the most popular), so I don't want to rush into this. Specifically, I wonder if I should export using proxies that can be used as getters for properties on fetchMock.config

Will think about it for a bit

**Comment by chet-manley** [comment]
Reviewing your code, I see that the default behavior is to pull `Headers`, `Request`, and `Response` directly from `node-fetch` into your `config`, and allowing the user to overload each of them with their own implementation. A good compromise that leaves this behavior intact, would be to expose each of those classes either on the main `fetchMock` class or instance class provided by `FetchMock.createInstance`, pulling them from the config. Then, re-expose the sandbox class on a circular `default` property (`sandbox.default = sandbox`) to prevent breaking code that implements `node-fetch`'s export pattern. This adds useful functionality while preventing any breaking changes to your existing module.

**Comment by wheresrhys** [comment]
I followed your reasoning there apart from the bit about sandbox. Could you put together a draft PR to demonstrate what you mean?
