### ISSUE TITLE
Remove advanced features

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#53]
Apologies for copying everyone in. I want to know if anyone's using the advanced features of this module https://github.com/wheresrhys/fetch-mock#advanced-usage? I'm planning on removing them in v4 and  instead just documenting a few examples of how to achieve similar behaviour using `beforeEach()` blocks and `.mock()` chaining. 

Speak now or forever hold your peace! (And happy New Year)

@Meabed @dannynelson @choonkending @jwarby @JamesLuoau @developit @DominicTobias @vbauerster @jfairbank @vyorkin @yagudaev @enricomarino @Rastopyr @danawoodman @noisecapella @goblindegook @vagusX @LucaColonnello @akatebi @pwalsh @albburtsev @sapegin @voy @badenkov @NOX73 @maksad @bs1180 @kaid @troybetz @yanivtal @mathieumg @sairion @christopherscott @s-shin

**Comment by vyorkin** [comment]
:christmas_tree: me not

**Comment by jwarby** [comment]
Also not using :+1: Happy New Year too!

**Comment by sapegin** [comment]
Looks like I do:

```js
/**
 * Mock URL.
 *
 * @param {String} url URL to mock.
 * @param {Object|Function} [result] Result body.
 * @param {Number} [status=200] Response HTTP status.
 * @param {Object} [headers] Response HTTP headers (default: Content-Type=application/json).
 */
global.mockUrl = function(url, result = {}, status = 200, headers = {'Content-Type': 'application/json'}) {
    fetchMocked = true;
    fetchMock.mock({
        routes: [
            {
                name: url,
                matcher: url,
                response: (requestUrl, requestOpts) => {
                    return {
                        body: typeof result === 'function' ? result(requestOpts, requestUrl) : result,
                        headers,
                        status
                    };
                }
            }
        ]
    });
};
```

Maybe it can be rewritten.

**Comment by choonkending** [comment]
Not using! Happy new year! :tada:

**Comment by wheresrhys** [comment]
@sapegin That should still be supported in version 4. It's only persistent routes added using `registerRoute()` or `unregisterRoute()` that will go

**Comment by wheresrhys** [comment]
And could be rewritten (as of v3/4) as

```
fetchMock.mock(url, (requestUrl, requestOpts) => {
                    return {
                        body: typeof result === 'function' ? result(requestOpts, requestUrl) : result,
                        headers,
                        status
                    };
                });
```
