### ISSUE TITLE
FetchMock.getMock seems always undefined as of 4.0.0

### ISSUE THREAD

**Issue by dschulten** [wheresrhys/fetch-mock#56]
I am using FetchMock with Mockery as Node 4 module, hence I need to get a handle on the mocked fetch() function.

Registering the node-fetch mock with `myMock.getMock()` as shown below leads to an undefined fetch function in the code under test.

```
'use strict';

var fetchMock = require('fetch-mock');
var mockery = require('mockery');

describe('fetch mockery', function () {

  beforeEach(function () {
    mockery.enable({useCleanCache: true});
    var myMock = fetchMock
      .mock('http://auth.service.com/user', '{"foo": 1}');
    mockery.registerMock('node-fetch', myMock.getMock());        <-- undefined
  });

  afterEach(function () {
    fetchMock.restore();
    mockery.deregisterMock('node-fetch');
    mockery.disable();
  });

  it('should mock a request', function () {

    var goFetch = require('../lib/fetchsample'); // just a call to fetch in a separate module

    return goFetch('http://auth.service.com/user').then(function (response) {
      return response.json();
    }).then(function (json) {
      console.log(json);
    });
  });

});

```

As a workaround, the necessary fetch function mock is availabe as `myMock.mockedContext.fetch`:

```
mockery.registerMock('node-fetch', myMock.mockedContext.fetch);
```

Maybe the fix would be to change `getMock()` in fetch-mock.js like so:

```
	/**
	 * getMock
	 * Returns a reference to the stub function used to mock fetch
	 * @return {Function}
	 */
	getMock () {
		return this.mockedContext.fetch;
	}
```
Or am I using fetch-mock incorrectly here?

**Comment by wheresrhys** [comment]
thanks for pointing this out. Not sure what in v4 would've broken it, or why the tests still pass. I'll fix the tests and add your solution

**Comment by wheresrhys** [comment]
Ah no, you're missing `fetchMock.useNonGlobalFetch(require('node-fetch'));` before your tests. That should fix it.
