### ISSUE TITLE
Having some trouble getting this to work within react/redux/webpack application.

### ISSUE THREAD

**Issue by deep-c** [wheresrhys/fetch-mock#57]
Hi,

Sorry if this isn't the right place to put this however im really struggling to get this working. Ive explained the issue I'm having here http://stackoverflow.com/questions/34574682/unable-to-get-fetch-mock-working-with-webpack-and-redux-react.

Im not sure if I am doing something completely wrong but ive tried so many different things and this is my last resort. Any help would be appreciated. 

Thanks

**Comment by wheresrhys** [comment]
From reading your code it looks like you're not interested in analysing calls to fetch, just in returning a mock response - is that right? In that case you could just return `new Response(url, opts)` using code similar to https://github.com/wheresrhys/fetch-mock/blob/master/src/fetch-mock.js#L17 and leave the call to `fetch` out of your implementation. 

I could expose my mockResponse function as a static helper method if that'd be useful

**Comment by deep-c** [comment]
Hi,

Yea thats right.

I managed to get this working by using window.fetch instead of just fetch. From what i thought, fetch (from isomorphic fetch) for the browser would use that from the global window object which it patches if necessary (think i read that in the docs somewhere). It seems that fetch being referenced in my code isnt the same fetch as that of the browser window object (which upon logging in the console returns the mock function). 

This just means that i have to annoyingly reference window.fetch until i get my backends up and then change all references to fetch when i dont need the mock response any longer and I need to start rendered things server side.

**Comment by SpaceviewMob** [comment]
We had the exact same issue. Found a solution, but it required a bit of extra code that we have now shared.

https://github.com/spaceviewinc/fetch-mock-forwarder

**Comment by wheresrhys** [comment]
I'd happily accept  PR to document this in the troubleshooting section of the readme

**Comment by theosherry** [comment]
Hey, I was having similar problems, and I resolved it by importing isomorphic-fetch to the global namespace rather than importing it to a variable.  I see in your code that you were importing it to a variable as well, so this might be a solution for you.

**Comment by esBeee** [comment]
Hi!
I am having a very similar issue, also with a react/redux/webpack application, and am running out of ideas. I try to use fetch-mock in a unit-test, that's supposed to test a function I import from another file, but a real request is being performed (I've also described the problem more exact [on StackOverflow](http://stackoverflow.com/questions/35414966/mocking-an-outgoing-request-inside-an-async-redux-action-in-a-node-app-doesnt-w)). Can anyone please give me a hint on what I am missing?

**Comment by marc-romera** [comment]
@SpaceviewMob solution worked for me

**Comment by esBeee** [comment]
Fantastic, it works for me, too! Thank you @marc-romera and @SpaceviewMob !

**Comment by wheresrhys** [comment]
FWIW I think @SpaceviewMob's solution, while it works, is an anti-pattern. In the browser `fetch` is supposed to be a global, as defined by the whatwg standard - any modules you're importing to provide as a `fetch` implementation should be considered as temporary polyfills for browsers that lack the native functionality. Assigning `fetch` to a variable departs from the standard, which means at some point in the future you will likely have to refactor. 

I cannot see any good reason not to use fetch as a global in the browser, or am I missing something???
