### ISSUE TITLE
Missing type for `lastResponse`

### ISSUE THREAD

**Issue by ashoksudani** [wheresrhys/fetch-mock#576]
Thanks for this beautiful library.

Just wanted to point that it does not have type for `lastResponse` in defined typescript types.

![Screenshot 2020-06-29 at 2 46 55 PM](https://user-images.githubusercontent.com/552975/85982086-d0e67600-ba17-11ea-9cfa-5576eacddaad.png)

**Comment by wheresrhys** [comment]
Please submit a PR to modify the types.
