### ISSUE TITLE
NotSupportedError:ReadableStream uploading is not supported in Safari when a native POST with payload has processed through fallbackToNetwork

### ISSUE THREAD

**Issue by lambdalisue** [wheresrhys/fetch-mock#584]
First of all, thanks for this great project. It's simple and efficient 👍 

Well, so using fetchMock like below cause "NotSupportedError: ReadableStream uploading is not supported" **only in Safari**. The behavior has confirmed with Safari version 13.1.2 (15609.3.5.1.3) on macOS Catalina version 10.15.6

```javascript
async function main() {
  fetchMock.config.fallbackToNetwork = true;
  fetchMock.get("http://example.com", {
    state: 200,
    body: {},
  });

  console.log("GET");
  await ky.get("https://httpbin.org/get");
  console.log("OK");

  console.log("POST");
  await ky.post("https://httpbin.org/post");
  console.log("OK");

  // Uncomment the below to fix the issue
  //fetchMock.restore();
  console.log("POST with payload");
  await ky.post("https://httpbin.org/post", {
    json: {
      foo: "bar",
    },
  });
  console.log("OK");
}
```

![](https://user-images.githubusercontent.com/546312/88761220-a79d3f00-d1a9-11ea-8027-2a80bbc48fb7.png)

I made a repository to reproduce the issue here if you needed.
https://github.com/lambdalisue/fetch-mock-test

**Comment by wheresrhys** [comment]
Thanks for the thorough bug report. I'll look into it

**Comment by wheresrhys** [comment]
I suspect it's a flavour of this bug https://bugs.webkit.org/show_bug.cgi?id=203617
