### ISSUE TITLE
Add extra params in response object

### ISSUE THREAD

**Issue by k010** [wheresrhys/fetch-mock#59]
Hey guys, thanks for this is great !!
It would be nice to add some extra param in response object for eg: *statusText*, *etc*... [Fetch Response](https://developer.mozilla.org/en-US/docs/Web/API/Response)

What do you think ?
Tks !

**Comment by wheresrhys** [comment]
statusText is the only one missing as far as I can see https://developer.mozilla.org/en-US/docs/Web/API/Response/Response. For completeness, yes that should be configurable.

**Comment by k010** [comment]
:+1:  Thanks !!
