### ISSUE TITLE
How to access query string data

### ISSUE THREAD

**Issue by rubenmoya** [wheresrhys/fetch-mock#597]
Hello!

I'm mocking this endpoint:

```
 http://localhost:3000/api/v1/clients?offset=0&limit=20&orderBy=name:asc
```

using this: 

```ts
fetchMock.get('glob:*/clients*', (url, options) => {
      console.log(url, options)
})
```
I'm getting the URL above in the `url` parameter, and `{ method: 'GET', body: undefined, headers: {} }` in the `options` one.

Is there any way to get the query string data without doing it manually? If not, would it be something that you'd want to do? I'm open to create a pull request if you think it's something that could be useful.

Basically my use case is I have a test that checks the filters on a table are working, I want to check that when I click on `Active` only active clients are shown, and I wanted to reuse the same mock for multiple requests, the first one being when the table loads, and the second one when a filter is clicked. Is there a better approach to do this?

**Comment by wheresrhys** [comment]
I don't 100% sure what the use case is. Could you provide a list of the urls called and the responses you expect from each.

```js
fetchMock.get({url: 'glob:*/clients*', query: {offset: 0}}, (url, options) => {
      console.log(url, options)
})
```
would match on a query string, but I'm not sure whether you want to vary the response based on qs too

**Comment by rubenmoya** [comment]
Yeah, I want to vary the response, for example:

```
http://localhost:3000/api/v1/clients -> [1, 2]
```

And then, when a filter is applied

```
http://localhost:3000/api/v1/clients?q=some_filter -> [1]
```

**Comment by wheresrhys** [comment]
OK. The way I'd do it is
```
fetchMock
.get({
  url: 'glob:*/clients*', 
  query: {q: 'some_filter}
}, [1])
.get({
  url: 'glob:*/clients*', 
}, [1, 2])
```

you might also need `overwriteRoutes: false` on the object in the second mock because the library might not be able to tell that you're not adding the same route twice
