### ISSUE TITLE
Unrecognised Request object, when using new Request()

### ISSUE THREAD

**Issue by roman-balzer** [wheresrhys/fetch-mock#598]
So I have a function, which creates a Request object for me. That function basically just appends some auth infos to the header and builds a path. And finally creates a `Request` Object with `new Request(...)`

```typescript
const request = createCustomRequest('validate', {
  method: 'POST',
  body,
})
const response = await fetch(request)
```
```typescript
export function createCustomRequest(endpoint: string, { body, ...customConfig }: CustomRequestInit = {}) {
  const headers = {
    'Content-Type': 'application/json',
    Accept: 'application/json;charset=UTF-8',
    // ... Setting some headers here
  }

  const config: RequestInit = {
    method: body ? 'POST' : 'GET',
    credentials: 'include',
    ...customConfig,
    headers,
    } as Headers & CustomHeaders,
  }
  if (body) {
    config.body = JSON.stringify(body)
  }
  return new Request(`${basePath}$/${endpoint}`, config)
}
```

When using fetch-mock and trying to mock some Request. I get the error message:
`TypeError: fetch-mock: Unrecognised Request object. Read the Config and Installation sections of the docs`
So, I looked into the code and found: https://github.com/wheresrhys/fetch-mock/blob/4b54e6db42a3e87700ef37a27a7a4d7df29cb3d7/src/lib/request-utils.js#L81-L94
My Request does not have a href property, and typings / [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request) do not specify such a prop. Therefore I'm confused how I should use fetch-mock with `new Request(...)`.

**Comment by wheresrhys** [comment]
Did you read the docs? This bit in particular http://www.wheresrhys.co.uk/fetch-mock/#usagecustom-classes

**Comment by roman-balzer** [comment]
Mhh, maybe I don't understand that part correctly, but i'm using the native `fetch` function and the native `Request` constructor. My function just creates a RequestInit Object which is used by the native `new Request()`. Not using any custom `fetch` oder `Request`.

**Comment by wheresrhys** [comment]
hmmm... maybe something in your build/dependencies is injecting a polyfill somewhere?

Maybe you can try putting a console.log in the fetch-mock code to log out window.Request and Request and see why they're different when you don't do this step?

**Comment by molhanec** [comment]
> Mhh, maybe I don't understand that part correctly, but i'm using the native `fetch` function and the native `Request` constructor. My function just creates a RequestInit Object which is used by the native `new Request()`. Not using any custom `fetch` or `Request`.
> 
> Edit: Okay, i'm a little bit confused about that. I just did whats shown in the doc, but since I use the native functions I provided these. So basically I did this and it works.
> 
> ```ts
> Object.assign(fetchMock.config, { Headers, Request, Response, fetch })
> ```

This actually fixed fetch-mock with RTK query for me.
