### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Request.prototype')

### ISSUE THREAD

**Issue by romanenko** [wheresrhys/fetch-mock#60]
I have a strange error happening in 1.9 PhantomJS and latest Safari environments 

```
TypeError: undefined is not an object (evaluating 'Request.prototype')
```

pointing me to https://github.com/wheresrhys/fetch-mock/blob/b0ca36c6ef632d6786028937e1db46631ef8f5a7/src/fetch-mock.js#L78

I use it in my test like this

```js
import fetchMock from 'fetch-mock'
//...
fetchMock.mock('http://my.api.url/v1/example', [{ ... }])
```

In Chrome, Firefox everything seems to work well.
Why could it happen and are there any advices how to debug it properly?

**Comment by wheresrhys** [comment]
you probably need to polyfill fetch, and possibly Promise too https://github.com/wheresrhys/fetch-mock#troubleshooting. Let me know if that doesn't help

**Comment by romanenko** [comment]
Yes, I had to polyfill `fetch` in Safari and PhantomJS. I'm using Karma with webpack and I had to require file with `isomorphic-fetch` before requiring any spec files.

Thank you very much!

**Comment by PixnBits** [comment]
I had the same error, but when using a dep package that itself used fetch (isomorphic-fetch).
The solution in my case was import/require order: be sure to load fetch-mock _after_ anything that polyfills fetch.
