### ISSUE TITLE
fetch-mock Response.body is not always a stream in Node.js

### ISSUE THREAD

**Issue by fluggo** [wheresrhys/fetch-mock#609]
[WhatWG fetch API spec](https://fetch.spec.whatwg.org/#body-mixin) requires that Body.body is of type ReadableStream. node-fetch [interprets the standard](https://github.com/node-fetch/node-fetch#bodybody) as requiring a Node.js Readable stream. fetch-mock [returns a Buffer](https://github.com/wheresrhys/fetch-mock/blob/4b54e6db42a3e87700ef37a27a7a4d7df29cb3d7/test/server-specs/server-only.test.js#L16) if anything other than a Readable is given to the Response object.

In Node:

```javascript
const fetchMock = require('fetch-mock');
const fetch = fetchMock.sandbox();

fetch.get('http://www.www.com.com', 'woo woo woo');

fetch('http://www.www.com.com').then(resp => resp.body.pipe(process.stdout));
```

...causes:

```
(node:36650) UnhandledPromiseRejectionWarning: TypeError: resp.body.pipe is not a function
    at /Users/fluggo/software/fetchmocktest/test-stream.js:6:56
```

This appears to be a bug in the ResponseBuilder, I have a patch.

**Comment by fluggo** [comment]
Workaround:

```javascript
const stream = require('stream');
const _baseResponseBuilder = require('fetch-mock/cjs/lib/response-builder');

require.cache[require.resolve('fetch-mock/cjs/lib/response-builder')] = {
  ..._baseResponseBuilder,
  exports: (options) => _baseResponseBuilder({ ...options, Stream: stream }),
};

const nodeFetch = require('node-fetch');
// and so forth
```

**Comment by jimmywarting** [comment]
in node-fetch@v3 the res.body is normalized into a node readable stream or null

**Comment by wheresrhys** [comment]
Should not be a problem any more in fetch-mock@10
