### ISSUE TITLE
Support calling a route n times

### ISSUE THREAD

**Issue by queicherius** [wheresrhys/fetch-mock#61]
I want to mock multiple calls to the same route - e.g.

```js
fetchMock.mock('http://test.com', 500)
  .mock('http://test.com', {valid: 'response', after: 'error'}
  .getMock()

// code that calls a url multiple times depending on the response
```

Right now, the first defined route that matches always answers. Any way around that?

**Comment by wheresrhys** [comment]
Easiest way would be to manage the state outside the mock.
```
let called = false;
fetchMock.mock('http://test.com', function () {
   if (called) {
     return {valid: 'response', after: 'error'};
   }
   return 500;
   called true;
})
```
(If that doesn't work it's a bug, so let me know and I'll fix it if it fails)

If you have any thoughts on what a nicer API for this sort of behaviour would look like I'm happy to consider adding it.

**Comment by wheresrhys** [comment]
I could accept an additional parameter specifying the number of times a mock should respond, but I'd be concerned about adding more complexity to the API and docs (which are already long enough IMO)

**Comment by queicherius** [comment]
Yeah the managing the state outside works, I was just wondering if I was overlooking something :smile: 

The `times` parameter would make this easier, but I am not sure if that usecase is so common that it justifies it.

**Comment by wheresrhys** [comment]
It's a feature I'd like to add anyway, though it does get a little bit tricky to implement in some of the details. Will have a go

**Comment by wheresrhys** [comment]
Some failing tests written https://github.com/wheresrhys/fetch-mock/compare/times, but the edge cases are quite problematic

**Comment by amit1911** [comment]
i have the same requirement and i am calling `fetchMock.restore()` before mocking another call to the same url and it seems to be working fine. Is this also okay?

**Comment by wheresrhys** [comment]
That'll work, but limiting responding to n calls I think is a nice feature to add anyway

**Comment by montogeek** [comment]
I would like to ask for this feature too, we can use something similar to Nock https://github.com/node-nock/nock#repeat-response-n-times

For example, this is useful when testing polling request, first 3rd requests are the same, but 4th is different

**Comment by wheresrhys** [comment]
done
