### ISSUE TITLE
Jest v27 requires syntax that docs state is not needed for `reset()` method.

### ISSUE THREAD

**Issue by Br4nd0R** [wheresrhys/fetch-mock#614]
This is a request to update the documentation for the [fetchMock.reset() method](https://www.wheresrhys.co.uk/fetch-mock/#api-lifecyclerestore_reset).

After updating to Jest v.27.0.5 I had test suites failing with:
```
Test functions cannot both take a 'done' callback and return something. Either use a 'done' callback, or return a promise.
```

The code that was failing was adhering to what is currently listed in the docs: `afterEach(fetchMock.reset);`.
The fix was to use syntax that is explicitly stated as not needed: `afterEach(() => fetchMock.reset());`

Would appreciate a small fix to [current documentation ](https://www.wheresrhys.co.uk/fetch-mock/#api-lifecyclerestore_reset)that notes this actually may be needed in some circumstances.

**Comment by wheresrhys** [comment]
Fixed.
