### ISSUE TITLE
Problem with fetch-mock and HMR

### ISSUE THREAD

**Issue by markwoon** [wheresrhys/fetch-mock#618]
I'm using fetch-mock 9.11.0 with Storybook 6.3.6.

I'm running into a problem with HMR because fetch-mock is mocking out the hot update request call as well:

```
client.js:1457 Uncaught (in promise) Error: fetch-mock: No fallback response defined for GET to /runtime_main.bcb1fe7d91f923746a39.hot-update.json
    at Object.FetchMock$1.executeRouter (client.js:1457)
    at Object.FetchMock$1._fetchHandler (client.js:1371)
    at Object.FetchMock$1.fetchHandler (client.js:1362)
    at __webpack_require__.hmrM (jsonp chunk loading:537)
```

If I set `fetchMock.config.fallbackToNetwork = true` then HMR works, but I'd really rather not.

Is there a way to configure fetch-mock to ignore these HMR requests?  If not, I'd like to suggest a new feature where we only fallback to network based on a regexp.

Edit: I'm seeing this behavior with Storybook and webpack 5.  This did not happen with Storybook and webpack 4.

Reproduction: https://github.com/markwoon/sb-fetch-hook-test
Run `yarn storybook` to start.
Fool around with `Hello.stories.js` to see it reload (or not) depending on value of `fallbackToNetwork`.

**Comment by wheresrhys** [comment]
You can probably do `.spy(matcher)` (matcher can be a regex) to fallback to network for only certain requests

**Comment by petersendidit** [comment]
@markwoon did you ever figure out better solution? I am seeing the same problem.

**Comment by markwoon** [comment]
@wheresrhys' suggestion worked.

I added the following to my Storybook decorator:

```
fetchMock.spy('end:.hot-update.json');
```
