### ISSUE TITLE
Allow access to `express`-style path parameters in mocked endpoints

### ISSUE THREAD

**Issue by ryanscottaudio** [wheresrhys/fetch-mock#656]
When adding a mock for an `express`-style path (e.g. `express:/example/:foo/:bar`, there is no built-in way to access the parsed values for `foo` and `bar`:

```
const mockedEndpoint = (url, opts) => {
  // we should be able to use { foo: <whatever>, bar: <whatever> } here without additional parsing
};

fetchMock.get('express:/example/:foo/:bar', mockedEndpoint);

fetch('/example/foovalue/barvalue'); // we would have access to { foo: 'foovalue', bar: 'barvalue' } in mockedEndpoint 
```

We're giving `fetchMock.get` enough information (the matching `express`-style pattern and the URL itself) that it should be able to parse out what `foo` and `bar` are and pass them to the callback (potentially as a third argument?).

This issue was called out in https://github.com/wheresrhys/fetch-mock/issues/300 but either wasn't addressed at all or was addressed but in a too-opaque-for-me-to-understand way.

**Comment by wheresrhys** [comment]
Marking as breaking change as it probably has an effect on the function signature for function matchers

**Comment by wheresrhys** [comment]
Probably the thing to do is to have the response function take a CallLog as input; CallLog is naturally extensible, and this will also make the param values (and query string values?) accessible when examining callhistory
