### ISSUE TITLE
done() not recognised matched requests

### ISSUE THREAD

**Issue by thewilkybarkid** [wheresrhys/fetch-mock#657]
I have a sandbox with a single `getOnce` matcher like:

```ts
{
  url: 'https://example.com/some-page/',
  query: { foo: 'bar' },
}
```

When a request to `https://example.com/some-page/?foo=bar` is made it matches successfully.

However, `fetch.done()` returns `false`.

I've been able to work around this by changing the matcher to:

```ts
{
  url: 'begin:https://example.com/some-page/?',
  query: { foo: 'bar' },
}
```

`fetch.done()` then returns `true` as expected.

**Comment by wheresrhys** [comment]
This is due to the unintuitive, and quite confusing implementation of filtering calls in fetch-mock. I'm working on a new library, @fetch-mock/core, which massively simplifies this, so will not be fixing this bug in fetch-mock
