### ISSUE TITLE
es5/client-legacy-bundle.js uses es6 syntax resulting in errors for older browsers

### ISSUE THREAD

**Issue by rmi22186** [wheresrhys/fetch-mock#660]
V9.11.0 (latest as of 10/10/2023)

The es5 directory is advertised as containing `builds of fetch-mock which do not use any JS syntax not included in the [ES5 standard](https://es5.github.io/), i.e. excludes recent additions to the language`.  However, `es5/client-legacy-bundle.js` contains references to `const` and `let`, which are part of es6 syntax.  While this will still run fine in modern browsers, when I run automated cross browser testing, there are syntax errors for older browsers due to them not recognizing const/let/other es6 syntax - One example is FF30. I know this is an old browser, but it was just a test to see if it worked or not.  This bundle should be pure ES5 as advertised.

In my case I am using Browserstack to test on older browsers.  When I do a global find replace for const and let, and change these to var and re-run, it points out that there is a [for/of](https://gist.github.com/rmi22186/7070fcdeb4e6146d763a5e713e88bb6b#file-gistfile1-txt-L261) error which is also es6 (for/in being es5).  It seems perhaps babel requires some configuration to get the transpiling process to run properly.

**Comment by wheresrhys** [comment]
I'm afraid that es5 is so old now that I consider this to be an edge case not worth fixing. If you still need this get in touch and we can discuss my doing it for a bounty.
