### ISSUE TITLE
Falling back to network does not work with relative URLs

### ISSUE THREAD

**Issue by Knagis** [wheresrhys/fetch-mock#669]
when `fetch-mock` is running with `fallbackToNetwork = true`, any relative URLs are always prepended with `/`

`fetch("image.png")` results in network request to `"/image.png"`, when the index.html is not hosted on the root of the domain.

This is because of normalizeURL rebases the URL not to the current pathname:

```
	} else {
		const u = new URL(url, 'http://dummy');
		return u.pathname + u.search;
	}
```

**Comment by Knagis** [comment]
One potential workaround for this could be

```
new URL(url, typeof location === "undefined" ? 'http://dummy' : location.href);
```

**Comment by wheresrhys** [comment]
I now have a 'fix' for this being rolled out in @fetch-mock/core https://github.com/wheresrhys/fetch-mock/pull/805
