### ISSUE TITLE
`.getMock()` returns undefined

### ISSUE THREAD

**Issue by jarofghosts** [wheresrhys/fetch-mock#68]
Using browserify + fetch-mock, attempts to get a reference to the mock via `.getMock()` always seems to return `undefined`.

A glance at the code indicates that `getMock` just returns `this.fetch` which doesn't seem to be set anywhere.

**Comment by wheresrhys** [comment]
Could you post a code sample and details of which browser please

**Comment by jarofghosts** [comment]
```js
require('isomorphic-fetch')

var mock = require('fetch-mock')

console.log(mock.getMock()) // undefined

mock.mock('lol/', 'ok')

console.log(mock.getMock()) // undefined
```

tried in chrome and phantomjs

**Comment by wheresrhys** [comment]
thanks, I'll investigate over the weekend

**Comment by wheresrhys** [comment]
I see, you're using the API incorrectly

`getMock()` is only intended for use when you're not mocking the global fetch instance and need a reference to the mocked function so you can assign it to a variable and use as a stub/spy. 

What are you trying to use getMock for?

**Comment by jarofghosts** [comment]
Very sorry! The code I presented here was just made up to try and reproduce in as few lines as possible, but it turns out that what I want to do actually does work, so I can close this.

```js
const fetchMock = require('fetch-mock')

fetchMock.useNonGlobalFetch(require('isomorphic-fetch'))
fetchMock.mock('lol/', 'ok')

const mock = fetchMock.getMock() // works
```
