### ISSUE TITLE
Mock two consecutive calls with different responses without explicit access to the calling context.

### ISSUE THREAD

**Issue by ipg0** [wheresrhys/fetch-mock#685]
I have a function that makes multiple fetch calls with the same request, and expects to receive different responses.

It would appear logical that you can use `.mock()`, and then `.once()` (or vice versa, or multiple `.once()` calls) in order to achieve this, but what happens instead is the following error is thrown:
```
fetch-mock: Adding route with same name or matcher as existing route. See `overwriteRoutes` option.
```
, which makes the `once` functionality almost entirely useless.

The doc says:
> If the route has already been called _repeat_ times, the call to `fetch()` will fall through to be handled by any other routes defined

Which would imply that one URL can be handled by multiple mocks, but, apparently, it seems like that is not the case.

Code example:

```ts
fetchMock
      .once(
        `${apiHost}/endpoint`,
        () =>
          new Response(
            JSON.stringify({
              code: 401,
              message: 'Unauthorized',
            }),
            {
              status: 401,
            },
          ),      )
      .mock(
        `${apiHost}/endpoint`,
        () =>
          new Response(
            JSON.stringify({
              code: 200,
              message: 'ok',
            }),
            {
              status: 200,
            },
          ),
      );
```

**Comment by ipg0** [comment]
Found the solution: apparently, if two handlers match the same _URL_, they are given the same `name` by default, and the `name` is supposed to be unique. The solution is to explicitly pass a unique `name`:

```ts
fetchMock
      .once(
        `${apiHost}/endpoint`,
        () =>
          new Response(
            JSON.stringify({
              code: 401,
              message: 'Unauthorized',
            }),
            {
              status: 401,
            },
          ),
        { name: 'unauthorised' },
      )
      .mock(
        `${apiHost}/endpoint`,
        () =>
          new Response(
            JSON.stringify({
              code: 200,
              message: 'ok',
            }),
            {
              status: 200,
            },
          ),
        { name: 'success' },
      );
```

**Comment by wheresrhys** [comment]
Hi - you'll be glad to hear this behaviour will be improved in the new version of fetch-mock I'm working on. matchers will no longer be coerced into pseudo-names, and only routes that are explicitly named the same thing will cause a clash like this.

**Comment by ipg0** [comment]
@wheresrhys thanks, looking forward to integrate
