### ISSUE TITLE
`headers` are not matched strictly

### ISSUE THREAD

**Issue by posva** [wheresrhys/fetch-mock#716]
Hello I noticed that when using `toHaveFetched(url, { headers: {} })`, it will always pass no matter what headers are passed but it should pass only if no headers are passed

```js
    fetchMock.get('/api', { body: {} })
// custom wrapper around fetch
    await api.get('2')
    expect(fetchMock).toHaveFetched('/api/2', {
      headers: {
        // no Accept
        Accept: 'application/json'
        // 'Content-Type': 'application/json',
      },
    })
```

**Comment by wheresrhys** [comment]
I think this is expected behaviour, though could be documented better. 

Matching based on non-existence of headers doesn't feel like a common requirement, and can be implemented using a function  matcher, so I don't think I will implement this as it risks complicating the API

**Comment by posva** [comment]
In my case I was testing that a bearer token wasn't being passed anymore. That seems like a very common use case to me, but maybe there is a better way of checking missing headers without a custom function matcher

I understand that headers being inclusive, an empty object means _no check_. While some custom `missingHeaders` option could be added with addMatcher, it seems quite common to check for missing headers and have it natively would also allow it to be typed

**Comment by wheresrhys** [comment]
Perhaps a solution would be a user-maintained library of custom matchers - living in maybe a /user-matchers directory, which users could copy from there and add themselves using the `addMatcher()` method. They could live in this repo, but as they would not be a part of the API I wouldn't have to take responsibility for testing them and making sure they don't break.

**Comment by wheresrhys** [comment]
Actually, having thought about it, if you submitted a PR to implement a `missingHeaders` matcher in the new @fetch-mock/core library then I think I will accept it. Your use case sounds like a good one

**Comment by posva** [comment]
Alright, I will give this a try the next week 😄
