### ISSUE TITLE
Cannot consume CJS build with TypeScript

### ISSUE THREAD

**Issue by wolfy1339** [wheresrhys/fetch-mock#726]
TypeScript users that don't use ESM are unable to use the include CJS build.

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("fetch-mock")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"`
```

If I patch the `package.json` in `node_modules` and remove the `"type": "module"` field it stops complaining and everything works just fine

**Comment by wheresrhys** [comment]
Hi @wolfy1339 

could you try patching by adding a package.json `{"type": "module"}` inside the fetch-mock/types directory and let me know if that works?

**Comment by wolfy1339** [comment]
That doesn't work. The `"type": "module"` gets inherited from the root anyways.

My source code is CJS, which is what TypeScript means by "The current file". TypesScript believes that `fetch-mock` is only ESM even though there is a `require` property in the exports map.

The only thing that has worked is removing `"type": "module"` from the root `package.json` of `node_modues/fetch-mock`

According to this blog post, there shouldn't be a `"type": "module"` in the root `package.json` for packages that publish both ESM and CJS.
Thttps://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by wheresrhys** [comment]
Could you please set up a reduced test case repo I can use to test this out. I'll need to create a variety of repos with a variety  of module system set ups to check that any change I put in for this use case doesn't break any others. As I'm not a typescripter I'd appreciate some help setting up a representative project.

**Comment by wolfy1339** [comment]
This is the minimal code required to reproduce the issue
https://github.com/wolfy1339/fetch-mock-typescript

```
index.ts:1:23 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("fetch-mock")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`.

1 import fetchMock from "fetch-mock";
                        ~~~~~~~~~~~~


Found 1 error in index.ts:1
```

**Comment by wheresrhys** [comment]
I've tested out your suggested change and although it would fix this ts issue it would break the ability to import fetch-mock from a javascript ESM project. So it's not a simple solution and needs more thought and exploration. I will try to look at it this week. In the meantime I suggest either trying v9 or forking this repo for now.

**Comment by wheresrhys** [comment]
Try v10.1.1-alpha.1

**Comment by wolfy1339** [comment]
Yup that fixes it
