### ISSUE TITLE
Clearing routes

### ISSUE THREAD

**Issue by joeltrew** [wheresrhys/fetch-mock#77]
I'm testing the same url route in a few different tests, i.e one test to see if a 200 response is handled correctly another to check that 400 response is handled correctly.  fetch-mock seems to remember the mocked routes between tests and this obviously causes issues when you need the mocked url to return a different response. I'm currently setting the routes array to an empty array before each test. Is there a better way? reset() seems to only clear calls, matched call etc. Thanks

**Comment by wheresrhys** [comment]
`.restore()`

**Comment by joeltrew** [comment]
Sorry for the slow response, yes `.restore` works great, not sure how I missed that one! Thanks
