### ISSUE TITLE
`.../es5/client-bundle.js` no longer exist

### ISSUE THREAD

**Issue by gian1200** [wheresrhys/fetch-mock#786]
On `fetch-mock` v9, there is `node_modules/fetch-mock/es5/client-bundle.js`. It seems to have been removed on v10.

Is there any plan to release an equivalent file on `dist` folder? 

This file is useful when testing with Karma.

**Comment by wheresrhys** [comment]
I have no plans to do that at the moment. I suggest sticking with v9 if you can.

Out of interest, what about it is useful for karma? Why can you not just require the default or commonjs builds of fetch-mock from v11?

**Comment by gian1200** [comment]
Yes, probably will stick with v9 for the moment. Karma also supports ESM for loading JS files into the browser (browsers do not support CJS by default). However, Karma do not handle dependencies importation from `node_modules` by default. It only upload files to the browser and executes them in order. With Karma it's usually easier to handle dependencies as global variables (by loading dependencies first).

Actually, there really is no need to keep the original `es5/client-bundle.js`. As long as there is a way to make the reference to `fetchMock` global (eg. `window.fetchMock`) by only loading the dependency file(s) (ESM or not) into the testing browser, it's fine. That'd work with Karma, too.

### Update:
I tried creating a wrapper for the current (v11) ESM file (thinking about a possible PR). However, it seems that it depends on some NodeJS specific libs which are not available on browser (`node:tty`, `node:util`, `node:os`). **Am I missing something or is it correct to say that last version of `fetch-mock` compatible with browsers is v9?**

`dist/esm/index.js`:
![image](https://github.com/user-attachments/assets/dfca6887-70a0-4cd8-b5a0-4c3c185e9492)

**Comment by wheresrhys** [comment]
Yes, going forward I want to avoid doing any bundling, and just provide esm and cjs builds that the end user can take responsibility for packaging up for their environment. 

That said, I do want to avoid making things more complicated than they need to be for users, so I will investigate why those 3 modules are being required as dependencies and try to remove them

**Comment by wheresrhys** [comment]
It's because I include the debug npm package. I will remove it as debugging tools are in general a lot better now, and including debug adds quite  a lot of complexity

**Comment by wheresrhys** [comment]
Released as 11.1

Regarding your wrapper to solve your problem, I'd be interested to see it, and possibly to add the method to the docs, but I'm unlikely to accept a PR unless it's very simple and obvious what the code is doing. I want to keep wrappers, hacks and workarounds targeting various toolchains out of this repo as much as I can

**Comment by gian1200** [comment]
There is one last reference to a NodeJS variable:

`Uncaught ReferenceError: process is not defined`
Line 637 of `node_modules/fetch-mock/dist/esm/index.js`

![image](https://github.com/user-attachments/assets/c9e344d1-bc92-495f-8365-569a0baff43b)

![image](https://github.com/user-attachments/assets/9eb30d99-27c5-4d70-907b-41f72536bd23)

----

### Option 1

After manually fixing it, the wrapper worked.

- `node_modules/fetch-mock/dist/esm/wrapper.js`:
```js
import fetchMock from "./index.js";
window.fetchMock = fetchMock;
```

![image](https://github.com/user-attachments/assets/16bf95c9-afe6-430a-b176-0fcd009b687c)

### Option 2
An equivalent line (`window.fetchMock = index;`) can be put inside `dist/esm/index.js` to make it work without the need of a wrapper:

![image](https://github.com/user-attachments/assets/47d8e1e3-3fd5-4db4-9fc8-d339e35495e6)

**If any of these options is added to the library, then the transition from v9 to v11 will be eased for many devs.**

**Comment by wheresrhys** [comment]
I've now removed the reference to `process`. Is it possible for your wrapper to be defined in your own codebase or is there some reason it would have to be implemented within the fetch-mock package?

**Comment by gian1200** [comment]
I can confirm that `v11.1.1` works on browser 👍🏻 . Thanks!

------

Given that it's a wrapper, by definition can be put anywhere, including my source code.

I suggested the wrapper to be in `fetch-mock` for convenience:
- It makes it easier for all devs who currently uses `fetch-mock` as a global variable (not only when using Karma).
- It makes it easier to upgrade from `fetch-mock` v9 to v11 (viable upgrade path)
- Personally, I believe option 1 from above is cleaner, since it doesn't modify current `fetch-mock` code (and doesn't expose it for those who don't need it). The name of the file can be improved to something else to make explicit it's usage (I'm not good at baptizing things), maybe `legacy-global.js` or `global-wrapper.js`, or something else.

Ultimately is up to the maintainers/owner of the repo to decide.

**Comment by wheresrhys** [comment]
I've decided to leave it out of the codebase, but have added a note to the docs.

Most modern testing tools are able to import modules without needing to define global variables, and as long as there is a workaround for people using older tools such as karma, I think it's ok to not include it here.

Thanks for raising the issue though
