### ISSUE TITLE
Support mocking client-only fetch

### ISSUE THREAD

**Issue by samzhang111** [wheresrhys/fetch-mock#79]
I encountered an issue with GLOBAL using fetch-mock to test a React app. It is the same error as the one posted here: http://stackoverflow.com/questions/35633044/fetch-mock-global-is-not-defined. I used their suggested workaround and it worked for my use-case.

Something as simple as replacing `global` here https://github.com/wheresrhys/fetch-mock/blob/master/src/server.js#L11 with `GLOBAL || global` would allow this to work on client as well as server.

**Comment by phkavitha** [comment]
@samzhang111, Can you share the code where you have defined the global variable? Here is what, I've done but, none of my test cases pass. Not sure what's happening.
```
/* eslint-env jasmine */
jasmine.VERBOSE = true
global.GLOBAL = global
```

And, I have included the `fetch-mock` and `isomorphic-fetch` in the unmockedModulePathPatterns

**Comment by ericlau-solid** [comment]
I am having a similar issue, using fetch-mock to test React app. Getting a window is not defined error (theGlobal: window, )

I use webpack and I load fetch globally using webpack's providePlugin. 
```

new webpack.ProvidePlugin({
			// to figure out how to code webpack module bundler, see: http://forum.shakacode.com/t/understanding-the-webpack-module-bundler/336
      'fetch': 'imports?this=>global!exports?global.fetch!isomorphic-fetch'
    }),
```

Do I need to do something similar for fetch-mock? What's the best way to get fetch-mock going?

**Comment by wheresrhys** [comment]
What's your build process exactly? webpack should respect this https://github.com/wheresrhys/fetch-mock/blob/master/package.json#L6

**Comment by wheresrhys** [comment]
I will probably change `GLOBAL` to `global` as that's what nodejs documents https://nodejs.org/api/globals.html#globals_global. Although arguably react/webpack should support both because both of them are defined in nodejs

**Comment by wheresrhys** [comment]
This is now fixed, though I would still be interested in seeing code samples of what build process and architecture means the server side js is being included on the client side. Are you developing for React Native?

**Comment by phkavitha** [comment]
@wheresrhys , I'm using webpack + ES6 loaders + JEST. If I use es6 import for `isomorphic-fetch` and `fetch-mock`, nothing works. All the test cases fail even after setting the `GLOBAL` variable. However, if I use `require` for both packages, test case runs. But again, the `expect` function is not behaving properly inside the `.then()` handler. For example:

```
    const urlToTest = 'http://localhost:3000/api/v1/users';
    fetchMock.mock(urlToTest, 'GET',  { test_id: '123', test_name: 'test_name' });
    return sendRequest(urlToTest).then(() => {
      expect(fetchMock.called(urlToTest)).toBeFalsy();
      fetchMock.restore();
     });
```
expect should fail actually, but it passes. I'm trying to debug it and find out what's happening to jasmine's expect function.

**Comment by wheresrhys** [comment]
Are you using fetch-mock 4.3.1?

**Comment by phkavitha** [comment]
yes @wheresrhys

**Comment by phkavitha** [comment]
@wheresrhys, Test cases are running fine now (used `pit` instead of `it` when writing test cases) when using `require`.  I found that if we use ES6 import, the `fetch` function is not becoming global. Can you please confirm if that's true?

**Comment by wheresrhys** [comment]
Try this https://www.npmjs.com/package/fetch-everywhere with import instead of isomorphic fetch. Let me know if it works and I'll add to the troubleshooting part of the README. 

I suspect that Jest might be making a mistake in how it works with babel. If you could create a repo with a reduced test case I'll try to verify that that is this case.
