### ISSUE TITLE
`globrex` does not support browser

### ISSUE THREAD

**Issue by kevinlaw91** [wheresrhys/fetch-mock#793]
In the past fetch-mock supports running in browser.
But in recent updates the new dependency `globrex` does not support browser.

You can see it check for `process` object which will throws:
https://github.com/terkelg/globrex/blob/7fa4690cd569d1b91e5f017208ba2b7cc2eca83e/index.js#L1

does this mean latest fetch-mock dropped support for browser env?

**Comment by wheresrhys** [comment]
That's unintentional, introduced by https://github.com/wheresrhys/fetch-mock/pull/707

I'll revert back, but will also take the opportunity to get some tests running in real browsers again (I dropped this when upgrading to ESM)

**Comment by wheresrhys** [comment]
What's your testing toolchain? (ideally can you provide me with a repo with a reduced test case). I now have some tests running using vitest in a browser and it works ok.

**Comment by wheresrhys** [comment]
I've submitted a PR to globrex https://github.com/terkelg/globrex/pull/10. If it doesn't get accepted soon I'll revert to the old library (which I'm reluctant to do as the type definitions it provides are missing/bad)

Weird that codesandbox works online but not locally. I can see that codesandbox [has a lot of webpack config](https://github.com/search?q=repo%3Acodesandbox%2Fcodesandbox-client%20webpack&type=code), so maybe somewhere in there is a plugin that stubs node globals
