### ISSUE TITLE
Would anyone like to co-own this project?

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#80]
As [detailed more extensively on my blog](http://www.wheresrhys.co.uk/2016/one-careful-owner/) I believe in sharing the ownership of open source projects that others depend on. If you'd like to co-own this repo, and can demonstrate reasonable experience of contributing/owning other open source projects, please get in touch. @wheresrhys

**Comment by montogeek** [comment]
@wheresrhys What are your requirements? I could help you :)

**Comment by jackfranklin** [comment]
@wheresrhys I've just added this project to our test suite at work and we'll be relying on it heavily. I've yet to contrib to this library but I'd love to help and give back as this library is very valuable to us at work :)
