### ISSUE TITLE
Module not found: Default condition should be last one

### ISSUE THREAD

**Issue by richard-thai** [wheresrhys/fetch-mock#840]
Trying to use fetch-mock with Next.js and got the following error. I did some digging and found that Webpack expects the exports default condition in package.json to be last in this list, because it is a fallback for environments where no other specific condition applies.

`
Module not found: Default condition should be last one
> 1 | import fetchMock from 'fetch-mock';
    | ^
  3 |
  4 | fetchMock.mock('/test', 200);`

**Comment by richard-thai** [comment]
I manually modified the package.json file inside the node_modules directory, and the changes appear to have resolved the issue with the following modification.

`{
	"exports": {
		"browser": "./dist/esm/index.js",            
		"import": "./dist/esm/index.js",          
		"require": "./dist/cjs/index.js",           
		"types": "./dist/esm/types/index.d.ts",      
		"default": "./dist/esm/index.js"            
	  },
	`

**Comment by wheresrhys** [comment]
Thanks for pointing this out. Fix will be released soon

**Comment by richard-thai** [comment]
Hi Rhys,

Thank you for promptly addressing the issue and providing a fix. I will be testing the new build this morning and will keep you informed if any further issues arise.

Thanks again for your support.


Regards

Richard
