### ISSUE TITLE
Upgrade to 12 guide is wanted :(

### ISSUE THREAD

**Issue by justnewbee** [wheresrhys/fetch-mock#849]
Just upgraded from version 11 to version 12.

But there are to many break changes. It is impossible for me to upgrade without an instruction document.

I tried replacing some APIs according to the types definition, but it didn't make it work as was before.

Please make an upgrade guide. I am very willing to upgrade.

**Comment by eduardo-santos-tribia** [comment]
They already did that: https://www.wheresrhys.co.uk/fetch-mock/docs/Usage/upgrade-guide.

But you still can have issues. In my case, I'm using `fetch-mock` with `react-native`, not only for Tests with Jest, but also to mock requests and use the App during development. To do that, It was required to install this other library to make things work as in `v11`: https://github.com/charpeni/react-native-url-polyfill

**Comment by wheresrhys** [comment]
That sounds like an appropriate solution for your environment. I'll add a note somewhere in the installation guide to highlight this additional dependency

**Comment by wheresrhys** [comment]
I'm quite reluctant to bring in a polyfill; once I go down that route then any type checks, uses of `instanceof` etc become unreliable, and a lot of the improvements I've made to the codebase woudl need to be reverted.

It does seem a bit absurd to me that the react-ntaive-url-polyfill docs say it adds 73kb to bundle size. I wonder if this is still the case. Are you able to check how much weight it actually adds @eduardo-santos-tribia. If it's significantly smaller then I feel less bad about expecting users to add it.

**Comment by eduardo-santos-tribia** [comment]
Of course @wheresrhys , I'm dynamically requiring the `react-native-url-polyfill/auto`and not directly importing. Below you can check the bundle size (I'm using a VSCode extension to get that) when directly importing it.

![image](https://github.com/user-attachments/assets/fcb18ee6-5e8d-4fea-9b38-c910303b4172)

**Comment by wheresrhys** [comment]
Thanks - I'll add a note to the docs with advice for users - thanks for raising it

**Comment by vtintillier** [comment]
Maybe a link to the upgrade guide can be added to https://github.com/wheresrhys/fetch-mock/releases/tag/fetch-mock-v12.0.0 ? I had to search the issues to find it.
Thanks
