### ISSUE TITLE
Behavior of called(matcher) and others may be confusing

### ISSUE THREAD

**Issue by motiz88** [wheresrhys/fetch-mock#87]
This is one of the two related issues that led me to submit #83 (the other is #88).

`calls`, `called`, `lastCall`, `lastUrl`. `lastOptions` are all documented as taking a `matcher` argument. This argument can only meaningfully be a `string` naming an existing route, and thus it differs subtly from the meaning of `matcher` in what's probably the most visible API, `mock()`:

> `matcher` [required]: Condition for selecting which requests to mock Accepts any of the following
	* `string`: ...
	* `RegExp`: ...
	* `Function(url, opts)`: ...

Here is a case where my (incorrect) reading of the docs led to surprising behavior:
```javascript
fetchMock.mock('^http://example.com/');
fetch('http://example.com/one/two').then(() => {
  fetchMock.called('^http://example.com/'); // true
  fetchMock.called('^http://example.com/one'); // false (surprising to me)
  fetchMock.called(/one\/two$/); // false (surprising to me)
});
```

**Comment by wheresrhys** [comment]
The docs are now clearer on this point, using `matcherName` with details of how this is derived from `matcher`

**Comment by fredtma** [comment]
Hi,

I am struggling to get the `fetchMock.called` method to work. The above example all return false.
What am I doing wrong?

```
  it('Test', (done) => {
    fetchMock.mock('^http://example.com/', 200);
    fetch('http://example.com/one/two').then(() => {
      console.log('==========');
      console.log(fetchMock.called('^http://example.com/')); // false
      console.log(fetchMock.called('^http://example.com/one')); // false 
      console.log(fetchMock.called(/one\/two$/)); // false
      done();
    });
  });
```
