### ISSUE TITLE
API to search through calls using matcher syntax

### ISSUE THREAD

**Issue by motiz88** [wheresrhys/fetch-mock#88]
This is one of the two related issues that led me to submit #83.

I propose an API that applies a `matcher` (`string|RegExp|function(url, opts)`) to the whole list of calls, regardless of any configured routes or their names. I consider this behavior useful in composing assertions that aren't possible with `calls(routeName)` or `called(routeName)`, such as:

``` javascript
// Assuming a new method: fetchMock.testCalls
fetchMock.mock('^http://example.com/');
fetch('http://example.com/?arg1=123').then(() => {
  // called() would return false for each of the following
  fetchMock.testCalls('http://example.com/?arg1=123'); // true
  fetchMock.testCalls('^http://example.com/?arg1='); // true
  fetchMock.testCalls(/arg1=\d+$/); // true
});
```

So basically, it would do what I had the impression `called()` and `calls()` _should_ do, as described in #87.
#83 contains a proposed implementation in the form of ~~`callsMatching()` and `calledMatching()`~~ `filterCalls()` and `testCalls()`.

**Comment by motiz88** [comment]
Picking up from https://github.com/wheresrhys/fetch-mock/pull/83#issuecomment-209776377:
> 3) I don't particularly want to have two supported ways of checking for matched calls - that will add to the complexity of the api, and thus increase confusion when it's being used. So if your suggestion was adopted I see it being a major release

Could clearer and more distinct naming (e.g. `filterCalls()`, `testCalls()` as in the updated PR #83) help reduce confusion despite the larger API surface?

**Comment by wheresrhys** [comment]
I'm afraid I'm against adding to the API unless this gets a few :+1:s

**Comment by wheresrhys** [comment]
I've decided to close this - it's been a long time with no supporting comments. Thanks fro submitting though, and for highlighting the confusing nature of the docs
