### ISSUE TITLE
@fetch-mock/jest - register types on jest expect object

### ISSUE THREAD

**Issue by hanseltime** [wheresrhys/fetch-mock#881]
Hey!

Thanks for writing this mock and the documentation about it.  I discovered that the jest matchers package does not put the matches on the `expect` object, and since I would either need to stub the typescript in my own project or contribute it here, I figured, I'd make a feature request for discussion.  

I have currently forked the repo and am locally using the types from my fork, but would love for this to be something that is just built in.  Please feel free to let me know if this is something that the project doesn't want, etc.

https://github.com/wheresrhys/fetch-mock/pull/880 - current fork PR that I am running off of.

Thanks!

**Comment by wheresrhys** [comment]
released as @fetch-mock/jest 0.2.7

Thanks for the PR 😄

**Comment by apoteet** [comment]
Will @fetch-mock/jest 0.2.7 be published to NPM soon?

**Comment by wheresrhys** [comment]
Yep - just rerunning the build now. Didn't realise it had failed
