### ISSUE TITLE
[@fetch-mock/vitest]: 405 "Method Not Allowed"

### ISSUE THREAD

**Issue by budarin** [wheresrhys/fetch-mock#888]
```ts
import fetchMock from '@fetch-mock/vitest';
import { describe, expect, it, afterEach } from 'vitest';

describe('Request', () => {
    const id = 1;
    const apiMethod = 'createTodo';
    const baseUrl = 'https://example.com/api';

    afterEach(() => {
        fetchMock.mockRestore();
    });

    it('Success request', async () => {
        const requestInit = {
            method: 'POST',
            headers: {
                accept: 'application/json',
                'content-type': 'application/json',
            },
            body: JSON.stringify({
                id,
                apiMethod,
                params: {},
            }),
        };

        const response = {
            id,
            result: {
                data: 'some data',
            },
        };

        fetchMock.post(`${baseUrl}/${apiMethod}`, response);
        const result = await fetch(`${baseUrl}/${apiMethod}`, requestInit);

        expect(result.ok).toEqual(true);
        
        const data = await result.json();
        expect(await result.json()).toEqual(response);
    });
    
});
```

it worked well for the last time (I haven't checked the tests for a long time)

But now in the fetchMock response I get:

```js
  const response = await fetch(....);
 
  /*
  Response {
    status: 405,
    statusText: 'Method Not Allowed',
    headers: Headers {
      'content-type': 'text/html; charset=UTF-8',
      date: 'Mon, 02 Dec 2024 11:21:01 GMT',
      server: 'ECAcc (sed/58E3)',
      'content-length': '0'
    },
    body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
    bodyUsed: false,
    ok: false,
    redirected: false,
    type: 'basic',
    url: 'https://example.com/api/createTodo'
  }
  */
```

it seems that fetchMock is configured incorrectly and it is not configurable
```js
        const response = {
            id,
            result: {
                data: 'some data',
            },
        };

        fetchMock.post(`${baseUrl}/${apiMethod}`, response);
```

Env:
"vite": "^6.0.1",
"vitest": "^2.1.6"
"@fetch-mock/vitest": "^0.2.6",
"node": "23.3.0"

**Comment by wheresrhys** [comment]
I think it's probably  a matter of adding a `fetchMock.mockGlobal()` at the beginning of your test. `.post()` no longer replaces the `fetch` global implicitly - it must be done explicitly with a method call.

**Comment by budarin** [comment]
> I think it's probably a matter of adding a `fetchMock.mockGlobal()` at the beginning of your test. `.post()` no longer replaces the `fetch` global implicitly - it must be done explicitly with a method call.

Thanks!
It is necessary to write about this in more detail in the documentation and correct the examples

**Comment by budarin** [comment]
> Can you point me to the examples and where you think it should be documented more clearly?

On the 1st page, the Overview shows the code with the mockGlobal() call, and then in all the examples there is a call without it (for example https://www.wheresrhys.co.uk/fetch-mock/docs/Usage/quickstart#setting-up-your-route )

The description of the mockGlobal method says nothing, except that this method mocks fetch globally. It is not clear from this description how and when it should be called
