### ISSUE TITLE
Not matching when fetch is called with a Request object

### ISSUE THREAD

**Issue by aaronmars** [wheresrhys/fetch-mock#89]
The `normalizeRequest()` function in fetch-mock.js is supposed to check if it is called with a URL string or a Request object.  This is failing, and falling back to the string case when fetch() is invoked with a Request object.

Here's an example:
```
let req = new Request('http://www.example.com', { method: 'GET' });
let p = fetch(req);
```
The following implementation works for me, but may be too simplistic of a fix:
```
function normalizeRequest (url, options) {
    if (typeof url === 'string') {
        return {
			url: url,
			method: options && options.method || 'GET'
		};
	} else {
        return {
			url: url.url,
			method: url.method
		};
	}
}
```

**Comment by wheresrhys** [comment]
Hello,

Before fixing this it'd be good to know which environment it's happening in as the current implementation _should_ work so I'd like to understand a bit more about why it's not

**Comment by aaronmars** [comment]
This is in a node environment, with `isomorphic-fetch` loaded beforehand.

This should replicate the issue for you.
```
require('isomorphic-fetch');
var fetchMock = require('fetch-mock');
fetchMock.mock('http://example.com/', '{"foo": "BAR"}');
var request = new Request('http://www.example.com', { method: 'GET' });
fetch(request).then(function(response) {
    return response.text();
}).then(function(responseText) {
    console.log(responseText);
});
```
That final console log outputs the html from example.com, rather than the mocked JSON.

**Comment by wheresrhys** [comment]
Ah now I see the problem. I guess you're not on npm 3 yet, which means that isomorphic-fetch and fetch-mock don't share an instance of node-fetch unless you call `npm prune`.

I'm not sure whether to fix this with your suggested solution or to add a suggestion to run `npm prune` when not working in npm 3+. The downsides of your solution as I see it are:

1. If fetch is accidentally called with an object or number, say, then, normalize request will return `{url: undefined, options: undefined}`, which could lead to some difficult to debug test failures
1. The primary use case for this module is to mock fetch in the browser, where the problem you're reporting won't occur 

On the other hand, your solution does basically work. Could you run `npm prune` and see if that fixes your problem?

**Comment by aaronmars** [comment]
Well, `npm prune` didn't work.  I even nuked npm_modules, reinstalled, and saw the same problem.
Updating npm worked though!

I was on npm@2.15.1, now I'm using npm@3.8.7.  That's fine for me.

As for the fix, I'm fine with "update npm" being the answer.  I totally agree with the loosey-goosey nature of the fix I suggested, and prefer the code as-is.
