### ISSUE TITLE
Add support (fix bug) for  functions returning a Promise

### ISSUE THREAD

**Issue by dletin** [wheresrhys/fetch-mock#90]
I tried to mock server delays and  I needed a Promise to be created at a time when a request is made to a mocked url, not at a time when we define how to mock a response.
The current implementation does not currently handle a case when the response is mocked as  a function returning a Promise. To fix it for my needs I added one line to fetchMock function, like this:

```
fetchMock (url, opts) {
    const response = this.router(url, opts);
    if (typeof response === 'function')  response = response(url, opts);  // <-- the new line
```

It moves evaluating the "mocking function" from mockResponse to fetchMock because fetchMock has proper logic (using "response.then") for Promises.

**Comment by wheresrhys** [comment]
Is this not already supported via

```
fetchMock.mock('http://my/url', (url, opts) => {
     return new Promise(resolve => setTimeout(() => {
         resolve(200)
      }, 1000));
})
```

**Comment by wheresrhys** [comment]
Ah, ignore the above - in explaining why it does work I realised why it doesn't 😄
