### ISSUE TITLE
how can I return an ArrayBuffer in the body?

### ISSUE THREAD

**Issue by tamird** [wheresrhys/fetch-mock#93]
Currently I'm just returning `{ sendAsJson: false, body: myArrayBuffer }`, but I always wind up with:

```
     TypeError: Invalid non-string/buffer chunk
      at chunkInvalid (_stream_readable.js:399:10)
      at readableAddChunk (_stream_readable.js:144:12)
      at Readable.push (_stream_readable.js:130:10)
      at mockResponse (node_modules/fetch-mock/src/fetch-mock.js:59:6)
      at FetchMock.fetchMock (node_modules/fetch-mock/src/fetch-mock.js:253:12)
```

I'm able to hack around this by wrapping it in a Buffer: `{ sendAsJSON: false, body: Buffer.from(myArrayBuffer) }`, but that's not documented. Is that the intended use?

**Comment by wheresrhys** [comment]
I'll write a failing test and then look at this. It's not a feature I've explored much

**Comment by wheresrhys** [comment]
I've added a test https://github.com/wheresrhys/fetch-mock/pull/95 which passes in node 5. I notice you have `sendAsJSON` in your code when it should be `sendAsJson`. I've managed to get it to pass in node 5 and 6

**Comment by tamird** [comment]
Good point regarding the key name, but this issue is about ArrayBuffer, not Buffer.

**Comment by tamird** [comment]
Ah, and it turns out I wrote the issue incorrectly - the actual code I wrote uses `sendAsJson`.

**Comment by wheresrhys** [comment]
I suggest raising this as an issue on node-fetch, which this library uses to construct responses. It already supports use cases that go beyond the fetch spec, so they could be keen to add support for ArrayBuffer

**Comment by tamird** [comment]
What does this have to do with fetching? The fetch spec already supports ArrayBuffer on the response https://developer.mozilla.org/en-US/docs/Web/API/Body/arrayBuffer

**Comment by wheresrhys** [comment]
I assumed you were running the tests in node (as opposed to in a browser) as the error stack looks more like something generated in node. If this is the case then support for arrayBuffer needs to be added to node-fetch. https://github.com/bitinn/node-fetch/issues/51. Not everything defined in the fetch spec is implemented, or is even intended to be implemented (https://github.com/bitinn/node-fetch/blob/master/LIMITS.md), in node-fetch, but for most use cases it's similar enough.

**Comment by tamird** [comment]
What does this have to do with node-fetch? The error stack is entirely within fetch-mock.

**Comment by wheresrhys** [comment]
Ah I missed that sorry. I now have a failing test and will work on fixing it

**Comment by tamird** [comment]
Great! Any luck?

**Comment by wheresrhys** [comment]
I have a failing test, but I'm still looking into what the behaviour should be with regard to building a Body from binary data. The spec https://fetch.spec.whatwg.org/#bodies mentions that [ReadableStream may change to be ReadableByteStream](https://github.com/whatwg/streams/issues/379), which may have some bearing on it.

Other than that I need to update fetch-mock to use stream.pipe() and add a check body isn't an ArrayBuffer before trying to 'utf8' decode, which may be enough

**Comment by tamird** [comment]
> This might become a ReadableByteStream object. While the type might change, the behavior specified will be equivalent since the hypothetical ReadableByteStream object will have the same members as the ReadableStream object has today.

What bearing would that have on the behaviour? Can you share your failing test? I'd like to help you get this over the finish.

**Comment by wheresrhys** [comment]
here you go https://github.com/wheresrhys/fetch-mock/compare/rhys/buffer

**Comment by tamird** [comment]
FWIW it seems that this mostly works in the browser already (as opposed to NodeJS), but there's still some weirdness in webkit as seen in https://github.com/cockroachdb/cockroach/pull/7178/files - still not quite sure what's going on there.

**Comment by wheresrhys** [comment]
closing due to incativity

**Comment by tamird** [comment]
Sorry, this was https://github.com/github/fetch/pull/351.

**Comment by qjflores** [comment]
was this implemented `update fetch-mock to use stream.pipe()`?

**Comment by wheresrhys** [comment]
@qjflores Please open a new issue if something is missing for you. I have very little memory of what this discussion was about
