### ISSUE TITLE
make the global default sendAsJson configurable

### ISSUE THREAD

**Issue by tamird** [wheresrhys/fetch-mock#99]
We prefer to be explicit rather than implicit, and we'd like for that to be enforced globally. Could you make `sendAsJson` globally configurable so we could set it to `false`?

**Comment by wheresrhys** [comment]
I'll happily accept a Pull request for this. Ideally by means of a `configure()` method that accepts an options object so it's extensible if need be in future

**Comment by wheresrhys** [comment]
Addressed in v5 https://github.com/wheresrhys/fetch-mock/pull/110
